Repository tigera/operator, pull requests merged in 2020-07, with the labels that each got.

#670 Move to scratch
  build/Dockerfile.amd64
  build/bin/entrypoint
  build/bin/user_setup
Labels: kind/enhancement

#663 Automated cherry pick of #616: Add support for allowing some pre-determined metadata
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: enterprise, kind/bug

#662 Automated cherry pick of #616: Add support for allowing some pre-determined metadata
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: enterprise, kind/bug

#672 Move to scratch
  build/Dockerfile.amd64
  build/bin/entrypoint
  build/bin/remove_unneeded.sh
  build/bin/user_setup
Labels: kind/enhancement

#676 [release-v1.2] Use custom Elasticsearch
  cmd/manager/main.go
  config/ee_versions.yaml
  hack/gen-versions/main.go
  pkg/components/versions.go
  pkg/render/elasticsearch.go
  pkg/render/images.go
Labels: enterprise, kind/enhancement

#681 Update versions to release-v2.7
  config/ee_versions.yaml
  pkg/components/versions.go
  pkg/render/images.go
  pkg/render/images_test.go
  pkg/render/manager_test.go
  pkg/render/node_test.go
Labels: enterprise

#685 Set ENTRYPOINT without using ENV variable
  build/Dockerfile.amd64
Labels: kind/bug

#686 Set ENTRYPOINT without using ENV variable
  build/Dockerfile.amd64
Labels: kind/bug

#677 Replace cat utility with in built application
  pkg/render/apiserver.go
Labels: enterprise, kind/enhancement

#698 [release-v1.2] Update flexvol to release-v3.12
  config/os_versions.yaml
  pkg/components/versions.go
Labels: enterprise

#683 Add custom Elasticsearch bits
  cmd/manager/main.go
  config/enterprise_versions.yml
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/render/logstorage.go
Labels: enterprise, hold merge, kind/enhancement

#714 Use correct registry for custom Elasticsearch
  pkg/components/references.go
Labels: enterprise, kind/bug

#721 [release-v1.2] Revert "Use custom Elasticsearch"
  cmd/manager/main.go
  config/ee_versions.yaml
  hack/gen-versions/main.go
  pkg/components/versions.go
  pkg/render/elasticsearch.go
  pkg/render/images.go
Labels: enterprise

#722 Fix test
  pkg/render/kube-controllers_test.go
Labels: enterprise, kind/bug

#723 Automated cherry pick of #722: Fix test
  pkg/render/kube-controllers_test.go
Labels: enterprise, kind/bug

#726 Override the keystore script
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: enterprise, kind/bug

#727 Automated cherry pick of #726: Override the keystore script
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: enterprise, kind/bug

#731 Don't require requestedScopes for AuthenticationCR
  deploy/crds/operator.tigera.io_authentications_crd.yaml
  pkg/apis/operator/v1/authentication_types.go
Labels: enterprise, kind/bug

#719 Allow enabling / disabling BGP
  deploy/crds/operator.tigera.io_installations_crd.yaml
  pkg/apis/operator/v1/types.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/enhancement

#744 Pass OIDC prefixes from Authentication CR to KubeControllers
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/utils/utils.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: enterprise, kind/bug

#750 cherry-pick #742: include v1beta1 amazoncloudintegration in crds
  deploy/crds/operator.tigera.io_amazoncloudintegrations_crd.yaml
  pkg/apis/addtoscheme_operator_v1beta1.go
  pkg/apis/operator/v1beta1/amazoncloudintegration_types.go
  pkg/apis/operator/v1beta1/doc.go
  pkg/apis/operator/v1beta1/register.go
  pkg/apis/operator/v1beta1/zz_generated.deepcopy.go
Labels: enterprise

#776 Cherry-pick support for EKS w/ Calico Networking
  deploy/crds/operator.tigera.io_installations_crd.yaml
  pkg/apis/operator/v1/types.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/render/apiserver.go
  pkg/render/logstorage.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha_test.go
Labels: kind/enhancement

#782 Pin enterprise components to v3.2.0
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: enterprise

#783 Consolidate pip role and manager role
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: enterprise, kind/bug

#786 [1.9] Consolidate pip role into manager role as these permissions are alway…
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: enterprise, kind/bug

#787 Bump enterprise component versions to 2.7.6
  config/ee_versions.yaml
  pkg/components/versions.go
  pkg/render/images.go
  pkg/render/images_test.go
  pkg/render/manager_test.go
Labels: enterprise

#789 Add support for only reconciling our desired annotations
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#793 Automated cherry pick of #790: Fix DNS policy for host-networked pods
  pkg/render/apiserver.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: enterprise, kind/bug
