Repository tigera/operator, pull requests merged in 2020-04, with the labels that each got.

#487 Allow for a configurable storage class name.
  deploy/crds/operator_v1_logstorage_crd.yaml
  pkg/apis/operator/v1/logstorage_types.go
  pkg/apis/operator/v1/zz_generated.openapi.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
Labels: enterprise, kind/enhancement

#489 KubeControllersConfiguration resource
  deploy/crds/calico/02-crd-kubecontrollersconfiguration.yaml
  pkg/render/kube-controllers.go
Labels: kind/enhancement

#497 Add RBAC for the apiserver to read webhook configurations
  go.mod
  go.sum
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: enterprise, kind/enhancement

#496 RBAC for dynamic admission webhook
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: enterprise, kind/enhancement

#498 [release-v1.2] ES NodeSelector
  deploy/crds/operator_v1_logstorage_crd.yaml
  pkg/apis/operator/v1/logstorage_types.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/apis/operator/v1/zz_generated.openapi.go
  pkg/render/elasticsearch.go
  pkg/render/elasticsearch_test.go
Labels: enterprise, kind/enhancement

#499 [release-v1.3] ES NodeSelector
  deploy/crds/operator_v1_logstorage_crd.yaml
  pkg/apis/operator/v1/logstorage_types.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/apis/operator/v1/zz_generated.openapi.go
  pkg/render/elasticsearch.go
  pkg/render/elasticsearch_test.go
Labels: enterprise, kind/enhancement

#504 Bump enterprise component versions to 2.7.4
  config/ee_versions.yaml
  pkg/components/versions.go
  pkg/render/node_test.go
Labels: enterprise

#506 [release-v1.5] Pick DataNodeSelector and StorageClassName
  deploy/crds/operator_v1_logstorage_crd.yaml
  pkg/apis/operator/v1/logstorage_types.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/apis/operator/v1/zz_generated.openapi.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: enterprise, kind/enhancement

#494 [release-v1.4] ES NodeSelector
  deploy/crds/operator_v1_logstorage_crd.yaml
  pkg/apis/operator/v1/logstorage_types.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/apis/operator/v1/zz_generated.openapi.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: enterprise, kind/enhancement

#505 Revert "Move admission controller support behind a tech-preview featu…
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/apiserver/apiserver_suite_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: enterprise, kind/enhancement

#507 Revert "Move admission controller support behind a tech-preview featu…
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/apiserver/apiserver_suite_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: enterprise, kind/enhancement

#517 Switch image references to tags instead of shas
  pkg/components/images_test.go
  pkg/components/references.go
  pkg/render/apiserver_test.go
  pkg/render/guardian_test.go
  pkg/render/kube-controllers_test.go
  pkg/render/manager_test.go
  pkg/render/node_test.go
Labels: kind/enhancement

#519 Bump Centos repo to 8.1.1911 to match ubi version
  build/init/centos.repo
Labels: kind/enhancement

#514 Use CNI private for Calico Enterprise installs
  config/enterprise_versions.yml
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/render/node.go
Labels: kind/enhancement

#538 Add imagepath that was missing for elastic-curator
  pkg/render/logstorage.go
Labels: enterprise, kind/bug

#539 [release-v1.4] cherrypick: Add imagepath that was missing for elastic-curator
  pkg/render/logstorage.go
Labels: enterprise, kind/bug

#540 [release-v1.5] cherrypick: Add imagepath that was missing for elastic-curator
  pkg/render/logstorage.go
Labels: enterprise, kind/bug

#542 [release-v1.4] Bump Calico Enterprise to v2.8.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: enterprise, kind/enhancement

#533 Allow updates to Logstorage resource limits
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: enterprise, kind/bug

#536 add tech preview seccomp selection for node
  pkg/render/node.go
  pkg/render/node_test.go
Labels: enterprise, kind/enhancement

#547 [release-v1.4] cherrypick: Allow updates to Logstorage resource limits
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: enterprise, kind/bug

#548 [release-v1.5] cherrypick: Allow updates to Logstorage resource limits
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: enterprise, kind/bug

#552 [release-v1.4] Bump Calico Enterprise to v2.8.2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: enterprise, kind/enhancement

#549 Update the default cloudwatch fetch interval to 60sec
  deploy/crds/operator_v1_logcollector_crd.yaml
  pkg/apis/operator/v1/logcollector_types.go
  pkg/controller/logcollector/logcollector_controller.go
Labels: enterprise, kind/enhancement

#541 Secret manager-tls must be shared with compliance and kube-controllers
  config/enterprise_versions.yml
  go.sum
  pkg/components/enterprise.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/priority_class.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: enterprise, kind/enhancement

#553 Add check that BGP metrics server is up to readiness probe.
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: enterprise
