Repository tigera/operator, pull requests merged in 2020-12, with the labels that each got.

#1007 Move RootCA to alpine trusted cert location
  go.mod
  pkg/render/dex_config.go
Labels: docs-not-required, release-note-not-required

#1000 add linux nodeselector to elastic, kibana, and ids job
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-not-required, enterprise, release-note-required

#1011 Update README for running locally
  README.md
Labels: docs-not-required, kind/bug, release-note-not-required

#1014 Propagate the KUBERNETES_SERVICE_XXX variables to kube-controllers.
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/elasticsearch_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/render.go
Labels: docs-pr-required, release-note-required

#1015 Propagate the KUBERNETES_SERVICE_XXX variables to API server.
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/k8sapi/k8s-endpoint.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common.go
  pkg/render/common_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-not-required, release-note-required

#1019 Use a constant length for git abbreviations
  Makefile
Labels: docs-pr-required, release-note-required

#1023 Automated cherry pick of #1019: Use a constant length for git abbreviations
  Makefile
Labels: docs-not-required, release-note-not-required

#1022 Automated cherry pick of #1019: Use a constant length for git abbreviations
  Makefile
Labels: docs-not-required, release-note-not-required

#1021 Automated cherry pick of #1019: Use a constant length for git abbreviations
  Makefile
Labels: docs-not-required, release-note-not-required

#1020 Automated cherry pick of #1019: Use a constant length for git abbreviations
  Makefile
Labels: docs-not-required, release-note-not-required

#1018 Propagate k8s API env var to CNI plugin.
  pkg/controller/k8sapi/k8s-endpoint.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1016 [v1.12] Propagate kubernetes service environment variables to kube-controllers, API server and CNI plugin
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/k8sapi/k8s-endpoint.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common.go
  pkg/render/common_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1024 [v1.13] Propagate kubernetes service environment variables to kube-controllers, API server and CNI plugin
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/k8sapi/k8s-endpoint.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common.go
  pkg/render/common_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1013 cherry-pick #1000: add linux nodeselector to elastic, kibana, and ids jobs
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#1012 cherry-pick #1000: add linux nodeselector to elastic, kibana, and ids job
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#1009 Don't panic if we have an empty logStorage spec
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  test/mainline_test.go
Labels: docs-not-required, release-note-not-required

#1027 Update to Calico v3.17.1
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1025 Add replicas and shards to bgp index
  pkg/render/fluentd.go
Labels: docs-not-required, kind/bug, release-note-required

#1026 Switch Updates after defaulting to use Patch
  go.sum
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/manager/manager_controller.go
Labels: docs-not-required, release-note-required

#1004 Add ILM policy for L7 logs
  pkg/controller/utils/elasticsearch.go
Labels: docs-not-required, enterprise, kind/enhancement, release-note-required

#1008 Add L7 access in RBAC and syslog types
  api/v1/logcollector_types.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-not-required, enterprise, kind/enhancement, release-note-required

#1030 Update enterprise components to v3.4.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-not-required, enterprise, release-note-not-required

#1031 Fix formatting
  pkg/render/node_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1033 Fix formatting
  pkg/render/node_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1032 Add some checks for dirty and formating to ci
  Makefile
Labels: docs-not-required, release-note-not-required

#1029 Use FQDN service references
  main.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/logstorage/shim_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/options/options.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/dex_test.go
  pkg/render/elasticsearch_decorator.go
  pkg/render/elasticsearch_decorator_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1034 Make apiserver run as UID 0
  pkg/render/apiserver.go
Labels: docs-not-required, enterprise, release-note-required

#1035 Follow-up fixes to cert SANs
  main.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_suite_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/logstorage/shim_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/options/options.go
  pkg/dns/dns.go
  pkg/dns/dns_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/dex_test.go
  pkg/render/elasticsearch_decorator.go
  pkg/render/elasticsearch_decorator_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1039 Don't hardcode the iptables backend
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-required

#1041 Remove the validatingwebhookconfiguration for elasticsearch.
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1040 Fix logstorage always degraded
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#1042 Remove ECK webhook (2/2)
  pkg/controller/utils/elasticsearch.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1047 fix the dex common name
  pkg/controller/authentication/authentication_controller.go
Labels: docs-pr-required, release-note-required
