Repository tigera/operator, pull requests merged in 2020-11, with the labels that each got.

#979 [master] Automatic update of sempahore YAMLs.
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#970 sort bird mounts alphabetically to prevent reconcile loop
  pkg/render/node.go
Labels: docs-not-required, kind/bug, release-note-not-required

#981 RBAC: Enterprisesearches ends in es, not s
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#980 Switch to custom image for Dex component
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/components/references.go
Labels: delete-branch, docs-pr-required, enterprise, kind/enhancement, merge-when-ready, release-note-not-required

#982 RBAC: Enterprisesearches ends in es, not s
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#983 [cherry-pick for release-v1.12] Custom Dex component
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/components/references.go
Labels: delete-branch, docs-pr-required, enterprise, kind/enhancement, merge-when-ready, release-note-not-required

#975 Add new flag to Authentication spec in order to support OKTA
  api/v1/authentication_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_authentications.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/authentication/authentication_suite_test.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-pr-required, release-note-required

#984 Automated cherry pick of #975: Add new flag to Authentication spec in order to support
  api/v1/authentication_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_authentications.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/authentication/authentication_suite_test.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-pr-required, release-note-required

#985 [release-v1.11] Update components for v3.3.1
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: docs-not-required, enterprise, hold merge, release-note-not-required

#986 Bugfix for checking SyslogLogIDSEvents in syslog.LogTypes field
  pkg/controller/logcollector/logcollector_controller.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#987 [cherry-pick for v1.12] Bugfix for checking SyslogLogIDSEvents in syslog.LogTypes field
  pkg/controller/logcollector/logcollector_controller.go
Labels: docs-pr-required, release-note-required

#963 Changes for auto MTU detection
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/core_controller.go
  pkg/controller/status/status.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-not-required

#988 Release v1.12.0
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: docs-not-required, release-note-not-required

#990 Update Calico to v3.16.5
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#991 release-v1.11: Bump enterprise components to v3.3.2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-not-required, enterprise, release-note-not-required

#993 Validate release tags
  hack/maybe-build-release.sh
Labels: docs-pr-required, release-note-required

#994 Pick: Validate tag before creating release image (#993)
  hack/maybe-build-release.sh
Labels: docs-not-required, release-note-not-required

#996 Use release-v3.17 for Calico versions
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#997 Automated cherry pick of #963: Changes for auto MTU detection
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/core_controller.go
  pkg/controller/status/status.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-not-required

#998 Picking changes from release-v1.11 since v1.11.0 into tech-preview-migrate-install
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#989 dns-templates
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-not-required, enterprise, kind/enhancement, release-note-not-required

#944 Use ILM to manage ES Index
  go.mod
  go.sum
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/logstorage/shim_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/elasticsearch_test.go
  pkg/controller/utils/test_files/01_put_policy.json
  pkg/controller/utils/test_files/02_get_policy.json
  pkg/controller/utils/test_files/02_put_policy.json
  pkg/render/logstorage.go
Labels: docs-pr-required, enterprise, kind/enhancement, release-note-required

#999 Adjust route table range for GKE CNI plugin
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-not-required

#1001 Add migration check for nodes when typha is deployed
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/network_test.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/controller/utils/utils.go
Labels: docs-not-required, release-note-not-required

#995 Allow overrides of 'default' installation resource through second 'overrides' installation resource
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1003 Update versions for v3.17.0
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#638 Adjust typha autoscale
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/controller/migration/convert/typha_test.go
  pkg/controller/utils/utils.go
Labels: docs-not-required, release-note-required

#1002 increase resiliency of new overlay feature
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#1005 Pick typha adjustment and check changes
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/network_test.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#1006 cherry-pick installation overlay into v3.13
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, kind/enhancement, release-note-required
