Repository tigera/operator, pull requests merged in 2020-08, with the labels that each got.

#791 Set routeSource in Felix configuration to WorkloadIPs for aws-vpc CNI
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/bug

#794 Automated cherry pick of #789: Add support for only reconciling our desired annotations
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#795 Automated cherry pick of #789: Add support for only reconciling our desired annotations
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#796 Automated cherry pick of #789: Add support for only reconciling our desired annotations
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#797 Automated cherry pick of #789: Add support for only reconciling our desired annotations
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#800 Automated cherry pick of #789: Add support for only reconciling our desired annotations
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#806 Automated cherry pick of #789: Add support for only reconciling our desired annotations
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#807 Automated cherry pick of #789: Add support for only reconciling our desired annotations
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#798 Automated cherry pick of #789: Add support for only reconciling our desired annotations
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_suite_test.go
Labels: kind/bug

#820 Run the node's init containers as privileged
  pkg/render/node.go
Labels: kind/bug

#832 Automated cherry pick of #820: Run the node init containers as privileged
  pkg/render/node.go
Labels: kind/bug

#831 Automated cherry pick of #820: Run the node init containers as privileged
  pkg/render/node.go
Labels: kind/bug

#830 Automated cherry pick of #820: Run the node init containers as privileged
  pkg/render/node.go
Labels: kind/bug

#829 Automated cherry pick of #820: Run the node init containers as privileged
  pkg/render/node.go
Labels: kind/bug

#828 Automated cherry pick of #820: Run the node init containers as privileged
  pkg/render/node.go
Labels: kind/bug

#827 Automated cherry pick of #820: Run the node init containers as privileged
  pkg/render/node.go
Labels: kind/bug

#833 Automated cherry pick of #774: Add cluster-admin permissions to the compliance controller
  pkg/render/compliance.go
Labels: enterprise, kind/bug

#838 Add CNI file logging by default
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/enhancement

#840 Add CNI file logging by default
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/enhancement

#857 [v1.10] Backport k8s API endpoint override
  pkg/controller/installation/core_controller.go
  pkg/render/common.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: kind/enhancement

#859 cherry-pick to v1.9
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/bug
