Repository tigera/operator, pull requests merged in 2020-09, with the labels that each got.

#871 Update to Calico v3.15.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: kind/enhancement

#877 Bump Enterprise versions to v3.2.1.
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: docs-pr-required, enterprise, kind/enhancement, release-note-required

#874 Cherry-pick Merge pull request #736 from ozdanborne/update-defaults
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/kube-controllers.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, kind/bug, release-note-required

#876 verify and set resoure requirements for individual fields
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#875 Add volume mounts for CNI logging and change the default CNI log level to INFO
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-required

#878 Allow tigera-network-admin to create/delete packet captures
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#881 Update versions for Enterprise v3.3 release branches
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: docs-pr-required, enterprise, release-note-required

#880 Cleanup errors
  pkg/controller/migration/convert/convert.go
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/errors.go
  pkg/controller/migration/convert/k8s.go
  pkg/controller/migration/convert/mtu.go
  pkg/controller/migration/convert/network.go
Labels: docs-not-required, release-note-not-required

#883 Try replacing goautoneg that doesn't exist anymore
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#885 Replace goautoneg to come from a different repo [pick #883]
  go.mod
  go.sum
Labels: docs-not-required, kind/bug, release-note-required

#895 vendor autoneg internally
  Makefile
  go.mod
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#897 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#899 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#900 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#901 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#902 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#903 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#905 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#884 Cleanup tests
  pkg/controller/migration/convert/components.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/migration/convert/convert_test.go
  pkg/controller/migration/convert/core_test.go
  pkg/controller/migration/convert/k8s.go
  pkg/controller/migration/convert/testutils_test.go
Labels: docs-pr-required, release-note-required

#896 move pools to own file
  pkg/controller/migration/convert/ippools.go
  pkg/controller/migration/convert/ippools_test.go
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
Labels: docs-pr-required, release-note-required

#907 Merge tech-preview-migrate-install to stable
  Makefile
  go.mod
  pkg/controller/migration/cni/calicotypes.go
  pkg/controller/migration/cni/cni.go
  pkg/controller/migration/cni/cni_test.go
  pkg/controller/migration/convert/cni_test.go
  pkg/controller/migration/convert/components.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/migration/convert/convert_test.go
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/core_test.go
  pkg/controller/migration/convert/errors.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/ippools.go
  pkg/controller/migration/convert/ippools_test.go
  pkg/controller/migration/convert/k8s.go
  pkg/controller/migration/convert/mtu.go
  pkg/controller/migration/convert/mtu_test.go
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
  pkg/controller/migration/convert/testutils_test.go
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#911 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  go.sum
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#910 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  go.sum
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#909 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  go.sum
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#908 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  go.sum
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#906 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  go.sum
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#904 Automated cherry pick of #895: vendor autoneg internally
  Makefile
  go.mod
  go.sum
  vendor/bitbucket.org/ww/autoneg/README.txt
  vendor/bitbucket.org/ww/autoneg/autoneg.go
  vendor/bitbucket.org/ww/autoneg/autoneg_test.go
  vendor/bitbucket.org/ww/autoneg/go.mod
Labels: docs-pr-required, release-note-required

#882 Move init image functionality into the operator itself
  Makefile
  build/init/Dockerfile.amd64
  build/init/aws-setup-security-groups.sh
  build/init/centos.repo
  build/init/init.sh
  cmd/manager/main.go
  go.mod
  go.sum
  hack/gen-versions/calico.go.tpl
  hack/maybe-build-release.sh
  pkg/awssgsetup/aws_security_group_setup.go
  pkg/components/calico.go
  pkg/components/images_test.go
  pkg/render/aws-securitygroup-setup.go
Labels: docs-not-required, hold merge, kind/enhancement, release-note-required

#916 Remove need for operator-init container (pick #882): Add to operator ability to configure AWS Security groups on
  Makefile
  build/init/Dockerfile.amd64
  build/init/aws-setup-security-groups.sh
  build/init/centos.repo
  build/init/init.sh
  cmd/manager/main.go
  go.mod
  go.sum
  hack/gen-versions/calico.go.tpl
  hack/maybe-build-release.sh
  pkg/awssgsetup/aws_security_group_setup.go
  pkg/components/calico.go
  pkg/components/images_test.go
  pkg/render/aws-securitygroup-setup.go
Labels: docs-pr-required, release-note-required

#915 Degrade Calico status on typha autoscale issues
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
Labels: delete-branch, docs-not-required, kind/bug, merge-when-ready, release-note-not-required

#918 [PICK] Degrade Calico status on typha autoscale issues
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
Labels: docs-pr-required, kind/bug, release-note-required

#917 Add SupportedOSTypes function to Components
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/configmap.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/priority_class.go
  pkg/render/render.go
  pkg/render/secrets.go
  pkg/render/typha.go
Labels: docs-pr-required, kind/bug, release-note-required

#919 Add SupportedOSTypes function to Components
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/configmap.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/priority_class.go
  pkg/render/render.go
  pkg/render/secrets.go
  pkg/render/typha.go
Labels: delete-branch, docs-not-required, kind/bug, merge-when-ready, release-note-not-required

#922 Pin enterprise versions to v3.3.0 for release
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: docs-not-required, enterprise, hold merge, release-note-not-required
