Repository tigera/operator, pull requests merged in 2020-05, with the labels that each got.

#570 Update components
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
Labels: enterprise, kind/enhancement

#566 remove digest machinery (#561)
  cmd/manager/main.go
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/digest.go
  hack/gen-versions/enterprise.go.tpl
  hack/gen-versions/main.go
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/references.go
Labels: kind/bug

#569 packetSize option gets ignored
  deploy/crds/operator_v1_logcollector_crd.yaml
  pkg/apis/operator/v1/logcollector_types.go
Labels: enterprise, kind/bug

#572 [Pick 569][release-v1.6] Use camelCase for the packetSize option
  deploy/crds/operator_v1_logcollector_crd.yaml
  pkg/apis/operator/v1/logcollector_types.go
Labels: enterprise, kind/bug

#575 [release-v1.6] cherrypick: Fix cloud-on-k8s pin
  go.mod
Labels: enterprise, kind/bug

#564 Increase timeout for liveness and readiness probe for fluentD
  pkg/render/fluentd.go
Labels: enterprise, kind/enhancement

#576 [release-v1.6] Increase timeout for liveness and readiness probe for fluentD
  pkg/render/fluentd.go
Labels: enterprise, kind/enhancement

#578 Update enterprise components to 3.0.0
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: enterprise, kind/enhancement

#579 Update registry
  pkg/components/images.go
  pkg/components/images_test.go
  pkg/render/manager_test.go
Labels: enterprise, kind/bug

#596 [release-v1.0] Bump Calico components to v3.10.4 and Enterprise components to v2.6.3
  config/ee_versions.yaml
  config/os_versions.yaml
  pkg/components/versions.go
Labels: enterprise, kind/enhancement

#595 [release-v1.2] Add clusterrole for authenticationreviews
  pkg/render/apiserver.go
Labels: enterprise, kind/enhancement

#600 [release-v1.2] Update Enterprise and Calico component versions
  config/ee_versions.yaml
  config/os_versions.yaml
  pkg/components/versions.go
  pkg/render/node_test.go
Labels: enterprise, kind/enhancement

#601 [release-v1.4] Update Enterprise and Calico component versions
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: enterprise, kind/enhancement
