Repository tigera/operator, pull requests merged in 2020-10, with the labels that each got.

#912 migrate existing installation config when converting
  Makefile
  deploy/crds/operator.tigera.io_installations_crd.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_operator_v1.go
  pkg/apis/apis.go
  pkg/apis/crd.projectcalico.org/v1/doc.go
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/ippool.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/apis/operator/v1/register.go
  pkg/apis/operator/v1/types.go
  pkg/apis/operator/v1/zz_generated.deepcopy.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/migration/cni/calicotypes.go
  pkg/controller/migration/cni/cni.go
  pkg/controller/migration/cni/cni_test.go
  pkg/controller/migration/convert/aws_cni_policy_only_test.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/controller/migration/convert/components.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/migration/convert/convert_suite_test.go
  pkg/controller/migration/convert/convert_test.go
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/core_test.go
  pkg/controller/migration/convert/errors.go
  pkg/controller/migration/convert/felix_vars.go
  pkg/controller/migration/convert/felix_vars_test.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/ippools.go
  pkg/controller/migration/convert/ippools_test.go
  pkg/controller/migration/convert/k8s.go
  pkg/controller/migration/convert/mtu.go
  pkg/controller/migration/convert/mtu_test.go
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
  pkg/controller/migration/convert/numorstring/numorstring.go
  pkg/controller/migration/convert/testutils_test.go
  pkg/controller/migration/convert/utils.go
  pkg/controller/migration/converter.go
  pkg/controller/migration/namespace_migration.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
  pkg/daemon/daemon.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#923 migration fixes for Azure
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
Labels: docs-pr-required, release-note-required

#924 remove unused provider from GetInstallation function
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
Labels: docs-pr-required, release-note-required

#925 Fix the service account assignments for kibana and elasticsearch
  pkg/render/logstorage.go
Labels: docs-not-required, release-note-required

#926 Update to Calico v3.16.2
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-required

#932 Fix error from operator-sdk upgrade with clusterconnection controller
  controllers/managementclusterconnection_controller.go
Labels: docs-not-required, kind/bug, release-note-not-required

#933 Fix error from operator-sdk upgrade with clusterconnection controller [Pick 932]
  controllers/managementclusterconnection_controller.go
Labels: docs-not-required, kind/bug, release-note-not-required

#930 Default CNI.Type to AmazonVPC if aws-node daemonset exists
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/defaults_test.go
Labels: docs-not-required, kind/enhancement, release-note-required

#934 Default CNI.Type if aws-node daemonset exists [Pick 930]
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/defaults_test.go
Labels: docs-pr-required, release-note-required

#927 Fix the service account assignments for kibana and elasticsearch
  pkg/render/logstorage.go
Labels: docs-pr-required, enterprise, kind/bug, release-note-required

#928 Fix the service account assignments for kibana and elasticsearch
  pkg/render/logstorage.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#929 Fix the service account assignments for kibana and elasticsearch
  pkg/render/logstorage.go
Labels: docs-pr-required, enterprise, kind/bug, release-note-required

#935 check for addon manager
  pkg/controller/migration/convert/addon_manager.go
  pkg/controller/migration/convert/addon_manager_test.go
  pkg/controller/migration/convert/handler.go
Labels: docs-pr-required, release-note-required

#937 Update to Calico v3.16.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#939 Fix building API reference doc
  api/doc.go
  api/v1/apiserver_types.go
  api/v1/compliance_types.go
  api/v1/doc.go
  api/v1/installation_types.go
  api/v1/logstorage_types.go
  go.mod
Labels: docs-not-required, release-note-not-required

#940 Fix building API reference doc [Pick 939-tpmi]
  api/doc.go
  api/v1/apiserver_types.go
  api/v1/compliance_types.go
  api/v1/doc.go
  api/v1/installation_types.go
  api/v1/logstorage_types.go
  go.mod
Labels: docs-not-required, release-note-not-required

#943 raise error if podSubnet not set
  pkg/controller/installation/pod_cidr_detection.go
  pkg/controller/installation/pod_cidr_detection_test.go
Labels: docs-pr-required, release-note-required

#931 Use -felix-ready for calico-node readiness on OpenShift
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, kind/bug, release-note-required

#948 Bump resources for ECK operator
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#949 Revert "calico-node clusterrole: add secrets permissions"
  pkg/render/node.go
Labels: docs-not-required, kind/bug, release-note-required

#950 1.10 cherry-picks
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-not-required

#951 Add NonZeroValueDefaulter for setting non zero defaults on types
  test/struct_defaulter.go
  test/struct_defaulter_test.go
Labels: docs-not-required, release-note-not-required

#946 Merge converted and configured Installation CR
  go.mod
  go.sum
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/merge.go
  pkg/controller/installation/merge_test.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/migration/convert/convert_test.go
  pkg/controller/migration/convert/ippools_test.go
  pkg/controller/migration/convert/network_test.go
  test/struct_defaulter.go
Labels: docs-pr-required, release-note-required

#952 Update to Calico v3.16.4
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-required

#938 Dont wipe status at start
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
Labels: docs-not-required, release-note-required

#953 Status delete bug fix and merge installation on migration [Pick 951 946 938]
  go.mod
  go.sum
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/merge.go
  pkg/controller/installation/merge_test.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/migration/convert/convert_test.go
  pkg/controller/migration/convert/ippools_test.go
  pkg/controller/migration/convert/network_test.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  test/struct_defaulter.go
  test/struct_defaulter_test.go
Labels: docs-pr-required, release-note-required

#941 Fine-grained control of log types for Syslog forwarding and alert forwarding
  api/v1/logcollector_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_logcollectors.yaml
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/render/compliance.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#954 Update deprecated centos image
  build/init/Dockerfile.amd64
  build/init/centos.repo
Labels: docs-not-required, release-note-required

#955 Pick fixes for release-v1.11
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-required

#947 Add Dex to the Operator for adding IDPs to Calico Enterprise
  api/v1/amazoncloudintegration_types.go
  api/v1/apiserver_types.go
  api/v1/authentication_types.go
  api/v1/compliance_types.go
  api/v1/intrusiondetection_types.go
  api/v1/logcollector_types.go
  api/v1/logstorage_types.go
  api/v1/manager_types.go
  api/v1/tigerastatus_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_authentications.yaml
  config/crd/bases/operator.tigera.io_managers.yaml
  controllers/authentication_controller.go
  controllers/controllers.go
  main.go
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/components/references.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/oidc/oidc.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/crypto_utils.go
  pkg/render/dex.go
  pkg/render/dex_config.go
  pkg/render/dex_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render.go
Labels: docs-pr-required, release-note-required

#956 [master] Bump resources for ECK operator
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#958 [release-v.12] Fix missing entry in enterprise.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#959 Add dex to enterprise_versions.yml and tpl.
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
Labels: docs-pr-required, release-note-required

#960 [release-v1.12] Add dex to enterprise_versions.yml and tpl.
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
Labels: docs-pr-required, release-note-required

#957 [v1.12] Bump resources for ECK operator
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#961 Add missing watch for installation in auth controller
  pkg/controller/authentication/authentication_controller.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#962 [release-v.12] Add missing installation watch for auth controller
  pkg/controller/authentication/authentication_controller.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#964 sort bird mounts alphabetically to prevent reconcile loop
  pkg/render/node.go
Labels: docs-not-required, kind/bug, release-note-required

#965 sort bird mounts alphabetically to prevent reconcile loop
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#968 Add label to curator pod
  pkg/render/logstorage.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#969 [cherry-pick] Add label to curator pod
  pkg/render/logstorage.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#966 [master] Dex PR follow-up
  api/v1/manager_types.go
  config/crd/bases/operator.tigera.io_managers.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/render/dex.go
  pkg/render/dex_config.go
  pkg/render/dex_test.go
  pkg/render/render.go
Labels: docs-pr-required, release-note-required

#971 [release-v1.12] Dex follow-up
  api/v1/manager_types.go
  config/crd/bases/operator.tigera.io_managers.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/render/dex.go
  pkg/render/dex_config.go
  pkg/render/dex_test.go
  pkg/render/render.go
Labels: docs-not-required, enterprise, release-note-not-required

#973 Add label to curator pod
  pkg/render/logstorage.go
Labels: delete-branch, docs-not-required, enterprise, kind/bug, merge-when-ready, release-note-not-required

#974 Add label to curator pod
  pkg/render/logstorage.go
Labels: delete-branch, docs-not-required, enterprise, kind/bug, merge-when-ready, release-note-not-required

#972 [master] Create dex namespace and avoid mutual controller dependency
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/installation/core_controller.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-not-required, release-note-not-required

#978 Automated cherry pick of #972: Address deadlock possibility for Authentication status
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/installation/core_controller.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-not-required, release-note-not-required
