Repository tigera/operator, pull requests merged in 2021-04, with the labels that each got.

#1249 Update versions of Calico and Enterprise
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: delete-branch, docs-pr-required, enterprise, merge-when-ready, release-note-required

#1250 Update component versions for Enterprise v3.6.0
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: docs-not-required, enterprise, release-note-not-required

#1252 Don't enable process info by default
  pkg/render/node.go
  pkg/render/node_test.go
Labels: delete-branch, docs-not-required, enterprise, kind/bug, merge-when-ready, release-note-not-required

#1254 Add liveness probe for kube-controllers
  pkg/render/kube-controllers.go
Labels: docs-not-required, release-note-not-required

#1258 use apiregistration/v1
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-not-required, release-note-not-required

#1251 Cert management for Elasticsearch
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/certs.go
  pkg/render/csr.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1253 Use certificate/v1 instead when kubernetes version is 1.19 onward
  main.go
  pkg/common/kubernetes_version.go
  pkg/common/kubernetes_version_test.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/options/options.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#1261 Merge tag v1.16.1 to clouddev branch
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  go.sum
  hack/gen-versions/enterprise.go.tpl
  hack/maybe-build-release.sh
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/render/fluentd.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1263 Revert "Merge pull request #1261 from tmjd/merge-1p16p1-clouddev"
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  go.sum
  hack/gen-versions/enterprise.go.tpl
  hack/maybe-build-release.sh
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/render/fluentd.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1257 FELIX_BPFEXTTOSERVICECONNMARK should default to 0x80 in EKS
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1266 FELIX_BPFEXTTOSERVICECONNMARK should default to 0x80 in EKS when AWS CNI is used
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-required

#1267 Update operator for Calico release v3.16.10
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1268 Update to Calico v3.15.5
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1271 Add init container to mount BPF filesystem.
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-not-required

#1273 [v1.17] Add init container to mount BPF filesystem.
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, release-note-not-required

#1269 update to apiregistration/v1
  pkg/controller/installation/core_controller.go
Labels: docs-pr-required, release-note-required

#1255 Added a watch for the kubernetes_services_endpoint configmap.
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/utils.go
  pkg/render/node.go
Labels: docs-pr-required, kind/enhancement, release-note-required

#1275 Cherry-pick configmap changes to v1.17
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/utils.go
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#1272 Support BGP layout ConfigMap for BGP multi-rack setups
  pkg/controller/installation/core_controller.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, enterprise, kind/enhancement, release-note-required

#1262 Refactor groups claim and make it cooperate w/ dex
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1276 Update to use Calico v3.17.4
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1265 Mount cert and add permissions to IDS controller to access managed cluster
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, enterprise, kind/enhancement, merge-when-ready, release-note-required

#1274 Install elasticsearch with basic license by default
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-not-required, enterprise, merge-when-ready, release-note-required

#1278 Add reading ConfigMap for extra Kibana config
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#1277 Update to Calico v3.18.2
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1281 Update for Calico v3.19.0
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1260 Add certificate management for compliance, dex, manager
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/utils.go
  pkg/render/apiserver.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/crypto_utils.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/dex_test.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required
