Repository tigera/operator, pull requests merged in 2021-09, with the labels that each got.

#1474 Add support for DeepPacketInspection
  api/v1/intrusiondetection_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_intrusiondetections.yaml
  config/enterprise_versions.yml
  deploy/crds/enterprise/02-crd-deeppacketinspection.yaml
  go.sum
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_suite_test.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#1482 Add note for odd secret creation
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required

#1501 Update kube-cntrl v3.9.1-1 and mgr v3.9.1-2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#1502 Migrate cidr= autodetection method properly
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
Labels: docs-pr-required, release-note-required

#1508 Enhance rights for an user to access the packetcapture UI
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1507 Fix that control-plane tolerations were not applied to Typha pods
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1509 Set ElasticSearch access variable to tigera-dpi
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#1514 [EV-1099] Upgrade fixes v1 to elastic prometheus crds
  deploy/crds/elastic/agent-crd.yaml
  deploy/crds/elastic/apmserver-crd.yaml
  deploy/crds/elastic/beat-crd.yaml
  deploy/crds/elastic/elasticmapsservers.yaml
  deploy/crds/elastic/elasticsearch-crd.yaml
  deploy/crds/elastic/enterprisesearch-crd.yaml
  deploy/crds/elastic/kibana-crd.yaml
  deploy/crds/prometheus/01-crd-alertmanager.yaml
  deploy/crds/prometheus/01-crd-podmonitor.yaml
  deploy/crds/prometheus/01-crd-prometheus.yaml
  deploy/crds/prometheus/01-crd-prometheusrule.yaml
  deploy/crds/prometheus/01-crd-servicemonitor.yaml
  deploy/crds/prometheus/01-crd-thanosrulers.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1515 Update versions to v3.19.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1516 Create tigera-dpi namespace irrespective of DPI resource
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#1518 [cherry-pick v1.22] Create tigera-dpi namespace irrespective of DPI resource
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1519 Remove es-gateway readiness probe
  pkg/render/logstorage/esgateway/esgateway.go
Labels: release-note-not-required, docs-not-required

#1520 Make es admin username configurable for kube-controllers secret
  pkg/controller/logstorage/common/common.go
  pkg/controller/logstorage/esgateway.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
Labels: docs-pr-required, release-note-required

#1522 Update versions to v3.20.1
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#1524 Reconcile performance hotspots secrets
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#1525 [EV-1143] Cherry pick release v1.22 1524
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#1523 Add resource quota to components
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/common/resourcequota/resourcequota.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1526 Automated cherry pick of #1523: Add resource quota to components
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/common/resourcequota/resourcequota.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1527 Pin versions
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1530 Automated cherry pick of #1528: Update IsAPIServerReady for variants
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#1533 Merge updates from v1.21.2
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1535 Update versions for v1.22
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: release-note-not-required, docs-not-required

#1536 Allow ARCHES to be overwritten
  Makefile
Labels: kind/enhancement, release-note-not-required, docs-not-required

#1538 Add init container that logs SELinux context
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: kind/bug, enterprise, docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1540 Automated cherry pick of #1538: Add init container that logs SELinux context
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1541 Automated cherry pick of #1538: Add init container that logs SELinux context
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1542 allow overriding manager image in cloud
  pkg/components/references.go
Labels: docs-pr-required, release-note-required

#1504 Support control plane replicas in Installation
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/merge.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/podaffinity/pod_anti_affinity.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/guardian.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1543 Add UISettingsGroup and UISettings to accessible CRD set
  deploy/crds/enterprise/02-crd-uisettings.yaml
  deploy/crds/enterprise/02-crd-uisettingsgroup.yaml
  pkg/render/apiserver.go
Labels: release-note-required, docs-not-required

#1539 [v1.22] Pick of Fix broken release script #1537
  hack/maybe-build-release.sh
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch
