Repository tigera/operator, pull requests merged in 2021-07, with the labels that each got.

#1300 Remove eks-log-forwarder deployment for Windows
  pkg/render/fluentd.go
Labels: docs-not-required, release-note-not-required

#1371 [release-v1.19] Remove eks-log-forwarder deployment for Windows (#1300)
  pkg/render/fluentd.go
Labels: docs-not-required, release-note-not-required

#1372 Bump to pre-release v3.7.1-0 intrusion detection controller
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-not-required, release-note-not-required

#1373 [hold merge] Prep for v3.8.0 release
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: docs-pr-required, hold merge, release-note-required

#1374 Enhance Monitor render unit tests
  pkg/render/monitor_test.go
Labels: docs-pr-required, release-note-required

#1370 Add default route to kibana
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#1375 Adding status RBAC for globalthreatfeeds for apiserver
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#1376 Automated cherry pick of #1375: Adding status RBAC for globalthreatfeeds for apiserver
  pkg/render/apiserver.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1368 release-1.16 Pick require affinity for typha
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  go.mod
  go.sum
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/migration/convert/core.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1369 release-1.18 Pick require affinity for typha
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  go.mod
  go.sum
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/migration/convert/core.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1378 Update EE versions for 1.19.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1381 bump manager for cloud-dev
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-not-required, release-note-not-required

#1384 [v1.18] Update go.sum
  go.sum
Labels: docs-pr-required, release-note-required

#1383 [v1.16] Update go.sum
  go.sum
Labels: docs-pr-required, release-note-required

#1341 Implement Operator logic to install ES Gateway
  config/enterprise_versions.yml
  go.mod
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/common/elasticsearch/decorator_test.go
  pkg/render/common/elasticsearch/service.go
  pkg/render/common/elasticsearch/tls.go
  pkg/render/common/kibana/service.go
  pkg/render/compliance_test.go
  pkg/render/fixtures_test.go
  pkg/render/fluentd_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_suite_test.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1386 [v3.5] Update components for EE v3.5.4
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1388 Add permissions to DeepPacketInspection resource
  pkg/render/apiserver.go
  pkg/render/typha.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1387 Add placeholder images for Calico v3.20
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1367 Check nf_conntrack for linux kernel 4.19+
  deploy/scripts/create_kind_cluster.sh
Labels: docs-pr-required, release-note-required

#1360 Add 1.17.5 bundle
  bundle/1.17.5/manifests/crd.projectcalico.org_bgpconfigurations.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_bgppeers.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_blockaffinities.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_clusterinformations.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_felixconfigurations.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_globalnetworkpolicies.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_globalnetworksets.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_hostendpoints.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_ipamblocks.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_ipamconfigs.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_ipamhandles.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_ippools.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_networkpolicies.yaml
  bundle/1.17.5/manifests/crd.projectcalico.org_networksets.yaml
  bundle/1.17.5/manifests/operator.clusterserviceversion.yaml
  bundle/1.17.5/manifests/operator.tigera.io_imagesets.yaml
  bundle/1.17.5/manifests/operator.tigera.io_installations.yaml
  bundle/1.17.5/manifests/operator.tigera.io_tigerastatuses.yaml
  bundle/1.17.5/metadata/annotations.yaml
  bundle/bundle-v1.17.5.Dockerfile
Labels: docs-not-required, release-note-not-required

#1395 cert management for es-gateway
  pkg/render/apiserver.go
  pkg/render/compliance.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-not-required, release-note-not-required

#1397 Fix Elasticsearch service name for Managed clusters
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1391 Enable FELIX_WIRGEUARDHOSTENCRYPTIONENABLED for AKS/EKS
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1400 Add RBAC for endpointslices
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1401 Automated cherry pick of #1400: Add RBAC for endpointslices
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1403 Automated cherry pick of #1402: IPAM GC RBAC update
  pkg/render/kube-controllers.go
Labels: docs-pr-required, release-note-required

#1402 IPAM GC RBAC update
  pkg/render/kube-controllers.go
Labels: docs-pr-required, release-note-required

#1396 Add label for ES gateway secrets
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/logstorage/esgateway/esgateway.go
Labels: docs-pr-required, release-note-required

#1406 Add copyright headers to esgateway package
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_suite_test.go
  pkg/render/logstorage/esgateway/esgateway_test.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1404 Extract packet capture as a service
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: docs-pr-required, release-note-required

#1408 Fix kube-proxy crashloopback for kind cluster
  deploy/scripts/create_kind_cluster.sh
Labels: docs-pr-required, release-note-required

#1407 Fix! Render secret in operator namespace
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
Labels: docs-pr-required, release-note-required

#1405 Move Prometheus ClusterRole to Role
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/monitor/prometheus.go
  pkg/render/monitor.go
  pkg/render/monitor_test.go
Labels: docs-pr-required, release-note-required

#1394 Operator changes for process path collection in flowLogs
  api/v1/logcollector_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_logcollectors.yaml
  pkg/controller/installation/core_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/utils/utils.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1410 Add timeouts to liveness/readiness probes for node/kube-controllers.
  pkg/render/kube-controllers.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1414 Fix typo in elasticsearch-metrics
  pkg/render/monitor.go
Labels: docs-pr-required, release-note-required

#1379 prometheus proxy managed under tigera operator
  config/crd/bases/operator.tigera.io_monitors.yaml
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/common/common.go
  pkg/components/enterprise.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/monitor.go
  pkg/render/monitor_test.go
  pkg/render/prometheus_api.go
  pkg/render/prometheus_api_test.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1399 Remove BYO Elasticsearch cert code cruft
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-not-required, release-note-not-required

#1413 Update ES Gateway render code to avoid re-rendering a customer provid…
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
Labels: docs-pr-required, release-note-required

#1417 Update for v3.20.0
  config/calico_versions.yml
  config/crd/bases/operator.tigera.io_monitors.yaml
  deploy/scripts/create_kind_cluster.sh
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1418 Bump es-proxy to v3.8.2-1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required
