Repository tigera/operator, pull requests merged in 2021-12, with the labels that each got.

#1659 Ensure typha and node secrets provided by the user do not have ownerreferences added
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-pr-required, release-note-required

#1673 [v1.23] windows: don't upgrade from Calico to Calico
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
Labels: docs-pr-required, release-note-required

#1674 [v1.24] windows: don't upgrade from Calico to Calico
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
Labels: docs-pr-required, release-note-required

#1672 windows: don't upgrade from Calico to Calico
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
Labels: release-note-required, docs-not-required

#1676 Use passthrough for tls secret
  pkg/controller/monitor/monitor_controller.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1669 Update kindest/node version to v1.21
  Makefile
Labels: release-note-not-required, docs-not-required

#1656 Do not create ES generated secrets in the render
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/logstorage.go
  pkg/render/passthru.go
  pkg/render/render_test.go
Labels: release-note-not-required, docs-not-required

#1677 Replace secrets renderer with the passthrough renderer
  pkg/controller/logstorage/esgateway.go
  pkg/render/secrets.go
Labels: release-note-not-required, docs-not-required

#1654 Don't call Delete if the CR has already been deleted
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
Labels: release-note-not-required, docs-not-required

#1681 [release-v1.23] Update versions for Calico v3.21.2
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1682 Make sure registry field and documentation match
  api/v1/installation_types.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: release-note-required, docs-not-required

#1683 Update k8s dependencies to 0.21.7, update base build images, update c…
  Makefile
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  go.mod
  go.sum
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/migration/convert/felix_vars.go
  test/dependencies.go
Labels: docs-pr-required, release-note-required

#1675 [release-1.24] Automated cherry pick of #1633 origin release v1.24 1638400080
  Makefile
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/monitor/monitor_controller_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/monitor/prometheus_api.go
  pkg/render/monitor/prometheus_api_test.go
Labels: docs-pr-required, release-note-required

#1684 Upgrade prometheus operator to 0.52.1
  go.mod
  go.sum
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#1686 Upgrade ECK operator to 1.8.0
  go.mod
  go.sum
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#1687 Create Kibana and Elasticsearch secrest after elasticsearch namespace exists
  pkg/controller/logstorage/logstorage.go
Labels: kind/bug, docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1688 [release-v1.24] Auto pick #1683: Update k8s dependencies to 0.21.7, update base build images, #1684: Upgrade prometheus operator to 0.52.1 #1686: Upgrade ECK operator to 1.8.0
  Makefile
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  go.mod
  go.sum
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/migration/convert/felix_vars.go
  test/dependencies.go
Labels: docs-pr-required, release-note-required

#1689 Upgrade ECK image to 1.8.0
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1691 [release-v1.24] Auto pick #1689: Upgrade ECK image to 1.8.0
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1692 Prometheus-tls secret was created in wrong place
  pkg/controller/monitor/monitor_controller.go
Labels: docs-pr-required, release-note-required

#1695 Update versions for calient 3.11.1 and operator 1.24.1 release
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1696 Remove authenticationreviews
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: hold merge, docs-pr-required, release-note-required

#1697 Place back authorizationreviews
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1699 Update for monorepo
  Makefile
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
Labels: docs-pr-required, release-note-required

#1703 Update controller dependency graph to the latest
  controller-dependency-graph.svg
  generate-controller-dependency-graph.py
Labels: release-note-not-required, docs-not-required

#1707 Regenerate CRDs
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
Labels: release-note-not-required, docs-not-required

#1708 Automated cherry pick of #1698: Order the fields in dex env
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-pr-required, release-note-required

#1705 Rev to use latest go-lang and golang.org/x/net
  Makefile
  api/v1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
Labels: docs-pr-required, release-note-required

#1706 Update Elasticsearch and Kibana to v7.16.2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/manager.go
Labels: enterprise, docs-pr-required, release-note-required

#1700 Improve git performance
  Makefile
Labels: docs-pr-required, release-note-required

#1702 Always have tokenreviews permissions for compliance-server
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#1698 Order the fields in dex env
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: kind/bug, enterprise, docs-pr-required, release-note-required

#1712 Update Enterprise components to v3.10.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1711 Update elastic v7.16.2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1415 Add VPP support
  api/v1/installation_types.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/node.go
Labels: docs-pr-required, release-note-required
