Repository tigera/operator, pull requests merged in 2021-11, with the labels that each got.

#1457 Update operator image label values
  build/Dockerfile.amd64
Labels: release-note-not-required, docs-not-required

#1595 Prepare release branch for Enterprise v3.11
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1586 Enable multiarch manifest for quay
  Makefile
Labels: docs-pr-required, release-note-required

#1593 Add rights for SV to query k8s resources
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1596 Fix for quay multiarch manifest
  Makefile
Labels: docs-pr-required, release-note-required

#1597 [cherry-pick] Add rights for SV to query k8s resources (#1593)
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1599 [release-v1.24] Auto pick #1586: Enable multiarch manifest for quay #1596: Fix for quay multiarch manifest
  Makefile
Labels: docs-pr-required, release-note-required

#1602 disableBGPExport to pkg files
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
Labels: docs-pr-required, release-note-required

#1603 [release-v1.23] Auto pick #1586 #1587 #1590 #1592 #1596 #1602
  Makefile
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_packetcaptures.yaml
Labels: release-note-not-required, docs-not-required

#1604 [release-v1.24] Auto pick #1602: Add: disableBGPExport to pkg files
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready

#1506 Don't run so many Typha instances on small clusters
  pkg/common/autoscale.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
Labels: release-note-required, docs-not-required

#1606 Automated cherry pick of #1506: Don't run so many Typha instances on small clusters
  pkg/common/autoscale.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
Labels: docs-pr-required, release-note-required

#1610 Add rights for packet capture to update status
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: docs-pr-required, release-note-required

#1589 Ensure logstorage use patch for its controlling resource
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1611 Add rights for packet capture to update status (#1610)
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: docs-pr-required, release-note-required

#1613 Update versions for v3.21.0 release
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
Labels: docs-pr-required, release-note-required

#1605 Refactor apiserver and amazoncloudintegration render args into a struct
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: release-note-not-required, docs-not-required

#1615 Update version for Calico v3.17.6
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#1618 Do AWS SG setup before active operator check
  main.go
Labels: release-note-not-required, docs-not-required

#1617 Add watch permissions for licensekeys for kube-controllers.
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#1620 Fix cert-management for ECK and PCAP
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/packet_capture_api.go
Labels: docs-pr-required, release-note-required

#1619 Fix windows-upgrader image
  pkg/components/references.go
  pkg/render/render_test.go
Labels: kind/bug, release-note-required, docs-not-required

#1624 Automated cherry pick of #1620: Fix cert-management for ECK and PCAP
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/packet_capture_api.go
Labels: docs-pr-required, release-note-required

#1622 Do AWS SG setup before active operator check [pick#1618 r1.24]
  main.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#1616 Fix windows upgrader test
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/controller/status/mock.go
Labels: release-note-not-required, docs-not-required

#1630 [release-v1.24] Automated cherry pick of #1616: Fix windows upgrader test
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/controller/status/mock.go
Labels: release-note-not-required, docs-not-required

#1629 [release-v1.23] Automated cherry pick of #1616: Fix windows upgrader test
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/controller/status/mock.go
Labels: release-note-not-required, docs-not-required

#1631 fix fdescribe
  test/struct_defaulter_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1623 Do AWS SG setup before active operator check [pick1618 r1.23]
  main.go
Labels: release-note-not-required, docs-not-required

#1625 [release-v1.23] Automated cherry pick of #1619: Fix windows-upgrader image
  pkg/components/references.go
  pkg/render/render_test.go
Labels: kind/bug, release-note-required, docs-not-required

#1621 Automated cherry pick of #1506: Don't run so many Typha instances on small clusters
  pkg/common/autoscale.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
Labels: release-note-required, docs-not-required

#1626 [release-v1.24] Automated cherry pick of #1619: Fix windows-upgrader image
  pkg/components/references.go
  pkg/render/render_test.go
Labels: release-note-not-required, docs-not-required

#1634 Automated cherry pick of #1620: Fix cert-management for ECK and PCAP
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/packet_capture_api.go
Labels: docs-pr-required, release-note-required

#1635 Automated cherry pick of #1620: Fix cert-management for ECK and PCAP
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/packet_capture_api.go
Labels: docs-pr-required, release-note-required

#1627 [pick release-v1.22] Add watch permissions for licensekeys for kube-controllers
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#1628 [pick release-v1.24] Add watch permissions for licensekeys for kube-controllers
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#1639 Update CRDs: uisettings
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#1632 Refactor render args into a struct
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
  pkg/render/render_test.go
Labels: release-note-required, docs-not-required

#1641 Updates for Calico v3.18.6
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#1636 removing validation for LogIntervalSeconds
  api/v1/applicationlayer_types.go
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
Labels: docs-pr-required, release-note-required

#1642 [cherry-pick] removing validation for LogIntervalSeconds as it fails helm
  api/v1/applicationlayer_types.go
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
Labels: docs-pr-required, release-note-required

#1644 Update CRDs
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#1637 windows upgrader followup
  pkg/common/windows.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
Labels: docs-pr-required, release-note-required

#1647 [v1.24] Pick of windows upgrader followup (#1637)
  pkg/common/windows.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
Labels: docs-pr-required, release-note-required

#1646 [v1.23] Pick windows upgrader followup (#1637)
  pkg/common/windows.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
Labels: docs-pr-required, release-note-required

#1614 Add UISettings passthru
  go.mod
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1648 Rev CRD for UISettings
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
Labels: docs-pr-required, release-note-required

#1652 Prep Enterprise v3.11.0
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1643 Ensure manager-tls secret provided by the user do not have ownerreference added
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: release-note-not-required, docs-not-required

#1650 Reorder Prometheus role and rolebindings creation
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: release-note-not-required, docs-not-required

#1633 Add authn-proxy to prometheus as a side-car
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/monitor/monitor_controller_test.go
  pkg/render/guardian.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/monitor/prometheus_api.go
  pkg/render/monitor/prometheus_api_test.go
Labels: hold merge, docs-pr-required, release-note-required

#1663 Update to v3.21.1
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1651 Ensure kibana secrets provided by the user do not have ownerreferences added
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/common/common.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: release-note-required, docs-not-required

#1660 Ensure compliance secret provided by the user do not have ownerreferences added
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#1664 Add test for manager created secret
  pkg/controller/manager/manager_controller_test.go
Labels: release-note-not-required, docs-not-required

#1661 Ensure esgateway secret provided by the user do not have ownerreferences added
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#1665 Update calico version to v3.20.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#1666 Revert "Update calico version to v3.20.3"
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#1667 Update versions for Calico v3.20.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1670 Update crds
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#1658 Ensure apiserver and packetcapture secrets provided by the user do not have ownerreferences added
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required
