Repository tigera/operator, pull requests merged in 2021-01, with the labels that each got.

#1048 avoid virtual nodes in aks
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/core_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1051 Fix a permission error that occurs for elasticsearch on OCP 4.6
  pkg/render/logstorage.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1052 Fix a permission error that occurs for elasticsearch on OCP 4.6
  pkg/render/logstorage.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1053 Fix a permission error that occurs for elasticsearch on OCP 4.6
  pkg/render/logstorage.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1046 expose option to set typha affinity
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/merge.go
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/core_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1054 Update to Calico v3.16.6
  build/init/centos.repo
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1036 Disable Elasticsearch features based on license type
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  test/utils.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1059 Enable service info in flow logs by default
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1058 Use binary readiness probe for Elasticsearch instead of bash script
  pkg/render/logstorage.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1043 Nodeselectors tolerations
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/merge.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render_utils_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1060 Use requested scopes (if specified) in dex
  pkg/render/dex_config.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1038 Fix IPv6 pool natOutgoing not working
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1062 Add fluentd component for Windows
  pkg/components/enterprise.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/utils/component_test.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/elasticsearch_decorator.go
  pkg/render/elasticsearch_decorator_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection.go
  pkg/render/logstorage.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1063 Fix environment name
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, enterprise, merge-when-ready, release-note-not-required

#1066 Add fluentd-windows to enterprise versions
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1065 Respect scopes for Google, change default scopes, don't respect scope…
  pkg/render/dex_config.go
Labels: docs-pr-required, release-note-required

#1067 Bump Elasticsearch and Kibana to 7.10.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1068 Use default Windows flowlogs path
  pkg/render/fluentd.go
Labels: docs-pr-required, release-note-required

#1069 Fix fluentd volume hostpaths
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#1070 Intrusion detection can read/watch license
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#1057 Support Elasticsearch native users
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1072 Add Elasticsearch version and Kibana URL to Manager environment variables
  pkg/render/manager.go
Labels: docs-not-required, release-note-not-required

#1073 Update the OIDC users Elasticsearch secret name
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1074 bump to v3.4.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1075 Added a missing nil check
  pkg/render/dex_config.go
Labels: docs-pr-required, release-note-required

#1077 Pass elasticsearch license type to kube-controller
  pkg/controller/installation/core_controller.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1078 Update permission for kube-controller to access secret
  pkg/render/logstorage.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1037 Add certificate management for calico and minimal enterprise clusters.
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/calico_versions.yml
  config/crd/bases/operator.tigera.io_installations.yaml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/components.go
  main.go
  pkg/components/calico.go
  pkg/components/references.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/merge.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common.go
  pkg/render/csr.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1081 Copy ad-job elasticsearch user secret to intrusion detection namespace
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
Labels: delete-branch, docs-not-required, enterprise, kind/enhancement, merge-when-ready, release-note-not-required

#1083 Update permission for OIDC users Elasticsearch secrets
  pkg/render/logstorage.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1084 Use existing logger for Elasticsearch client
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#1080 recreate ES/kibana certs when DNS names change
  .gitignore
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/utils/secrets.go
  pkg/dns/dns.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render.go
  pkg/render/render_test.go
  test/utils.go
Labels: docs-not-required, enterprise, release-note-not-required

#1087 Update components for release branch v3.5
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1088 Apply imageset for windows fluentd
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
Labels: docs-pr-required, release-note-required

#1089 pick - Apply imageset for windows fluentd (#1088)
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
Labels: docs-pr-required, release-note-required

#1090 Switch PriorityClass from v1beta to v1
  pkg/controller/installation/core_controller_test.go
  pkg/render/priority_class.go
  pkg/render/render_test.go
Labels: docs-not-required, release-note-required

#1094 Switch PriorityClass from v1beta to v1
  pkg/controller/installation/core_controller_test.go
  pkg/render/priority_class.go
  pkg/render/render_test.go
Labels: docs-not-required, release-note-required

#1085 Updating controller-runtime
  Makefile
  go.mod
  go.sum
  main.go
  pkg/awssgsetup/aws_security_group_setup.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller_test.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/compliance/compliance_suite_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/core_suite_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_suite_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/configmap.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/priority_class.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/render_utils_test.go
  pkg/render/secrets.go
  pkg/render/typha.go
  test/mainline_test.go
  test/utils.go
Labels: docs-pr-required, release-note-required

#1095 Update controller-runtime and omit Licensekey resource from client cache
  Makefile
  go.mod
  go.sum
  main.go
  pkg/awssgsetup/aws_security_group_setup.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller_test.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/compliance/compliance_suite_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/core_suite_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_suite_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/configmap.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/priority_class.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/render_utils_test.go
  pkg/render/secrets.go
  pkg/render/typha.go
  test/mainline_test.go
  test/utils.go
Labels: docs-pr-required, release-note-required

#1097 Update controller-runtime and omit Licensekey resource from client cache
  Makefile
  go.mod
  go.sum
  main.go
  pkg/awssgsetup/aws_security_group_setup.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller_test.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/compliance/compliance_suite_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/core_suite_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_suite_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/configmap.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/priority_class.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/render_utils_test.go
  pkg/render/secrets.go
  pkg/render/typha.go
  test/mainline_test.go
  test/utils.go
Labels: docs-not-required, release-note-required

#1093 Create elasticsearch client on error
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#1098 [cherry-pick release-v1.14] create new es client on error
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1100 Disable healthcheck on es client
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1101 [cherry-pick release-v1.14]Disable Healthcheck in elasticsearch client
  pkg/controller/utils/elasticsearch.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1092 Recreate manager, compliance, and ES+KB pub certs if DNS names change
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
  pkg/controller/utils/secrets.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render_utils_test.go
  test/utils.go
Labels: docs-pr-required, hold merge, release-note-required

#1103 [release-v1.14] Recreate manager, compliance, and ES+KB pub certs if DNS names change…
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
  pkg/controller/utils/secrets.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render_utils_test.go
  test/utils.go
Labels: docs-not-required, enterprise, kind/bug, release-note-not-required

#1104 Custom certs only need to contain the expected svc DNS names as a subset
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
Labels: docs-not-required, enterprise, kind/bug, release-note-not-required

#1105 [master] Custom certs only need to contain the expected svc DNS names as a subset
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
Labels: docs-pr-required, enterprise, release-note-not-required

#1107 cherry-pick AKS improvements to release-v1.13
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/merge.go
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/core_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/common.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render_utils_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1109 fix maybe-build-release to work on earlier versions of git
  hack/maybe-build-release.sh
Labels: docs-not-required, release-note-not-required

#1108 Fix handling of custom manager TLS certs
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
Labels: docs-not-required, enterprise, kind/bug, release-note-not-required

#1110 Use 'skipInterface: ^br-.*' for Docker Enterprise ipv4 autodetection …
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-not-required, release-note-not-required

#1111 Use 'skipInterface: ^br-.*' for Docker Enterprise ipv4 autodetection …
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-not-required, release-note-not-required

#1112 [master] Fix handling of custom manager TLS certs (#1108)
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
Labels: docs-pr-required, release-note-required

#1116 Disable cert management for variant=calico for v1.14 only
  pkg/controller/installation/core_controller.go
Labels: docs-not-required, enterprise, release-note-not-required

#1121 Check that cert is managed by operator by checking cert issuer
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
  pkg/render/common.go
  test/utils.go
Labels: docs-pr-required, enterprise, kind/bug, release-note-required

#1122 [release-v1.14] Check that cert is managed by operator by checking cert issuer (#1121)
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
  pkg/render/common.go
  test/utils.go
Labels: docs-pr-required, enterprise, kind/bug, release-note-required

#1117 Need to ensure internal manager TLS secret is updated
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-not-required, enterprise, hold merge, kind/bug, release-note-not-required

#1119 Add annotation hashes for Manager / KB to roll pods over on kb cert c…
  pkg/render/logstorage.go
  pkg/render/manager.go
Labels: docs-not-required, enterprise, release-note-required

#1124 [release-v1.14] Add annotation hashes for Manager / KB to roll pods over on kb cert changes
  pkg/render/logstorage.go
  pkg/render/manager.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required
