Repository tigera/operator, pull requests merged in 2021-03, with the labels that each got.

#1199 [release-v1.15] Pick of Merge pull request #1189 from lmm/lmm-fluentd-probes
  pkg/render/fluentd.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1198 [release-v1.14] Pick Merge pull request #1189 from lmm/lmm-fluentd-probes
  pkg/render/fluentd.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1202 Fix assignment of compliance cert to unused variable
  pkg/controller/manager/manager_controller.go
Labels: docs-pr-required, release-note-required

#1201 Disable waiting on IDS job secret in managed clusters
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
Labels: docs-pr-required, release-note-required

#1197 Fix groups for google connector
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1190 Expose kube-controllers prometheus metrics
  pkg/apis/crd.projectcalico.org/v1/kubecontrollersconfiguration.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1200 Revert "Revert "[cherry-pick v1.14] remove OIDC elsticsearch user configmap and secret""
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-not-required, enterprise, release-note-not-required

#1194 Validate only operator-managed certificates
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/utils/certs.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1208 [release-v1.15] Validate only operator-managed certificates
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/utils/certs.go
Labels: docs-pr-required, enterprise, release-note-required

#1203 Automated cherry pick of #1197: Make kibana scopes static. Now requestedScopes meant for
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1205 [PICK] Create Elasticsearch client on the fly instead of caching it
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/logstorage/shim_test.go
  pkg/controller/utils/elasticsearch.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1212 Update operator for Calico release v3.16.9
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1210 Add alternate default values for Registry and ImagePath
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/components/images_test.go
  pkg/components/references.go
Labels: docs-pr-required, release-note-required

#1209 Fix validation with HostLocal IPAM
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/render/common/elasticsearch/service.go
  pkg/render/common/kibana/service.go
Labels: docs-not-required, release-note-required

#1204 Handle case where there are more Typhas than there are nodes
  go.mod
  go.sum
  pkg/common/autoscale.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/controller/migration/namespace_migration.go
  pkg/controller/utils/utils.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1216 Automated cherry pick of #1204: Fix Typha namespace migration for small clusters
  go.mod
  go.sum
  pkg/common/autoscale.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/controller/migration/namespace_migration.go
  pkg/controller/utils/utils.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1214 Add alternate default values for Registry and ImagePath [Pick #1210 to r1.5]
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/components/images_test.go
  pkg/components/references.go
Labels: docs-pr-required, release-note-required

#1215 Fix validation with HostLocal IPAM [pick#1209 r1.15]
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
Labels: docs-not-required, release-note-required

#1220 Add Typha prometheus config [pick#1217 r1.15]
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/merge.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1221 Add Typha prometheus config [pick#1217 r1.14]
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/merge.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, kind/enhancement, release-note-required

#1222 Fix autoscaler to look at labels, not annotations
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
Labels: docs-pr-required, release-note-required

#1224 Automated cherry pick of #1222: Fix autoscaler to look at labels, not annotations
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
Labels: docs-pr-required, release-note-required

#1223 Add Typha prometheus config [pick#1217 r1.13]
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/merge.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, kind/enhancement, release-note-required

#1225 Add Typha prometheus config [pick#1217 r1.12]
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/merge.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, kind/enhancement, release-note-required

#1226 Update calico version to v3.18.1
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1213 Update Enterprise component versions for v3.5.1 release
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1160 Add explanation of unauthenticated for tiered-policy-passthrough
  pkg/render/apiserver.go
Labels: docs-not-required, enterprise, release-note-not-required

#1129 cherry-pick: fix maybe-build-release to work on earlier versions of git
  hack/maybe-build-release.sh
Labels: docs-pr-required, release-note-required

#1227 inherit nodeReporterPort from felixconfig
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, enterprise, kind/enhancement, release-note-required

#1228 [cherry-pick v1.14] inherit nodeReporterPort from felixconfig
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1231 Fix previous commit that took out copying the admin secret to the operator namespace
  pkg/controller/logstorage/logstorage_controller.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1174 Adding checks for export-logs
  pkg/common/common.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#1230 Enable process info by default
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-not-required, enterprise, release-note-not-required

#1234 Check for nil replicas before accessing
  pkg/controller/migration/namespace_migration.go
Labels: docs-pr-required, release-note-required

#1235 Add pull secrets to Elasticsearch metrics deployment
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1237 Automated cherry pick of #1234: Check for nil replicas before accessing
  pkg/controller/migration/namespace_migration.go
Labels: docs-pr-required, release-note-required

#1232 Only enable groups params if secrets are present (google oidc)
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1236 Automated cherry pick of #1233: Only enable groups params if secrets are present (google
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1233 [v1.14] Only enable groups params if secrets are present (google oidc)
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-not-required, enterprise, kind/bug, release-note-required

#1240 Merge v1.14.2 to cloud-dev
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  config/enterprise_versions.yml
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/components/enterprise.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/merge.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/logstorage/shim_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/typha_test.go
  pkg/controller/utils/certs.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/utils.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/elasticsearch_decorator.go
  pkg/render/elasticsearch_decorator_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-not-required, release-note-not-required

#1238 Add OIDC Prompt type to Authentication spec
  api/v1/authentication_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_authentications.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-pr-required, release-note-required

#1219 Add a defaulting UT for zero-length IP pools
  pkg/controller/installation/defaults_test.go
Labels: docs-pr-required, release-note-required

#1229 auto generate product versions in release notes
  generate-release-notes.py
Labels: docs-not-required, release-note-not-required

#1243 Enabled tigera plugin for Kibana
  pkg/render/logstorage.go
Labels: docs-not-required, enterprise, kind/enhancement, release-note-not-required

#1244 Update components for Enterprise v3.5.2
  config/calico_versions.yml
  config/enterprise_versions.yml
Labels: docs-pr-required, enterprise, release-note-required

#1245 [v1.14] Add generated files for enterprise v3.5.2
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: delete-branch, docs-pr-required, enterprise, merge-when-ready, release-note-required

#1164 Add linuxDataplane option and defaulting/extra mounts for BPF
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/installation/merge.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, kind/bug, release-note-required

#1247 Add rights to access licenkeys for kube-controller
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#1248 Improve docs for LinuxDataplaneOption.
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
Labels: docs-pr-required, release-note-not-required
