Repository tigera/operator, pull requests merged in 2021-02, with the labels that each got.

#1115 Until the cert initialization is available for OS treat it as private
  config/calico_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/references.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-not-required, enterprise, release-note-not-required

#1126 cherry-pick: fix maybe-build-release to work on earlier versions of git
  hack/maybe-build-release.sh
Labels: docs-not-required, release-note-not-required

#1127 cherry-pick: fix maybe-build-release to work on earlier versions of git
  hack/maybe-build-release.sh
Labels: docs-not-required, release-note-not-required

#1128 cherry-pick: fix maybe-build-release to work on earlier versions of git
  hack/maybe-build-release.sh
Labels: docs-not-required, release-note-not-required

#1123 [master] Need to ensure internal manager TLS secret is updated (#1117)
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, enterprise, kind/bug, release-note-not-required

#1130 Update to Calico v3.15.4
  build/init/centos.repo
  config/calico_versions.yml
  go.mod
  go.sum
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1125 Add elasticsearch and kibana cert secrets annotations to kube-controllers
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/utils.go
  pkg/render/fixtures_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, enterprise, hold merge, kind/bug, release-note-required

#1131 [release-v1.14] Add elasticsearch and kibana cert secrets annotations to kube-control…
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/utils.go
  pkg/render/fixtures_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, enterprise, kind/bug, release-note-required

#1132 Updating Enterprise component versions for v3.5.0 release.
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: delete-branch, docs-not-required, enterprise, merge-when-ready, release-note-not-required

#1134 Update so CI will push images for cloud-* tags
  hack/maybe-build-release.sh
Labels: docs-pr-required, release-note-required

#1139 Fix version check during release
  Makefile
Labels: docs-not-required, release-note-not-required

#1138 Only merge metadata if it's not set on the desired state
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#1142 include OS node selector in PodTemplate resource types
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-not-required, kind/bug, release-note-required

#1144 Update to v3.16.7
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1136 Fix the version verification and add separate image dump argument
  main.go
Labels: docs-not-required, release-note-required

#1145 Update to v3.17.2
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1118 Move managing OIDC elsticsearch user configmap and secret from operator
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, enterprise, merge-when-ready, release-note-required

#1082 LDAP support for enterpise w/ Authentication CRD
  api/v1/authentication_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_authentications.yaml
  go.mod
  go.sum
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/authentication/authentication_suite_test.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-pr-required, release-note-required

#1146 Fix the version verification and add separate image dump argument (#1136)
  main.go
Labels: docs-not-required, release-note-required

#1137 Add eck-operator memory requests/limits to LogStorage CR.
  api/v1/installation_types.go
  api/v1/logstorage_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  config/crd/bases/operator.tigera.io_logstorages.yaml
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1152 Merge from release-v1.14
  main.go
Labels: docs-not-required, kind/bug, release-note-not-required

#1150 Add new common version file for projects that have release streams ou…
  Makefile
  RELEASING.md
  config/calico_versions.yml
  config/common_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/common.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/main.go
  main.go
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/references.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/utils/imageset/imageset.go
Labels: docs-not-required, kind/enhancement, release-note-required

#1154 Fix migration of interface autodetection method
  pkg/controller/migration/convert/network.go
Labels: docs-not-required, release-note-not-required

#1155 Add watch permissions to kube-controllers on IPAM blocks
  pkg/render/kube-controllers.go
Labels: docs-not-required, release-note-not-required

#1156 Automated cherry pick of #1155: Add watch permissions to kube-controllers on IPAM blocks
  pkg/render/kube-controllers.go
Labels: docs-not-required, release-note-not-required

#1153 Set LICENSE_EDITION to cloudEdition
  Makefile
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/manager.go
Labels: docs-not-required, enterprise, release-note-not-required

#1158 [PICK] Add new common version file for projects that have release streams outside of OS and EE
  Makefile
  RELEASING.md
  config/common_versions.yml
  hack/gen-versions/common.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  hack/gen-versions/main.go
  main.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/references.go
  pkg/controller/utils/imageset/imageset.go
Labels: docs-not-required, release-note-required

#1148 Install compliance and intrusion detection if features are active
  go.mod
  go.sum
  pkg/common/common.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/render/manager.go
Labels: docs-not-required, release-note-not-required

#1159 Remove certificate management restriction notice
  pkg/controller/installation/core_controller.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1147 [cherry-pick v1.14] remove OIDC elsticsearch user configmap and secret
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, enterprise, merge-when-ready, release-note-required

#1157 [cherry-pick v1.15] remove OIDC elsticsearch user configmap and secret
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, enterprise, merge-when-ready, release-note-required

#1143 include OS node selector in PodTemplate resource types
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-not-required, kind/bug, merge-when-ready, release-note-required

#1162 [release-v1.14] Pick changes from Use FQDN elasticsearch and kibana endpoints only for Windows
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/render/compliance_test.go
  pkg/render/elasticsearch_decorator.go
  pkg/render/elasticsearch_decorator_test.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection.go
  pkg/render/logstorage.go
  pkg/render/manager.go
Labels: docs-not-required, enterprise, kind/bug, merge-when-ready, release-note-required

#1161 [release-v1.15] Pick changes from Use FQDN elasticsearch and kibana endpoints only for Windows
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
  pkg/render/compliance_test.go
  pkg/render/elasticsearch_decorator.go
  pkg/render/elasticsearch_decorator_test.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection.go
  pkg/render/logstorage.go
  pkg/render/manager.go
Labels: delete-branch, docs-not-required, enterprise, kind/bug, merge-when-ready, release-note-required

#1163 Copy ComponentResources struct to eliminate CRD confusion
  api/v1/installation_types.go
  api/v1/logstorage_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  config/crd/bases/operator.tigera.io_logstorages.yaml
  pkg/controller/installation/validation_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1113 Adjust SignerName so it renders nicely for the Reference API doc
  api/v1/installation_types.go
Labels: docs-pr-required, release-note-required

#1165 Standardize intallation enum documentation format
  api/v1/installation_types.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1166 typha and namespace adjustments for AKS
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/compliance.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1167 cherry-pick aks fixes to v1.13
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/compliance.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-not-required, release-note-required

#1168 Update to v3.16.8
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1169 Adjust ImageSet API text
  api/v1/imageset_types.go
  config/crd/bases/operator.tigera.io_imagesets.yaml
  config/crd/bases/operator.tigera.io_installations.yaml
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1170 Update to use Calico v3.17.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required
