Repository tigera/operator, pull requests merged in 2021-10, with the labels that each got.

#1545 Get internal elasticsearch secret from proper namespace
  pkg/controller/logstorage/esgateway.go
Labels: kind/bug, enterprise, docs-pr-required, release-note-required

#1547 Copy pull secret to dpi namespace
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: release-note-not-required, docs-not-required

#1548 [release-v1.22] Auto pick #1545: Get internal elasticsearch secret from proper namespace
  pkg/controller/logstorage/esgateway.go
Labels: docs-pr-required, release-note-required

#1550 Remove "duplicate" image-all target (use images-all instead)
  Makefile
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#1549 [Cherr-pick v1.22] Copy pull secret to dpi namespace
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#1551 [release-v1.22] Auto pick #1536: Allow ARCHES to be overwritten #1550: Remove "duplicate" image-all target (use images-all instead)
  Makefile
Labels: release-note-not-required, docs-not-required

#1546 Update versions to v3.20.2
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1570 [release-v1.22] Auto pick #1567: Fix dereferencing nil error in es gateway
  pkg/controller/logstorage/esgateway.go
Labels: release-note-not-required, docs-not-required

#1575 Pickup latest libcalico-go CRD changes
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#1577 [release-v1.22] Auto pick #1576: Add Tolerations to Prometheus CRs
  pkg/render/monitor.go
Labels: docs-pr-required, release-note-required

#1505 changes for deploying l7 log collector daemon set using operator for calient
  api/v1/applicationlayer_types.go
  api/v1/zz_generated.deepcopy.go
  config/enterprise_versions.yml
  config/samples/operator_v1_applicationlayer.yaml
  controllers/applicationlayer_controller.go
  controllers/controllers.go
  go.mod
  go.sum
  hack/gen-versions/enterprise.go.tpl
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/components/enterprise.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
  pkg/controller/applicationlayer/applicationlayer_suit_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/utils/discovery.go
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_suit_test.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/applicationlayer/envoy-config.yaml
Labels: docs-pr-required, release-note-required
