Repository tigera/operator, pull requests merged in 2021-08, with the labels that each got.

#1412 Fix typo in ES service monitor name
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/render/monitor.go
  pkg/render/monitor_test.go
Labels: docs-not-required, release-note-required

#1421 Automated cherry pick of #1408: Fix kube-proxy crashloopback for kind cluster
  deploy/scripts/create_kind_cluster.sh
Labels: docs-pr-required, release-note-required

#1422 Automated cherry pick of #1408: Fix kube-proxy crashloopback for kind cluster
  deploy/scripts/create_kind_cluster.sh
Labels: docs-pr-required, merge-when-ready, release-note-required

#1420 Adds support for wireguard on EKS with AWS CNI
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1423 Automated cherry pick of #1408: Fix kube-proxy crashloopback for kind cluster
  deploy/scripts/create_kind_cluster.sh
Labels: docs-pr-required, merge-when-ready, release-note-required

#1416 add CNX_AUTH0_ORG_ID
  deploy/scripts/create_kind_cluster.sh
  hack/maybe-build-release.sh
  pkg/controller/manager/manager_controller.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1430 Upgrade Elastic and Kibana to 7.11
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1431 Revert "Upgrade Elastic and Kibana to 7.11"
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1433 Fix kube-proxy crashloopback for kind cluster
  deploy/scripts/create_kind_cluster.sh
Labels: docs-not-required, release-note-not-required

#1398 [v1.16] Backport oidc groups fixes
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1426 Update versions to v3.19.2
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#1440 Set CALICO_DISABLE_FILE_LOGGING to false as default
  pkg/controller/migration/convert/aws_cni_policy_only_test.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1443 bump manager to v3.7.1-4
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1442 Temporary pin Elastic/Kibana images to release-calient-v3.9
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#1436 Upgrade Elastic and Kibana to 7.11.2
  config/enterprise_versions.yml
  deploy/crds/elastic/apmserver-crd.yaml
  deploy/crds/elastic/beat-crd.yaml
  deploy/crds/elastic/elasticsearch-crd.yaml
  deploy/crds/elastic/enterprisesearch-crd.yaml
  deploy/crds/elastic/kibana-crd.yaml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1446 Merge pull request #1440 from song-jiang/song-felix-log
  pkg/controller/migration/convert/aws_cni_policy_only_test.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1449 Cherrypick ECK 1.3.2 and EK 7.11.2 upgrade to release 1.21
  config/enterprise_versions.yml
  deploy/crds/elastic/apmserver-crd.yaml
  deploy/crds/elastic/beat-crd.yaml
  deploy/crds/elastic/elasticsearch-crd.yaml
  deploy/crds/elastic/enterprisesearch-crd.yaml
  deploy/crds/elastic/kibana-crd.yaml
  pkg/components/enterprise.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#1432 Upstream changes to support Cloud Operator and the new CloudLogStorage controller.
  go.sum
  pkg/controller/logstorage/common/common.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/compliance.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/monitor.go
  pkg/render/namespaces.go
  pkg/render/packet_capture_api.go
Labels: release-note-not-required, docs-not-required

#1437 [v1.14] Update components for EE v3.5.5
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1393 [SAAS-1454] Ignore all kubectl generated annotation during the Installation conversion
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/core_test.go
Labels: docs-pr-required, release-note-required

#1452 Ignore calico/api when hacking the versions
  hack/gen-versions/components.go
Labels: release-note-not-required, docs-not-required

#1447 Default FelixConfiguration RouteTableRange when using AWS CNI
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1454 Default FelixConfiguration RouteTableRange when using AWS CNI [pick#1447 r1.21]
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1453 Fix! Enable authentication for packet capture
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/guardian.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: docs-pr-required, release-note-required

#1456 [cherry-pick]Fix! Enable authentication for packet capture (#1453)
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/guardian.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: docs-pr-required, release-note-required

#1455 add AUTH0_ORG_ID
  pkg/controller/manager/manager_controller.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1451 Revert "Merge pull request #1304 from tigera/song-v3.5.3"
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1458 Update components and registry for v3.9.0
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: docs-pr-required, release-note-required

#1448 Refactor Calico renderer
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/component.go
  pkg/render/apiserver.go
  pkg/render/common/test/testing.go
  pkg/render/compliance.go
  pkg/render/configmap.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/passthru.go
  pkg/render/priority_class.go
  pkg/render/render.go
  pkg/render/render_suite_test.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1460 Don't manage CNI if Calico isn't the CNI
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1462 Automated cherry pick of #1460: Don't manage CNI if Calico isn't the CNI
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1463 Automated cherry pick of #1460: Don't manage CNI if Calico isn't the CNI
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1461 update tigera/api package version
  go.mod
  go.sum
  pkg/apis/addtoscheme_operator_v1.go
  pkg/apis/projectcalico.org/v3/doc.go
  pkg/apis/projectcalico.org/v3/networkpolicy.go
  pkg/apis/projectcalico.org/v3/register.go
  pkg/apis/projectcalico.org/v3/zz_generated.deepcopy.go
Labels: docs-pr-required, release-note-required

#1464 arm64 support
  Makefile
  build/Dockerfile.arm64
Labels: docs-pr-required, release-note-required

#1411 Fix bailing on RedHat cert with cloud-dev
  hack/maybe-build-release.sh
Labels: release-note-not-required, docs-not-required

#1459 Only set kubernetes server/port env vars on host-networked pods.
  pkg/controller/k8sapi/k8s-endpoint.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/test/testing.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#1471 Default FelixConfiguration RouteTableRange when using AWS CNI
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1472 Default FelixConfiguration RouteTableRange when using AWS CNI
  deploy/scripts/create_kind_cluster.sh
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1473 Update priority class logic
  pkg/common/common.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/component.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/fixtures_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packetcapture_api_test.go
  pkg/render/passthru.go
  pkg/render/prometheus_api.go
  pkg/render/render.go
  pkg/render/render_test.go
  pkg/render/secrets.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1469 Update: including arm64 in the release process
  Makefile
Labels: docs-pr-required, release-note-required

#1354 Prevent release image from being overwritten
  Makefile
  hack/maybe-build-release.sh
Labels: release-note-not-required, docs-not-required

#1486 [v1.13] Update config to use Calico v3.17.5
  config/calico_versions.yml
  deploy/scripts/create_kind_cluster.sh
  pkg/components/calico.go
Labels: docs-pr-required, release-note-not-required

#1487 [v1.15] Update config to use Calico v3.18.5
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-not-required

#1488 Ocp updates
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1490 [cherry-pick] Ocp updates (#1488)
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: release-note-not-required, docs-not-required

#1492 [cherry-pick][v1.19] Ocp updates (#1488)
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1491 [cherry-pick] Ocp updates (#1488)
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1494 [cherry-pick][v1.17] Ocp updates (#1488)
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1495 [cherry-pick][v1.16] Ocp updates (#1488)
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1493 [cherry-pick][v1.18] Ocp updates (#1488)
  deploy/scripts/create_kind_cluster.sh
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: release-note-not-required, docs-not-required

#1489 bump manager to latest release
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1496 [cherry-pick][v1.14] Ocp updates (#1488)
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1498 [cherry-pick][v1.13] Ocp updates (#1488)
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1499 [cherr-pick][v1.15] Ocp updates (#1488)
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1497 [cherry-pick][v1.12] Ocp updates (#1488)
  deploy/scripts/create_kind_cluster.sh
  pkg/render/compliance.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required
