Repository tigera/operator, pull requests merged in 2021-05, with the labels that each got.

#1285 Update versions of Calico and Enterprise
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-not-required, release-note-not-required

#1287 Update for Calico v3.18.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1289 don't migrate if the daemonset and deployments are deleting
  pkg/controller/migration/namespace_migration.go
Labels: docs-not-required, release-note-required

#1290 Namespace migration: fix deletetion timestamp update
  pkg/controller/migration/namespace_migration.go
Labels: docs-not-required, kind/bug, release-note-not-required

#1291 Namespace migration to ignore deleting resources [pick 1289 1290 r1.18]
  pkg/controller/migration/namespace_migration.go
Labels: docs-not-required, kind/enhancement, release-note-required

#1297 Handle no resources to monitor in the status manager
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller_test.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/controller/utils/component.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1293 Allow Implicit OIDC flow
  api/v1/authentication_types.go
  config/crd/bases/operator.tigera.io_authentications.yaml
  go.mod
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/auth.go
  pkg/render/common/authentication/tigera/key_validator_config/key_validator_config.go
  pkg/render/common/authentication/tigera/key_validator_config/key_validator_config_options.go
  pkg/render/common/authentication/types.go
  pkg/render/common/configmap/configmaps.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/dex_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1296 Update Makefile to consistenly use variables for CI paths.
  Makefile
Labels: docs-pr-required, release-note-required

#1299 [PICK] Pick implicit flow commits
  api/v1/authentication_types.go
  config/crd/bases/operator.tigera.io_authentications.yaml
  go.mod
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller_test.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/controller/utils/auth.go
  pkg/controller/utils/component.go
  pkg/render/common/authentication/tigera/key_validator_config/key_validator_config.go
  pkg/render/common/authentication/tigera/key_validator_config/key_validator_config_options.go
  pkg/render/common/authentication/types.go
  pkg/render/common/configmap/configmaps.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/dex_test.go
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1302 Prep for enterprise release v3.7.0
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: docs-not-required, release-note-not-required

#1303 Update tigera-manager role to include felixconfiguration, heps, events and nodes for service graph processing
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1304 Enable file logging for node by default for Calient.
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1286 Allow users to select Typha affinity type
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  go.mod
  go.sum
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/migration/convert/core.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1307 Change TigeraNodeAffinity to NodeAffinity
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/controller/migration/convert/core.go
  pkg/render/typha_test.go
Labels: docs-not-required, release-note-not-required

#1309 Fix Affinty->Affinity typo
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/controller/migration/convert/core.go
  pkg/render/typha_test.go
Labels: docs-not-required, release-note-not-required

#1308 Allow required affinity for typha [Pick 1286 1307 1309 to r1.14]
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_installations.yaml
  go.mod
  go.sum
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/migration/convert/core.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, kind/enhancement, release-note-required

#1314 Merge pull request #1304 from tigera/song-v3.5.3
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1313 Merge pull request #1304 from tigera/song-v3.5.3
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1311 Merge pull request #1304 from tigera/song-v3.5.3
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1312 Merge pull request #1304 from tigera/song-v3.5.3
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1288 Changes to run API server for Calico
  config/calico_versions.yml
  go.mod
  go.sum
  hack/gen-versions/calico.go.tpl
  pkg/apis/addtoscheme_operator_v1.go
  pkg/apis/projectcalico.org/v3/doc.go
  pkg/apis/projectcalico.org/v3/networkpolicy.go
  pkg/apis/projectcalico.org/v3/register.go
  pkg/apis/projectcalico.org/v3/zz_generated.deepcopy.go
  pkg/components/calico.go
  pkg/components/references.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/component.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/merge.go
  pkg/controller/utils/merge_test.go
  pkg/controller/utils/utils.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/meta/meta.go
  pkg/render/common/test/testing.go
Labels: docs-pr-required, release-note-required

#1315 Update components for Enterprise 3.5.3 release
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: docs-not-required, hold merge, release-note-not-required

#1316 Update to v3.19.1
  config/calico_versions.yml
Labels: docs-pr-required, release-note-required

#1317 Fix calico/apiserver in gen-versions
  config/calico_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/components.go
  pkg/components/calico.go
Labels: docs-not-required, release-note-not-required

#1318 Fix bug setting PSP name
  pkg/render/apiserver.go
Labels: docs-not-required, release-note-not-required

#1322 updates for cloud-dev portal
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/references.go
  pkg/controller/manager/manager_controller.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-not-required, release-note-required

#1323 Update to Calico v3.18.4
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1326 gen-versions needed to be ran for 1.17.2/Calico v3.19.1 release
  pkg/components/calico.go
Labels: docs-not-required, release-note-required

#1327 Hopefully more consistent gen-versions check
  Makefile
  hack/gen-versions/validate.sh
Labels: docs-not-required, docs-pr-required, kind/bug, release-note-required

#1329 Fix binding of clusterrole to enterprise serviceaccount
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#1328 Support an image prefix
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  main.go
  pkg/components/images_test.go
  pkg/components/references.go
  pkg/controller/utils/merge.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/compliance.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1330 Automated cherry pick of #1328: Support an image prefix
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  main.go
  pkg/components/images_test.go
  pkg/components/references.go
  pkg/controller/installation/merge.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/compliance.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1325 extend timeout to avoid not ready containers
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1331 extend timeout to avoid not ready containers (pick #1325 r1.17)
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1332 Automated cherry pick of #1328: Support an image prefix
  api/v1/installation_types.go
  config/crd/bases/operator.tigera.io_installations.yaml
  main.go
  pkg/components/images_test.go
  pkg/components/references.go
  pkg/controller/installation/merge.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/compliance.go
  pkg/render/csr.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required
