Repository tigera/operator, pull requests merged in 2021-06, with the labels that each got.

#1335 Fix polling for isLicenseKeyReady
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required

#1320 Added node lifecycle and increased terminationGracePeriodSeconds
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1336 Allow calico-node to update packetcaptures
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#1338 use new portal url var
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1337 Always manage CNI config from calico/node
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1339 pin to v3.7 release image
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1340 Update manager to prod repo with v3.7.1-1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/references.go
  pkg/render/manager_test.go
Labels: docs-not-required, release-note-not-required

#1342 Cloud: Quadruple leader lease timings
  main.go
  pkg/ptr/conversion.go
Labels: docs-pr-required, release-note-required

#1345 Add comment for felix and CLUSTER_TYPE env var
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#1344 Change tag validation for new format cloud-<ent-version>-<release>
  hack/maybe-build-release.sh
Labels: docs-not-required, release-note-not-required

#1346 Strip creationTimestamp from generated CRDs
  Makefile
  config/crd/bases/operator.tigera.io_amazoncloudintegrations.yaml
  config/crd/bases/operator.tigera.io_apiservers.yaml
  config/crd/bases/operator.tigera.io_authentications.yaml
  config/crd/bases/operator.tigera.io_compliances.yaml
  config/crd/bases/operator.tigera.io_imagesets.yaml
  config/crd/bases/operator.tigera.io_installations.yaml
  config/crd/bases/operator.tigera.io_intrusiondetections.yaml
  config/crd/bases/operator.tigera.io_logcollectors.yaml
  config/crd/bases/operator.tigera.io_logstorages.yaml
  config/crd/bases/operator.tigera.io_managementclusterconnections.yaml
  config/crd/bases/operator.tigera.io_managementclusters.yaml
  config/crd/bases/operator.tigera.io_managers.yaml
  config/crd/bases/operator.tigera.io_tigerastatuses.yaml
Labels: docs-not-required, release-note-not-required

#1306 Operator managed Prometheus CR
  Makefile
  api/v1/monitor_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.tigera.io_monitors.yaml
  config/enterprise_versions.yml
  config/samples/operator_v1_monitor.yaml
  controllers/controllers.go
  controllers/monitor_controller.go
  deploy/crds/prometheus/01-crd-alertmanager.yaml
  deploy/crds/prometheus/01-crd-podmonitor.yaml
  deploy/crds/prometheus/01-crd-prometheus.yaml
  deploy/crds/prometheus/01-crd-prometheusrule.yaml
  deploy/crds/prometheus/01-crd-servicemonitor.yaml
  go.mod
  go.sum
  hack/gen-versions/enterprise.go.tpl
  pkg/apis/addtoscheme_operator_v1.go
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/components/references.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/monitor/monitor_controller_suite_test.go
  pkg/controller/monitor/monitor_controller_test.go
  pkg/controller/monitor/prometheus.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/utils.go
  pkg/render/manager.go
  pkg/render/monitor.go
  pkg/render/monitor_test.go
Labels: docs-pr-required, release-note-required

#1350 Automated cherry pick of #1337: Always manage CNI config from calico/node
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1351 Automated cherry pick of #1337: Always manage CNI config from calico/node
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1352 Pull prometheus + eck-operator images from tigera/ to match docs pulling from quay.io/tigera
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/components/images_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1355 Fix Monitor render namespace selectors
  pkg/render/monitor.go
Labels: docs-pr-required, release-note-required

#1298 Adjust fluentd probe timeouts
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-not-required, release-note-required

#1356 Add deletecollection permissions for deleting ES secrets
  pkg/render/kube-controllers.go
  pkg/render/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#1357 bump manager version for cloud
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1358 Make alertmanager name consistent with calico-private
  config/enterprise_versions.yml
  go.sum
  hack/gen-versions/enterprise.go.tpl
Labels: docs-pr-required, release-note-required

#1353 Adding container for packet capture api to tigera manager
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/auth.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1359 Add rights to access packetcaptures/files as tigera-network-admin and…
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1361 Addendum: Rename component to packetcapture-api
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#1362 Fix apiserver deployment on Mirantis
  pkg/render/apiserver.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#1365 Prep for enterprise release v3.8.0
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#1319 Add controller dependency graph
  README.md
  controller-dependency-graph.svg
  generate-controller-dependency-graph.py
Labels: docs-not-required, release-note-not-required
