Repository tigera/operator, pull requests merged in 2022-02, with the labels that each got.

#1753 Run gen-versions
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#1751 Fix packet capture RBAC for default users
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1754 Fix packet capture RBAC for default users
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1756 updating envoy config to have NodePort listener
  pkg/render/applicationlayer/envoy-config.yaml
Labels: docs-pr-required, release-note-required

#1752 Add default UISettingsGroups and UISettings for pre-defined roles
  go.mod
  go.sum
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettingsgroups.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#1762 Cherry pick: Add UISettings defaults for enterprise and corresponding RBAC config
  go.mod
  go.sum
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettingsgroups.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1763 Update to v3.20.4
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1764 Install UISettings and UISettingsGroup as part of manager after api server is installed
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1767 Update to v3.19.4
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1766 Install UISettings and UISettingsGroup as part of manager after api server is installed
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1765 Pin golang.org/x/text
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#1769 Don't set owner ref on UISettings
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
Labels: docs-pr-required, release-note-required

#1768 Do not set or change OwnerReference of UISettings
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#1771 Default tigera infrastructure UISettings layer definition to line up with UI expected data
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/manager.go
Labels: enterprise, docs-pr-required, release-note-required

#1770 Default tigera infrastructure UISettings layer definition to line up with UI expected data
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/manager.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#1773 [release-v1.25] Auto pick #1772: Add specific registry for key-cert-provisioner
  pkg/components/images.go
  pkg/components/images_test.go
  pkg/components/references.go
Labels: docs-pr-required, release-note-required

#1774 Default UISettings and UISettingsGroups need to be added to managed cluster
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#1761 [cherry-pick] updating envoy config to have nodeports listener
  pkg/render/applicationlayer/envoy-config.yaml
Labels: docs-pr-required, release-note-required

#1777 Default UISettings and UISettingsGroups need to be added to managed cluster
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1779 Remove cluster-wide UI Settings for v3.12
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: enterprise, docs-pr-required, release-note-required

#1760 [cherry-pick] updating envoy config to have nodeports listener
  pkg/render/applicationlayer/envoy-config.yaml
Labels: docs-pr-required, release-note-required

#1781 Nil de-reference when err is nil
  pkg/controller/authentication/authentication_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1783 Update Enterprise components to v3.10.2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: enterprise, docs-pr-required, release-note-required

#1785 Update components for Enterprise v3.12.0
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/monitor/monitor_test.go
Labels: enterprise, docs-pr-required, release-note-required

#1788 adding tesla non-cloud changes to keep consistency
  pkg/render/common/configmap/configmaps.go
  pkg/render/common/test/testing.go
Labels: docs-pr-required, release-note-required

#1782 Automated cherry pick of #1781: nil de-reference when err is nil
  pkg/controller/authentication/authentication_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1790 Add tests to check that the elasticsearch index suffix is properly set on components
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/calico/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/calico/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/calico/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networksets.yaml
  pkg/render/compliance_test.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/manager_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#1792 [release-v1.25] Auto pick #1788: adding tesla non-cloud changes to keep consistency #1790: Add tests to check that the elasticsearch index suffix is
  pkg/render/common/configmap/configmaps.go
  pkg/render/common/test/testing.go
  pkg/render/compliance_test.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1793 Misc typo fixes
  README.md
  api/v1/installation_types.go
  pkg/controller/migration/cni/cni.go
  pkg/controller/migration/convert/ippools_test.go
  pkg/controller/status/status.go
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-901-INITIALIZATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-921-PROTOCOL-ATTACK.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/modsecdefault.conf
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#1798 Update projectcalico.org CRDs
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-pr-required, release-note-required

#1795 [master] Remove <v1.25 pod monitor
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#1797 Automated cherry pick of #1795: Remove <v1.25 pod monitor
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required
