Repository tigera/operator, pull requests merged in 2022-01, with the labels that each got.

#1715 Fix CI: `make gen-versions` and committed
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1713 Add java opts back to the pod spec
  go.mod
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#1716 Automated cherry pick of #1713: Add java opts back to the pod spec
  go.mod
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: kind/bug, docs-pr-required, release-note-required

#1717 Update go-build version and run mod tidy
  Makefile
  api/v1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  go.mod
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
Labels: docs-pr-required, release-note-required

#1719 Don't append slash to UseDefault for Installation spec.Registry
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
Labels: release-note-required, docs-not-required

#1722 [v1.23] Merge pull request #1719 from lmm/lmm-registry-use-default
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#1721 [v1.24] Pick Merge pull request #1719 from lmm/lmm-registry-use-default
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#1727 Updates for Calico v3.21.3
  Makefile
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#1729 Add component for the eck controller version.
  config/enterprise_versions.yml
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/components/images_test.go
  pkg/components/references.go
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#1733 Automated cherry pick of #1729: Add component for the eck controller version.
  config/enterprise_versions.yml
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/components/images_test.go
  pkg/components/references.go
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#1736 Update Calico version to v3.21.4
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#1730 Add namespaces flag to eck to prevent interference
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: hold merge, docs-pr-required, release-note-required

#1731 add extra hostpath volume for benchmarker for GKE
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#1680 Merge labels on resources
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: release-note-required, docs-not-required

#1738 tigera-ui-user can view policies in all tiers
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1735 Add github CODEOWNERS
  .github/CODEOWNERS
Labels: release-note-not-required, docs-not-required

#1726 Dual-stack host-local support
  pkg/controller/installation/validation_test.go
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1741 Prep 3.11.2
  Makefile
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1740 tigera-ui-user can view policies in all tiers
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1743 Fix dual-stack host-local
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#1744 Fix that sync state could be blocked when the TigeraStatus CR doesn't exist
  pkg/controller/status/status.go
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
Labels: release-note-required, docs-not-required

#1690 Kubecontrollers should be able to get UISettingsGroup
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1747 Run make gen-versions to update CRD
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready

#1748 Automated cherry pick of #1747: Run make gen-versions to update CRD
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready

#1745 Fix manifest migration of IptablesBackend
  pkg/controller/migration/convert/felix_vars.go
Labels: release-note-required, docs-not-required

#1749 Update to Calico v3.22.0
  config/calico_versions.yml
  pkg/components/calico.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#1710 Improving teardown
  pkg/controller/installation/core_controller.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/render_test.go
  pkg/render/windows.go
  test/crd_management_test.go
  test/mainline_test.go
Labels: release-note-required, docs-not-required
