Repository tigera/operator, pull requests merged in 2022-12, with the labels that each got.

#2319 Use our own TyphaDeploymentStategy
  api/v1/typha_deployment_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/common/validation/overrides_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/common/components/components_test.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-not-required, merge-when-ready

#2316 Automated cherry pick of #2315: Node selectors for prometheus resources overridden fix
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2315 Automated cherry pick of #2309: Node selectors for prometheus resources overridden fix
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2314 Automated cherry pick of #2309: Node selectors for prometheus resources overridden fix
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2313 Automated cherry pick of #2309: Node selectors for prometheus resources overridden fix
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2321 upgrade kibana from 7.17.5 to 7.17.7
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2320 Revert "Revert "Update Elasticsearch version to v7.17.7""
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2279 [Release 25] Update base image (cherry-pick 2275)
  build/Dockerfile.amd64
  build/Dockerfile.arm64
Labels: docs-pr-required, release-note-required, merge-when-ready

#2326 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2325 fix(render/ids): correct claim name in deployment
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2327 [release-v1.28] Pick 2325
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2338 Make gen-files make validate-gen-versions, make gen-versions
  api/v1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_externalnetworks.yaml
Labels: docs-pr-required, release-note-required

#2337 Add calico-typha ClusterRole permissions for newly added bgpfilters a…
  api/v1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required, merge-when-ready, squash-commits

#2335 [RS-647] Adds access to applicationlayer resources
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#2339 Update numorstring
  Makefile
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/migration/convert/felix_vars.go
  pkg/controller/migration/convert/felix_vars_test.go
  pkg/controller/migration/convert/numorstring/numorstring.go
Labels: docs-pr-required, release-note-required

#2342 Update golang to 1.18.9
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2343 [Release 1.28] Update golang to 1.18.9 (cherry-pick 2342)
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2344 [Release 1.27] Update golang to 1.18.9 (cherry-pick 2342)
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2346 [Release 1.25] Update golang to 1.18.9 (cherry-pick 2342)
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2347 [Release-v1.27] Update dependencies
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready

#2351 Add permissions for bgpfilters and externalnetworks to the apiserver.
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#2353 Fix that operator could not remove a ClusterIP.
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: kind/bug, docs-pr-required, release-note-required

#2355 [v1.28] Fix that operator could not remove a ClusterIP.
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2354 [v1.27] Fix that operator could not remove a ClusterIP.
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2348 Update general dependencies
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2349 [Release 1.28] Update general dependencies (cherry-pick 2348)
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2352 Create node trustedbundle with root certificates.
  pkg/controller/installation/core_controller.go
Labels: docs-pr-required, release-note-required

#2356 Create node trustedbundle with root certificates. (#2352)
  pkg/controller/installation/core_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2360 Automated cherry pick of #2357: Support rolling updates during upgrades by preserving
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller.go
  pkg/tls/certificatemanagement/keypair.go
Labels: docs-pr-required, release-note-required

#2361 Automated cherry pick of #2360: Support rolling updates during upgrades by preserving
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller.go
  pkg/tls/certificatemanagement/keypair.go
Labels: docs-pr-required, release-note-required

#2357 Support rolling updates during upgrades by preserving legacy fields in tls secrets
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller.go
  pkg/tls/certificatemanagement/keypair.go
Labels: docs-pr-required, release-note-required

#2362 Update ES & KB for EE v3.14.4
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2363 Add private flexvol image
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2364 update tigera/api pin to latest v3.14
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch
