Repository tigera/operator, pull requests merged in 2022-04, with the labels that each got.

#1878 Add the internal-manager-tls pem to the trusted bundle for es-proxy
  pkg/controller/manager/manager_controller.go
Labels: docs-pr-required, release-note-required

#1879 Automated cherry pick of #1878: Add the internal-manager-tls pem to the trusted bundle for
  pkg/controller/manager/manager_controller.go
Labels: docs-pr-required, release-note-required

#1860 Support for migrating a BPF cluster to operator install
  pkg/controller/migration/convert/bpf.go
  pkg/controller/migration/convert/bpf_test.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/namespace_migration.go
Labels: docs-pr-required, release-note-required

#1883 Prep for v3.13.0
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#1882 Make password generation more secure.
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/render/crypto_utils.go
Labels: docs-pr-required, release-note-required

#1884 Fix tests
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1885 Automated cherry pick of #1882: Make password generation more secure.
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/render/crypto_utils.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1886 Update with latest CRDs
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
Labels: docs-pr-required, release-note-required

#1887 update tigera/api pin to latest (v3.12 branch)
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1890 update tigera/api pin to latest for v3.12 branch
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#1871 Change to populate HTTP details in all cases when rule is triggered
  git-hooks/files-to-skip
  pkg/render/applicationlayer/modsec-core-ruleset/crs-setup.conf
  pkg/render/applicationlayer/modsecurityrules.go
Labels: docs-pr-required, release-note-required

#1892 Add list/watch permissions for clusterinformations on calico-kube-controller
  pkg/render/kubecontrollers/kube-controllers.go
Labels: release-note-required, docs-not-required

#1895 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready

#1898 Set the images for v1.25.5 to include enterprise release v3.12.2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-pr-required, release-note-required

#1899 Update go-build
  Makefile
Labels: docs-pr-required, release-note-required

#1901 Update go-build
  Makefile
  api/v1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
Labels: docs-pr-required, release-note-required

#1903 Update key-cert-provisioner
  config/common_versions.yml
  pkg/components/common.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#1905 Disable WireguardHostToHost encryption for AKS/EKS with Calico CNI (v1.26 pick)
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1897 Increase Typha max fall behind window
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#1906 [release-v1.15] Auto pick #1897: Increase Typha max fall behind window
  pkg/render/typha.go
Labels: release-note-required, docs-not-required

#1907 [release-v1.16] Auto pick #1897: Increase Typha max fall behind window
  pkg/render/typha.go
Labels: release-note-required, docs-not-required

#1908 [release-v1.17] Auto pick #1897: Increase Typha max fall behind window
  pkg/render/typha.go
Labels: release-note-required, docs-not-required

#1909 [release-v1.18] Auto pick #1897: Increase Typha max fall behind window
  pkg/render/typha.go
Labels: release-note-required, docs-not-required

#1911 [release-v1.20] Auto pick #1897: Increase Typha max fall behind window
  pkg/render/typha.go
Labels: release-note-required, docs-not-required

#1893 Add run options to test code in real clusters
  README.md
Labels: docs-pr-required, release-note-required

#1912 Disable WireguardHostToHost encryption for AKS/EKS with Calico CNI (#…
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1914 Disable WireguardHostToHost for AKS/EKS with Calico CNI (#1905)
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1916 Disable WireguardHostToHost for AKS/EKS with Calico CNI (#1905)
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1915 Disable WireguardHostToHost for AKS/EKS with Calico CNI (#1905)
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1913 Disable WireguardHostToHost encryption for AKS/EKS with Calico CNI (#…
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1910 [release-v1.19] Auto pick #1897: Increase Typha max fall behind window
  pkg/render/typha.go
Labels: release-note-required, docs-not-required

#1917 Update to Calico v3.22.2
  config/calico_versions.yml
  pkg/components/calico.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-pr-required, release-note-required

#1900 Update go-build
  Makefile
Labels: docs-pr-required, release-note-required

#1919 Update to Calico v3.21.5
  config/calico_versions.yml
  pkg/components/calico.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#1920 Update to v3.20.5
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1921 Update containernetworking pin
  go.mod
  go.sum
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
Labels: release-note-not-required, docs-not-required

#1925 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#1926 Prep v3.13.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1918 [v1.26] Allow downgrading from v1.26+ to v1.25.x
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#1927 Ignore csi driver, not installed via operator
  hack/gen-versions/components.go
Labels: release-note-not-required, docs-not-required

#1928 A small typo makes the files harder to find
  RELEASING.md
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1929 hack: add calico/windows to ignored images for gen-versions
  hack/gen-versions/components.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#1822 Use certificatemanager for dex
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/auth.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/common/authentication/tigera/key_validator_config/key_validator_config.go
  pkg/render/common/authentication/tigera/key_validator_config/key_validator_config_options.go
  pkg/render/common/authentication/types.go
  pkg/render/compliance.go
  pkg/render/crypto_utils.go
  pkg/render/dex.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/dex_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: docs-pr-required, release-note-required
