Repository tigera/operator, pull requests merged in 2022-07, with the labels that each got.

#2060 Fix node ver
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2061 Set enterprise versions to v3.13.3
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
Labels: docs-pr-required, release-note-required

#2057 Refactor semaphore jobs
  .semaphore/clean_up.yml
  .semaphore/clear_cache.yml
  .semaphore/push_images.yml
  .semaphore/semaphore.yml
  Makefile
Labels: docs-pr-required, release-note-required

#2067 [cherry-pick][release-v1.27] pick #2065
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2059 Remove Components from list that are not for images
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/common.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  main.go
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/controller/utils/imageset/imageset.go
Labels: docs-pr-required, release-note-required

#2072 [release-v1.27] cherry-pick: Add /proc and /var/run/calico to mount-bpffs volumes
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2073 [release-v1.25] cherry-pick: Add /proc and /var/run/calico to mount-bpffs volumes
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2055 [Pick release-v1.27] Run as non-privilege and non-root user
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/aws-securitygroup-setup_test.go
  pkg/render/common/podsecuritycontext/pod_security_context.go
  pkg/render/common/securitycontext/security_context.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: hold merge, docs-pr-required, release-note-required

#2077 Update oss crds
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2076 Fix PodSecurityStandard for intrusion detection
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#2078 Fix instructions for running a local operator
  README.md
Labels: release-note-not-required, docs-not-required

#2075 Updating the usage comment for documenation
  api/v1/tigerastatus_types.go
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/calico/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/calico/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/calico/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networksets.yaml
Labels: docs-pr-required, release-note-required

#2083 Add new field DisableBGPExport to IPPools API
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/apis/crd.projectcalico.org/v1/ippool.go
  pkg/controller/migration/convert/ippools.go
  pkg/controller/migration/convert/ippools_test.go
  pkg/controller/migration/convert/network_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/enhancement, docs-pr-required, release-note-required

#2086 Updates for v3.23.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2088 Update to Calico v3.22.4
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#2030 [release v1.26] Cherry pick: Add mount-cgroup init container to node ds
  pkg/render/node.go
  pkg/render/node_test.go
Labels: hold merge, docs-pr-required, release-note-required

#2093 Update to Calico v3.21.6
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2085 update github.com/stretchr/testify from 1.7.0 to v1.8.0
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2058 fix(render/ids): set ad images for standalone and management clusters
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2063 Add support for component resource overrides
  Makefile
  api/v1/apiserver_types.go
  api/v1/calico_kubecontrollers_types.go
  api/v1/calico_node_types.go
  api/v1/common_types.go
  api/v1/installation_types.go
  api/v1/typha_deployment_types.go
  api/v1/windows_upgrade_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/common/components.go
  pkg/common/k8svalidation/helper/helper.go
  pkg/common/k8svalidation/v1helper/v1helper.go
  pkg/common/k8svalidation/v1validation.go
  pkg/common/k8svalidation/validation.go
  pkg/common/validation/apiserver/validation.go
  pkg/common/validation/calico-node/validation.go
  pkg/common/validation/calico-windows-upgrade/validation.go
  pkg/common/validation/kube-controllers/validation.go
  pkg/common/validation/overrides.go
  pkg/common/validation/overrides_test.go
  pkg/common/validation/typha/validation.go
  pkg/components/overrides.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/utils/component.go
  pkg/controller/utils/merge.go
  pkg/controller/utils/merge_test.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/components/components.go
  pkg/render/common/components/components_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
  pkg/tls/certificatemanagement/csr.go
Labels: docs-pr-required, release-note-required

#2090 allow-tigera reconciliation: follow-ups
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/clusterconnection/shim_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/logstorage/shim_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/monitor/monitor_controller_test.go
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/tiers/tiers_controller_test.go
  pkg/controller/utils/test_utils.go
  pkg/controller/utils/utils.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: release-note-not-required, docs-not-required

#2097 Update FelixConfig CRD
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2089 Bump dependencies
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2050 deploy Calico API Server with soft zone based anti-affinity by default
  pkg/render/common/podaffinity/pod_anti_affinity.go
Labels: docs-pr-required, release-note-required

#2099 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2100 Update RBAC for apiserver to allow ipamconfigs
  pkg/render/apiserver.go
  pkg/render/node.go
Labels: release-note-required, docs-not-required, merge-when-ready

#2105 CRD update
  pkg/crds/calico/crd.projectcalico.org_ipamconfigs.yaml
Labels: release-note-not-required, docs-not-required

#2098 Status: do not degrade if expected pods are available
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
Labels: docs-pr-required, release-note-required

#2091 Update master toleration to include control-plane
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/meta/meta.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required
