Repository tigera/operator, pull requests merged in 2022-10, with the labels that each got.

#2186 Modify L7 logging and WAF to use CSI volume instead of flexvolume volume
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
Labels: docs-pr-required, release-note-required

#2205 Update dex security context in deploy when PSS is restricted
  pkg/render/dex.go
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required

#2206 [release-v1.28] Update dex security context in deploy when PSS is restricted
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/render/dex.go
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required

#2209 Update to Calico v3.22.5
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2207 [release-v1.28] Support Prometheus metrics scraping from queryserver
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/testutils/expected_policies/apiserver.json
  pkg/render/testutils/expected_policies/apiserver_ocp.json
  pkg/render/testutils/expected_policies/prometheus.json
  pkg/render/testutils/expected_policies/prometheus_ocp.json
Labels: docs-pr-required, release-note-required

#2210 Update golang to 1.18.7
  Makefile
Labels: docs-pr-required, release-note-required

#2211 [Release 1.28] Cherry-pick 2210
  Makefile
Labels: docs-pr-required, release-note-required

#2212 [Release 1.27] Cherry-pick 2210
  Makefile
Labels: docs-pr-required, release-note-required

#2215 [Release 1.25] Cherry-pick 2210
  Makefile
Labels: docs-pr-required, release-note-required

#2217 [release-v1.28] Remove ADJ api pod when fips is enabled
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2204 Remove ADJ api pod when fips is enabled
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2220 Add PSP for Guardian for RKE2 CIS -Hardened clusters
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
Labels: docs-pr-required, release-note-required

#2221 [release-v1.28] Remove adj and es-job installer resources when FIPS mode is enabled
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2227 Updates for v3.24.2
  config/calico_versions.yml
  pkg/components/calico.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
Labels: release-note-not-required, docs-not-required

#2228 Update to Calico v3.23.4
  config/calico_versions.yml
  pkg/components/calico.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#2202 Propagate imagePullSecrets from Installation resource th...
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required

#2222 [release-v1.28] pick #2220
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2230 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2229 [release-v1.28] pick #2226
  pkg/controller/installation/core_controller.go
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2226 Render PSPs for CSI driver pods
  pkg/controller/installation/core_controller.go
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2231 Updates for v3.24.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2233 Update felixconfig CRD with egress gateway polling config
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#2208 Propagate imagePullSecrets from Installation resource through to CSI …
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, squash-commits

#2223 Cherry pick 2143 - update kibana Version - 7.16.2 to 7.17.5
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2235 Update CRDs to the latest
  pkg/crds/enterprise/crd.projectcalico.org_globalthreatfeeds.yaml
Labels: docs-pr-required, release-note-required

#2234 Bump elasticsearch version to v7.17.6
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2236 [release-v1.28] Bump elasticsearch version to v7.17.6
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2237 Update CRDs to the latest
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
Labels: docs-pr-required, release-note-required

#2243 prevent operator lockup when unused apiservices are down
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: release-note-required, docs-not-required

#2244 [Cherry-pick #2243 to v1.27] prevent operator lockup when unused apiservices are down
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required

#2245 [Cherry-pick #2243 to v1.28] prevent operator lockup when unused apiservices are down
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required

#2247 Allow IP forwarding during manifest-to-operator migration
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2248 Update tigera/api pin
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch
