Repository tigera/operator, pull requests merged in 2022-11, with the labels that each got.

#2232 Prepare v1.27.15
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2250 GlobalAlertTemplates for detectors: multivariable flow and dns tunnel
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2252 [release-v1.28] pick 2250
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2253 Updates for v3.24.4
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2246 Add support for topology spread constraints to core components
  Makefile
  api/v1/apiserver_types.go
  api/v1/calico_kubecontrollers_types.go
  api/v1/calico_node_types.go
  api/v1/typha_deployment_types.go
  api/v1/windows_upgrade_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/common/k8svalidation/validation.go
  pkg/common/validation/overrides.go
  pkg/common/validation/overrides_test.go
  pkg/common/validation/validation_suite_test.go
  pkg/components/overrides.go
  pkg/render/apiserver_test.go
  pkg/render/common/components/components.go
  pkg/render/node_test.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, squash-commits

#2256 Updates for v3.23.5
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2259 [release-v1.28] Pick #2258
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2258 fix(render/ids): remove privilege from
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2254 Cherry-picks from master to release-v1.28
  api/v1/apiserver_types.go
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/controller/migration/convert/mtu.go
  pkg/controller/migration/convert/mtu_test.go
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2262 Fix kibana certificate in esgateway trusted bundle EV-2686
  pkg/controller/logstorage/esgateway.go
Labels: docs-pr-required, release-note-required

#2257 [EV-2765] Add v1 namespaces get to tigera-manager-role ClusterRole
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2265 Update golang to 1.18.8
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2266 [Release 1.28] Cherry-pick 2265 (Update golang to 1.18.8)
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2268 [Release 1.26] Cherry-pick 2265 (update golang to 1.18.8)
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2267 [Release 1.27] Cherry-pick 2265 (update golang to 1.18.8)
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2269 [Release 1.25] Cherry-pick 2265 (update golang to 1.18.8)
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2264 Cherry pick 2257 into release v1.28
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2270 Updates for v3.24.5
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2240 Add syslog tls changes - EV-2481
  api/v1/logcollector_types.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager_test.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2241 Support k8s 1.25 for CE 3.15
  config/enterprise_versions.yml
  go.mod
  go.sum
  pkg/active/active_test.go
  pkg/apis/addtoscheme_operator_v1.go
  pkg/apis/apis.go
  pkg/components/enterprise.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/status/status.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_test.go
  pkg/render/apiserver_test.go
  pkg/render/compliance_test.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/node_test.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#2271 cherry-pick #2240 Add syslog tls changes - EV-2481
  api/v1/logcollector_types.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager_test.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2272 (Pick for release-v1.28) Support k8s 1.25 for CE 3.15
  config/enterprise_versions.yml
  go.mod
  go.sum
  pkg/active/active_test.go
  pkg/apis/addtoscheme_operator_v1.go
  pkg/apis/apis.go
  pkg/components/enterprise.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/status/status.go
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/controller/utils/utils_test.go
  pkg/render/apiserver_test.go
  pkg/render/compliance_test.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/node_test.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#2273 Update tigera-ca-bundle path to /etc/pki/tigera
  pkg/render/guardian.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager_test.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2274 cherry-pick #2273 Update tigera-ca-bundle path to /etc/pki/tigera
  pkg/render/guardian.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager_test.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2275 Update base to UBI 8.7
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required

#2276 [Release 28] Update base image (cherry-pick 2275)
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required

#2281 Remove unconditional ServiceAccountName on CSI daemonset
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, squash-commits

#2282 Remove unconditional ServiceAccountName on CSI daemonset
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2283 Update versions for CE v3.15
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2284 Update doc for syslog possible values (EV-2821,EV-2822)
  api/v1/logcollector_types.go
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
Labels: docs-pr-required, release-note-required

#2285 Cherry-pick #2284 Update doc for syslog possible values (EV-2821,EV-2822)
  api/v1/logcollector_types.go
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
Labels: docs-pr-required, release-note-required

#2286 Bump compliance benchmarker and reporter liveness period
  pkg/render/compliance.go
Labels: docs-pr-required, release-note-required

#2289 [release-v1.28] Bump compliance benchmarker and reporter liveness period
  pkg/render/compliance.go
Labels: docs-pr-required, release-note-required

#2290 Fix make manifests
  Makefile
  pkg/crds/operator/operator.tigera.io_amazoncloudintegrations.yaml
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2291 Update golang.org/x/text
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2292 [Release 1.28] Update golang.org/x/text [cherry-pick 2291]
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2299 Update pins for v3.15.0
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2302 Add prometheus annotations to kube-controllers metrics service
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2306 Update enterprise versions
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: docs-pr-required, release-note-required

#2294 IDS controller use root when syslog forwarding is enabled
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2298 [release-v1.28] IDS controller use root when syslog forwarding is enabled
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2305 Update Elasticsearch version to v7.17.7
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2307 [release-v1.28] Update Elasticsearch version to v7.17.7
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2300 fix(render/ids): render ad api with privilege user if persistent storage is used
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2293 Revert "[EV-2765] Add v1 namespaces get to tigera-manager-role Cluste…
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2311 [release-v1.28] pick 2300
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2309 Node selectors for prometheus resources overridden fix
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2308 add gen-files and fix
  .semaphore/semaphore.yml
  Makefile
Labels: docs-pr-required, release-note-required

#2312 Add functionality to include system root certs into the tigera-ca-bundle
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/render/compliance_test.go
  pkg/render/fluentd.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager_test.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2317 Automated cherry pick of #2312: Add functionality to include system root certs into the
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/render/compliance_test.go
  pkg/render/fluentd.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager_test.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2318 Revert "Update Elasticsearch version to v7.17.7"
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2277 [Release 27] Update base image (cherry-pick 2275)
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required

#2278 [Release 26] Update base image (cherry-pick 2275)
  build/Dockerfile.amd64
  build/Dockerfile.arm64
Labels: docs-pr-required, release-note-required
