Repository tigera/operator, pull requests merged in 2022-05, with the labels that each got.

#1933 Fix setting of Typha healthport
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: release-note-not-required, docs-not-required

#1924 Update IPv6 migration for VXLAN
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/node.go
Labels: release-note-required, docs-not-required

#1888 BGPConfiguration operator in tigera
  go.mod
  go.sum
  pkg/apis/crd.projectcalico.org/v1/bgpconfig.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/render/node.go
Labels: release-note-not-required, docs-not-required

#1934 Fix formatting and generated files
  pkg/apis/crd.projectcalico.org/v1/bgpconfig.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#1936 [release-v1.27] Auto pick #1934: Fix formatting and generated files
  pkg/apis/crd.projectcalico.org/v1/bgpconfig.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#1938 Update node version with patch fix
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1939 Set VXLAN encap for IPv6 pools
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#1940 Automated cherry pick of #1939: Set VXLAN encap for IPv6 pools
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1937 Add Typha preferred zone anti-affinity
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1941 bump go to 1.17.9
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#1946 Update to Calico v3.23.0
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
Labels: release-note-not-required, docs-not-required

#1947 Update CRDs to the latest
  pkg/crds/enterprise/crd.projectcalico.org_alertexceptions.yaml
  pkg/crds/operator/operator.tigera.io_amazoncloudintegrations.yaml
Labels: release-note-not-required, docs-not-required

#1952 Update CRDs
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
Labels: release-note-not-required, docs-not-required

#1951 Fix error check in status
  pkg/controller/status/status.go
Labels: docs-pr-required, release-note-required

#1953 Fix error check in status [pick 1951 r1.27]
  pkg/controller/status/status.go
Labels: docs-pr-required, release-note-required

#1931 Apply AD API deployment and serviceaccount assosication with ad detectors podtemplate
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1955 Fix felix healthport: set as env var
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-required, docs-not-required

#1956 [release-v1.27] Auto pick #1955: Fix felix healthport: set as env var
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-required, docs-not-required

#1958 Update packetcapture component name
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/apiserver/apiserver_controller_test.go
Labels: docs-pr-required, release-note-required

#1961 Update to Calico v3.23.1
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1963 Update to Calico v3.22.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#1960 Bump components for Enterprise v3.11.4
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#1943 Automated cherry pick of #1941: bump go to 1.17.9
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#1944 Automated cherry pick of #1941: bump go to 1.17.9
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#1962 Prepare for Enterprise v3.13.2
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-pr-required, release-note-required

#1964 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#1967 Update release-note generation for python3
  generate-release-notes.py
Labels: release-note-not-required, docs-not-required

#1965 Remove cluster-wide UI Settings for now
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: enterprise, release-note-not-required, docs-not-required

#1942 Automated cherry pick of #1941: bump go to 1.17.9
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1975 Bump versions to 3.14.0
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/common.go.tpl
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_alertexceptions.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/operator/operator.tigera.io_amazoncloudintegrations.yaml
Labels: docs-pr-required, release-note-required

#1974 Add new permissions required by CNI plugin
  pkg/render/node.go
Labels: release-note-required, docs-not-required

#1976 Add kibana_login permissions to network admin cluster role
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1979 [release-v1.26] Auto pick #1976: Add kibana_login permissions to network admin cluster role
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1980 [release-v1.25] Auto pick #1976: Add kibana_login permissions to network admin cluster role
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#1978 [release-v1.27] Auto pick #1976: Add kibana_login permissions to network admin cluster role
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1982 Update Calico Enterprise pre release versions
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required
