Repository tigera/operator, pull requests merged in 2022-06, with the labels that each got.

#1986 Automated cherry pick of #1984: Add missing r.status.OnCRNotFound()
  pkg/controller/applicationlayer/applicationlayer_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1988 Automated cherry pick of #1984: Add missing r.status.OnCRNotFound()
  pkg/controller/applicationlayer/applicationlayer_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1987 Automated cherry pick of #1984: Add missing r.status.OnCRNotFound()
  pkg/controller/applicationlayer/applicationlayer_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1991 [v1.24] Update tigera/api pin
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#1957 Add mount-cgroup init container to node ds
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#1983 adjust FlexVolumePath when RKE2 provider is set
  api/v1/installation_types.go
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: docs-pr-required, release-note-required

#1679 Component labeler
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/packet_capture_api.go
  pkg/render/typha.go
  pkg/render/windows.go
Labels: docs-pr-required, release-note-required

#1993 Update windows fluentd bash.exe path
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: hold merge, release-note-not-required, docs-not-required

#1994 Update dependencies
  go.mod
  go.sum
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2000 Rename windows-upgrade component
  config/enterprise_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/references.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/render/windows.go
Labels: release-note-not-required, docs-not-required

#1996 [v1.27] Pick Update windows fluentd bash.exe path
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: release-note-not-required, docs-not-required

#2001 [v1.27] Pick Rename windows-upgrade component (#2000)
  config/enterprise_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/references.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/render/windows.go
Labels: release-note-not-required, docs-not-required

#2005 Cherrypick v1.27 RKE2 FlexVlumePath Patch
  api/v1/installation_types.go
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: kind/bug, release-note-required, docs-not-required

#1787 Add more logging to the check resource registration loop
  pkg/controller/utils/utils.go
Labels: release-note-not-required, docs-not-required

#1999 [v1.24] Pick of Update windows fluentd bash.exe path
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: hold merge, release-note-not-required, docs-not-required

#1998 [v1.25] Pick of Update windows fluentd bash.exe path
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: hold merge, release-note-not-required, docs-not-required

#1997 [v1.26] Pick Update windows fluentd bash.exe path
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: hold merge, release-note-not-required, docs-not-required

#2009 check for max and min in MTU
  pkg/controller/installation/core_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2007 Merge DaemonSet and Deployment template metadata as well
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: kind/bug, release-note-required, docs-not-required

#2012 Automated cherry pick of #2007: Merge DaemonSet and Deployment template metadata as well
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#2013 Automated cherry pick of #2007: Merge DaemonSet and Deployment template metadata as well
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#2014 Automated cherry pick of #2007: Merge DaemonSet and Deployment template metadata as well
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#2008 Tolerate IP6_AUTODETECTION_METHOD none when IP6 is none
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
Labels: docs-pr-required, release-note-required

#2015 Fix waiting for informers to sync in Typha autoscaler
  pkg/controller/installation/typha_autoscaler.go
Labels: release-note-required, docs-not-required

#1832 Use certificatemanagement for Elastic secrets and certificates
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/common/common.go
  pkg/controller/logstorage/esgateway.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/utils/certs.go
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/rand.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/elasticsearch/decorator.go
  pkg/render/common/elasticsearch/tls.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/crypto_utils.go
  pkg/render/dex.go
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/node.go
  pkg/render/packet_capture_api.go
  pkg/render/render_test.go
  pkg/render/testutils/fixtures.go
  pkg/render/typha.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
  pkg/tls/certificatemanagement/keypair.go
  pkg/tls/certificatemanagement/tls.go
Labels: docs-pr-required, release-note-required

#2025 Update versions to 3.14.0-2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2022 Dns retention
  api/v1/logstorage_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2027 update pin
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2036 update versions for 3.14.0-3
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_alertexceptions.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/enterprise/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/enterprise/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_deeppacketinspections.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreports.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreporttypes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalthreatfeeds.yaml
  pkg/crds/enterprise/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_licensekeys.yaml
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_packetcaptures.yaml
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_tiers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettingsgroups.yaml
Labels: docs-pr-required, release-note-required

#2039 Include VPP in cluster type enumeration
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, squash-commits

#2010 Add CodeQL for operator
  .github/workflows/codeql-analysis.yml
Labels: release-note-not-required, docs-not-required

#2011 Cherry pick #1931 #1966 release v1.27
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2029 [release v1.25] Cherry pick: Add mount-cgroup init container to node ds
  pkg/render/node.go
  pkg/render/node_test.go
Labels: hold merge, docs-pr-required, release-note-required

#2044 Update tigera/api dependency
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2043 [cherry-pick][release-v1.27] Trim lib, lib64 to necessary imports
  build/Dockerfile.amd64
Labels: docs-pr-required, release-note-required

#2042 Trim lib, lib64 to necessary imports
  build/Dockerfile.amd64
Labels: docs-pr-required, release-note-required

#2035 Only install PodSecurityPolicies if the API is present
  main.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/options/options.go
  pkg/controller/utils/discovery.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/podsecuritypolicy/pod_secruity_policy.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
  test/mainline_test.go
Labels: release-note-required, docs-not-required

#2045 Fixing Comment for BGP DNS log
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#2046 Update to Calico v3.23.2
  config/calico_versions.yml
  pkg/components/calico.go
  pkg/render/node.go
Labels: release-note-not-required, docs-not-required

#2049 Prep for Enterprise v3.7.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2048 Support Power image
  Makefile
  build/Dockerfile.ppc64le
Labels: release-note-required, docs-not-required, merge-when-ready

#2028 [release v1.27] Cherry pick: Add mount-cgroup init container to node ds
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-required, docs-not-required

#2053 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready

#2041 [EV-1873] Add volume mount with the TLS key pair to queryserver conta…
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: enterprise, docs-pr-required, release-note-required

#1954 Issue1055 Status Condition for Installation's CR from Tigerastatus conditions
  api/v1/installation_types.go
  api/v1/tigerastatus_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/typha_autoscaler.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
Labels: docs-pr-required, release-note-required

#2054 Bump ee preview release versions to 3.14.0-4
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2037 Run as non-privilege and non-root user
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/aws-securitygroup-setup_test.go
  pkg/render/common/podsecuritycontext/pod_security_context.go
  pkg/render/common/securitycontext/security_context.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
Labels: docs-pr-required, release-note-required

#2056 Fix EE issue introduced by https://github.com/tigera/operator/pull/2028
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required
