Repository tigera/operator, pull requests merged in 2022-09, with the labels that each got.

#2145 Add BPFDisableLinuxConntrack to Calico Api
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2144 Allow IP forwarding during manifest-to-operator migration
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#2155 Backport 2151
  build/Dockerfile.amd64
  build/Dockerfile.arm64
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2156 Add BPFDisableLinuxConntrack to Calico Enterprise Api
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#2151 update UBI base image from 8.5 to 8.6
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required, merge-when-ready

#2152 Cherry pick 2151
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2153 Backport 2151
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2149 Automated cherry pick of #2146: Update GO_BUILD_VERSION
  Makefile
Labels: docs-pr-required, release-note-required

#2146 Update GO_BUILD_VERSION
  Makefile
  pkg/controller/migration/cni/cni.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2158 update dependencies
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2147 Automated cherry pick of #2146: Update GO_BUILD_VERSION
  Makefile
  pkg/controller/migration/cni/cni.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2148 Automated cherry pick of #2146: Update GO_BUILD_VERSION
  Makefile
  pkg/controller/migration/cni/cni.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2160 Update tigera/api pin
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2162 Let the pcap server trust dex by mounting the ca-bundle
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
Labels: docs-pr-required, release-note-required

#2163 v1.27 Let the pcap server trust dex by mounting the ca-bundle
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
Labels: docs-pr-required, release-note-required

#2164 Update CRDs to the latest
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2165 Set enterprise versions to v3.14.2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2168 Update crds
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2167 Update pins
  Makefile
  go.mod
  go.sum
  pkg/controller/migration/convert/addon_manager.go
  pkg/controller/migration/convert/addon_manager_test.go
  pkg/controller/migration/convert/aws_cni_policy_only_test.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/controller/migration/convert/components.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/migration/convert/convert_suite_test.go
  pkg/controller/migration/convert/errors.go
  pkg/controller/migration/convert/k8s.go
  pkg/controller/migration/convert/mtu_test.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/utils.go
  pkg/controller/monitor/prometheus.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#2171 Set versions for CE v3.15
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamconfigs.yaml
Labels: docs-pr-required, release-note-required

#2126 Support Prometheus metrics scraping from queryserver
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/testutils/expected_policies/apiserver.json
  pkg/render/testutils/expected_policies/apiserver_ocp.json
  pkg/render/testutils/expected_policies/prometheus.json
  pkg/render/testutils/expected_policies/prometheus_ocp.json
Labels: docs-pr-required, release-note-required

#2175 Automated cherry pick of #2135: Add delete permissions to the kubecontrollers (EE) for
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2176 Automated cherry pick of #2140: Add expiry to kb session
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2174 Automated cherry pick of #2138: Change audit api version to v1
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#2177 Automated cherry pick of #2142: Default LogCollector instance first-thing
  pkg/controller/logcollector/logcollector_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2178 Automated cherry pick of #2136: Fix misspelling of variant in imageset
  api/v1/imageset_types.go
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready

#2170 Update pins (#2167)
  Makefile
  go.mod
  go.sum
  pkg/controller/migration/convert/addon_manager.go
  pkg/controller/migration/convert/addon_manager_test.go
  pkg/controller/migration/convert/aws_cni_policy_only_test.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/controller/migration/convert/components.go
  pkg/controller/migration/convert/convert.go
  pkg/controller/migration/convert/convert_suite_test.go
  pkg/controller/migration/convert/errors.go
  pkg/controller/migration/convert/k8s.go
  pkg/controller/migration/convert/mtu_test.go
  pkg/controller/migration/convert/typha.go
  pkg/controller/migration/convert/utils.go
  pkg/controller/monitor/prometheus.go
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2182 Hide anomaly detection when FIPS is enabled
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2183 Automated cherry pick of #2182: Hide anomaly detection when FIPS is enabled
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2184 Fix apiserver name comment
  api/v1/apiserver_types.go
Labels: release-note-not-required, docs-not-required

#2181 Configure dnsTrustedServers correctly for RKE2
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/bug, enterprise, release-note-required, docs-not-required

#2087 Add IPv6 Wireguard and IPv6 VXLAN custom MTU support
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/controller/migration/convert/mtu.go
  pkg/controller/migration/convert/mtu_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/enhancement, release-note-not-required, docs-not-required

#2185 [v1.25.12] Update EE versions to v3.12.4
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/enterprise/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/enterprise/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_deeppacketinspections.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreports.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreporttypes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalthreatfeeds.yaml
  pkg/crds/enterprise/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_licensekeys.yaml
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_packetcaptures.yaml
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_tiers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettingsgroups.yaml
Labels: docs-pr-required, release-note-required

#2187 [release-v1.21] Auto pick #2015: Fix waiting for informers to sync in Typha autoscaler
  pkg/controller/installation/typha_autoscaler.go
Labels: kind/bug, release-note-required, docs-not-required

#2188 [release-v1.20] Auto pick #2015: Fix waiting for informers to sync in Typha autoscaler
  pkg/controller/installation/typha_autoscaler.go
Labels: kind/bug, release-note-required, docs-not-required

#2189 [release-v1.19] Auto pick #2015: Fix waiting for informers to sync in Typha autoscaler
  pkg/controller/installation/typha_autoscaler.go
Labels: kind/bug, release-note-required, docs-not-required

#2190 [release-v1.18] Auto pick #2015: Fix waiting for informers to sync in Typha autoscaler
  pkg/controller/installation/typha_autoscaler.go
Labels: kind/bug, release-note-required, docs-not-required

#2191 [release-v1.17] Auto pick #2015: Fix waiting for informers to sync in Typha autoscaler
  pkg/controller/installation/typha_autoscaler.go
Labels: kind/bug, release-note-required, docs-not-required

#2192 [release-v1.16] Auto pick #2015: Fix waiting for informers to sync in Typha autoscaler
  pkg/controller/installation/typha_autoscaler.go
Labels: kind/bug, release-note-required, docs-not-required

#2193 [release-v1.15] Auto pick #2015: Fix waiting for informers to sync in Typha autoscaler
  pkg/controller/installation/typha_autoscaler.go
Labels: kind/bug, release-note-required, docs-not-required

#2195 update ip_pools CRDs
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2194 fix(guardian): minimize PS for deployment
  pkg/render/guardian.go
  pkg/render/guardian_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2196 pick 2194 release-v1.28
  pkg/render/guardian.go
  pkg/render/guardian_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2197 Update aws sdk go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required
