Repository tigera/operator, pull requests merged in 2022-08, with the labels that each got.

#2084 Re-add static-checks target to CI
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#2108 Update to v3.20.6
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2110 Sync GlobalAlert Template list for AD to what is available in the AD pods themselves
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2112 Remove some entries from go.mod that aren't needed
  go.mod
  go.sum
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2080 signed voltron certs
  api/v1/managementcluster_types.go
  api/v1/managementclusterconnection_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2104 Sanitize reason messages until we have them all updated
  api/v1/tigerastatus_types.go
  pkg/common/windows.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
Labels: docs-pr-required, release-note-required

#2106 Add Fips mode installation flag
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
  pkg/controller/clusterconnection/shim_test.go
  pkg/controller/logstorage/esgateway.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/utils/merge.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#2114 Fix syslog forwarding volume
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2079 Log upstream service time in envoy access log
  pkg/render/applicationlayer/envoy-config.yaml.template
Labels: docs-pr-required, release-note-required

#2118 Update CSI node registrar image
  config/calico_versions.yml
  hack/gen-versions/components.go
  pkg/components/calico.go
  pkg/components/references.go
  pkg/controller/installation/core_controller_test.go
Labels: release-note-not-required, docs-not-required

#2119 Update CSI node registrar image
  config/calico_versions.yml
  hack/gen-versions/components.go
  pkg/components/calico.go
  pkg/components/references.go
  pkg/controller/installation/core_controller_test.go
Labels: release-note-not-required, docs-not-required

#2120 Fix missing mount for es-proxy w/ standalone
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2121 Fix syslog forwarding volume
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2122 Update to Calico v3.24.0
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#2115 FIPS changes for Elastic.
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/crypto_utils.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2125 Update CRDs
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamconfigs.yaml
Labels: docs-pr-required, release-note-required

#2127 Merge pull request #2094 from freecaykes/ad-api-persistent-volume
  api/v1/intrusiondetection_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2138 Change audit api version to v1
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#2136 Fix misspelling of variant in imageset
  api/v1/imageset_types.go
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2111 Support Compliance CR omission
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2139 Updates for v3.24.1
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required

#2135 Add delete permissions to the kubecontrollers (EE) for secrets, confi…
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#2134 Automated cherry pick of #2115: FIPS changes for Elastic.
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/crypto_utils.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2133 (Pick 3.15) Support Compliance CR omission
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2132 (Pick 3.14) Support Compliance CR omission
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2131 (Pick 3.13) Support Compliance CR omission
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2130 (Pick 3.12) Support Compliance CR omission
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2141 Update CRDs to the latest
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: docs-pr-required, release-note-required

#2140 Add expiry to kb session
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#2142 Default LogCollector instance first-thing
  pkg/controller/logcollector/logcollector_controller.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2124 Set the csi-node-driver DaemonSet PriorityClass to system-node-critical
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#2143 upgrade kibana from 7.16.2 to 7.17.5
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required
