Repository tigera/operator, pull requests merged in 2022-03, with the labels that each got.

#1800 Remove env that is no longer used
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#1806 Update projectcalico.org CRDs
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/enterprise/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/enterprise/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_deeppacketinspections.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreports.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreporttypes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalthreatfeeds.yaml
  pkg/crds/enterprise/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_licensekeys.yaml
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_packetcaptures.yaml
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_tiers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettingsgroups.yaml
Labels: docs-pr-required, release-note-required

#1801 Set Kibana public domain based on Authentication domain
  pkg/controller/logstorage/logstorage.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: release-note-required, docs-not-required

#1804 Setting MaxUnavailable to 1 when calculation against # of available calico node pods resolves to 0
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/migration/namespace_migration.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#1808 Set Kibana public domain based on Authentication domain [pick #1801 r1.25]
  pkg/controller/logstorage/logstorage.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: release-note-required, docs-not-required

#1805 Pick migration fixes to 1.25
  pkg/controller/migration/convert/felix_vars.go
  pkg/controller/migration/convert/felix_vars_test.go
Labels: release-note-required, docs-not-required

#1811 Update projectcalico CRDs
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
Labels: docs-pr-required, release-note-required

#1803 bundle: update operator bundle tooling and docs
  Makefile
  RELEASING.md
  hack/gen-bundle/update-bundle.sh
  hack/maybe-build-release.sh
Labels: release-note-not-required, docs-not-required

#1794 Move PodDisruptionBudget from apiVersion policy/v1beta1 to policy/v1
  pkg/apis/addtoscheme_operator_v1.go
  pkg/apis/apis.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1807 Pick #1804 to release-v1.25
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/migration/namespace_migration.go
Labels: docs-pr-required, release-note-required

#1812 Update to Calico v3.22.1
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-required, docs-not-required

#1815 Pick 1814 to releaase-v1.25
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/migration/namespace_migration.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#1810 windows: create upgrader resources only on AKS
  pkg/render/render_test.go
  pkg/render/windows.go
Labels: kind/bug, release-note-required, docs-not-required

#1819 make gen files and versions
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1814 cleanup comments
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/migration/namespace_migration.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#1817 [release-v1.23] Pick of #1810: windows: only render upgrader components on AKS
  pkg/render/render_test.go
  pkg/render/windows.go
Labels: release-note-required, docs-not-required

#1818 [release-v1.25] Pick of #1810: windows: only render upgrader components on AKS
  pkg/render/render_test.go
  pkg/render/windows.go
Labels: release-note-required, docs-not-required

#1821 [release-v1.24] Pick of #1810: windows: only render upgrader components on AKS
  pkg/render/render_test.go
  pkg/render/windows.go
Labels: release-note-required, docs-not-required

#1824 refactoring manager test case function
  pkg/render/manager_test.go
Labels: release-note-not-required, docs-not-required

#1825 refactoring manager test case function
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1827 Make gen-files to fix the build
  pkg/crds/enterprise/crd.projectcalico.org_alertexceptions.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1823 Prevent ginkgo fdescribe and missing license with git hooks
  Makefile
  git-hooks/files-to-skip
  git-hooks/pre-commit
  git-hooks/pre-commit-in-container
  install-git-hooks
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#1830 Remove a git-hooks check that is not applicable to the repo
  git-hooks/pre-commit-in-container
Labels: docs-pr-required, release-note-required

#1568 ADJob Podtemplates for tigera-intrusion-detecion with corresponding updated ClusterRoles
  config/calico_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1833 Bump Enterprise versions to v3.11.3
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1799 Add AlertException cluster roles for apiserver and manager users
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1600 Add GlobalAlertTemplates for ADJobs
  go.mod
  go.sum
  pkg/render/common/test/testing.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required

#1839 Make validate-gen-files
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#1841 [v1.26] Fix mcm where certificate is not accepted (cherry-pick)
  pkg/controller/certificatemanager/certificatemanager.go
Labels: docs-pr-required, release-note-required

#1838 Remove cluster-wide UI Settings for now
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1844 Update felixconfig CRD for DNSPolicyMode
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#1849 make validate-gen-versions
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-pr-required, release-note-required

#1848 [master] Add missing rbac for kube controllers
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#1836 Pin operator versions to 1.26
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/common.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/calico/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/calico/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/calico/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
Labels: docs-pr-required, release-note-required

#1837 Cherry pick #1600 to release-v1.26
  go.mod
  go.sum
  pkg/render/common/test/testing.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1847 [v1.26] Add missing rbac for kube controllers
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#1853 Move pullsecret creation right after the namespace is created
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#1854 Automated cherry pick of #1853: Move pullsecret creation right after the namespace is created
  pkg/render/intrusion_detection.go
Labels: kind/bug, enterprise, docs-pr-required, release-note-required, merge-when-ready

#1239 Update Felixconfig for updated failsafes
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
Labels: docs-pr-required, release-note-required

#1856 Update AD GlobalalertTemplate + add feature toggle flag for intrusion detection
  go.mod
  go.sum
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: enterprise, docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1862 Automated cherry pick of #1856: feat(render/ids): add missing ad globalalert templates
  go.mod
  go.sum
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: enterprise, docs-pr-required, release-note-required

#1864 Automated cherry pick of #1863: Bump go-build to 0.65.1
  Makefile
Labels: docs-pr-required, release-note-required

#1863 Bump go-build to 0.65.1
  Makefile
Labels: docs-pr-required, release-note-required

#1868 Updating ids forward cert path
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1866 Fix enabling/disabling compliance flag for Voltron
  pkg/controller/manager/manager_controller.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: kind/bug, enterprise, docs-pr-required, release-note-required, merge-when-ready

#1867 Automated cherry pick of #1866: Fix enabling/disabling compliance flag for Voltron
  pkg/controller/manager/manager_controller.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#1869 Cherrypick #1868 to release-v1.26
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1865 image name change: app-policy -> dikastes.
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1873 Improve error message and fix ns for manager-internal-tls
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1872 image name change: app-policy -> dikastes.
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#1874 Automated cherry pick of #1873: Improve error message and fix ns for manager-internal-tls
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1846 Respect felixconfig health port
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#1880 make validate-gen-versions
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#1881 make validate-gen-versions
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch
