Repository tigera/operator, pull requests merged in 2023-04, with the labels that each got.

#2392 [EV-2059] Add policy recommendation resources
  api/v1/policyrecommendation_types.go
  api/v1/zz_generated.deepcopy.go
  config/enterprise_versions.yml
  config/samples/operator_v1_policyrecommendation.yaml
  controllers/controllers.go
  controllers/policyrecommendation_controller.go
  hack/gen-versions/enterprise.go.tpl
  pkg/common/common.go
  pkg/components/enterprise.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_suite_test.go
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/testutils/expected_policies/policyrecommendation.json
  pkg/render/testutils/expected_policies/policyrecommendation_managed.json
  pkg/render/testutils/expected_policies/policyrecommendation_managed_ocp.json
  pkg/render/testutils/expected_policies/policyrecommendation_ocp.json
Labels: docs-pr-required, release-note-required

#2578 Update tigera/api pin
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2571 Updates for MCM with Linseed
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/render/guardian.go
  pkg/render/logstorage.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2576 Fix periodic reconcile logic
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required

#2579 Update for v3.16.1
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2581 [v1.28] Fix periodic reconcile logic
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required

#2582 Add patch permissions to tigera-network-admin for services
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2580 [v1.29] Fix periodic reconcile logic
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: hold merge, docs-pr-required, release-note-required

#2583 [EV-2059] Create default PolicyRecommendationScope resource
  go.mod
  go.sum
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/render/policyrecommendation.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2586 Upgrade golang to v1.20.3 and k8s deps to 1.26 release
  Makefile
  go.mod
  go.sum
  pkg/common/k8svalidation/validation.go
  pkg/controller/utils/component_test.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
Labels: docs-pr-required, release-note-required

#2593 Fix! Missing rbac for flowlogs and snapshots and benchmarks
  pkg/render/compliance.go
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#2594 Fix! Mount linseed tokens as secret instead of config maps
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
  pkg/render/compliance.go
Labels: docs-pr-required, release-note-required

#2595 [Cherry-pick] Fix volumes for compliance and rbac roles for intrusion detection
  pkg/render/compliance.go
Labels: docs-pr-required, release-note-required

#2596 Fix! Reporter is missing access to flows
  pkg/render/compliance.go
Labels: docs-pr-required, release-note-required

#2597 [cherry-pick] Compliance reporter needs access to flows
  pkg/render/compliance.go
Labels: docs-pr-required, release-note-required

#2588 Ensure precommit checks happen on PR code
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#2600 Add egress gateway policy to API server RBAC
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#2602 [Cherry-pick 1.30] Support Egress Gateway Policy resource - EE 3.17
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
  pkg/render/apiserver.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#2605 Fix! Linseed controller needs get and create for secrets
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2607 [cherry-pick] Fix! Linseed controller needs get and create for secrets
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2609 Cherry-pick iptables backend to 3.17
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#2608 Cherry-pick(iptables-backend) to 3.16
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required
