Repository tigera/operator, pull requests merged in 2023-09, with the labels that each got.

#2849 Fix incorrect defaultEnterpriseRegistry/TigeraRegistry
  hack/gen-versions/main.go
  pkg/components/images.go
Labels: release-note-required, docs-not-required

#2850 Add new-branch instructions to releasing doc
  RELEASING.md
Labels: release-note-not-required, docs-not-required

#2847 [cherry-pick] [v1.30] Add some common content-types expected in micro-service traffic (#2839)
  pkg/render/applicationlayer/modsec-core-ruleset/crs-setup.conf
  pkg/render/applicationlayer/modsecurityrules.go
Labels: docs-pr-required, release-note-required

#2853 [cherry-pick] Add some common content-types expected in micro-service traffic (#2839)
  pkg/render/applicationlayer/modsec-core-ruleset/crs-setup.conf
  pkg/render/applicationlayer/modsecurityrules.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2854 Update v3.25.2
  config/calico_versions.yml
  config/common_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
Labels: release-note-not-required, docs-not-required

#2856 Fix! LogStorage name for tigera-status cannot contain special characters
  pkg/controller/logstorage/elastic/elastic_controller.go
Labels: docs-pr-required, release-note-required

#2859 Use baseline PSS for tigera-kibana namespace
  pkg/controller/logstorage/secrets/secret_controller.go
Labels: docs-pr-required, release-note-required

#2846 Various multi-tenancy fixes and cleanups
  pkg/controller/logstorage/users/user_controller.go
Labels: docs-pr-required, release-note-required

#2860 Fix! Tenant CA secrets needs to be rendered
  pkg/render/certificatemanagement/certificatemanagement.go
Labels: docs-pr-required, release-note-required

#2861 [EV-3914] Set the controller manager cache RESTMapper back to the DynamicRESTMapper (default changed on k8s upgrade)
  go.mod
  go.sum
  main.go
  pkg/common/k8svalidation/validation.go
  pkg/controller/utils/component_test.go
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_securityeventwebhooks.yaml
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
Labels: docs-pr-required, release-note-required

#2864 Update versions for v1.28.14
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/main.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#2804 Multi-tenant Linseed changes
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/policyrecommendation_test.go
Labels: release-note-not-required, docs-not-required, squash-commits

#2866 Fix certificate management due to missing volumemount
  pkg/controller/logstorage/kubecontrollers/esgateway.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2873 Disable es-kube-controllers controller in multi-tenant mode
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  test/crd_management_test.go
  test/mainline_test.go
Labels: release-note-not-required, docs-not-required

#2870 update kb & elastic to 7.17.13
  Makefile
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2869 update kb & elastic to 7.17.13
  Makefile
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2867 update kb & elastic to 7.17.13
  Makefile
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2868 update kb and elastic to 7.17.13
  Makefile
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2875 Cluster name will be set by Voltron for a managed cluster
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#2877 [cherry-pick] [v1.30] Cluster name will be set by Voltron for a managed cluster (#2875)
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#2876 [cherry-pick] [v1.31] Cluster name will be set by Voltron for a managed cluster (#2875)
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#2732 Add support for Windows hostprocess containers
  api/v1/calico_node_windows_types.go
  api/v1/installation_types.go
  api/v1/windows_upgrade_types.go
  api/v1/zz_generated.deepcopy.go
  config/calico_versions.yml
  config/enterprise_versions.yml
  controllers/controllers.go
  controllers/windows_controller.go
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  pkg/common/common.go
  pkg/common/kubernetes_version.go
  pkg/common/validation/calico-node/validation.go
  pkg/common/validation/calico-windows-upgrade/validation.go
  pkg/common/windows.go
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/references.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/installation/typha_autoscaler_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/installation/windows/calico_windows_upgrader_test.go
  pkg/controller/installation/windows/windows_suite_test.go
  pkg/controller/installation/windows_controller.go
  pkg/controller/installation/windows_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/k8sapi/k8s-endpoint.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/controller/utils/merge.go
  pkg/controller/utils/merge_test.go
  pkg/controller/utils/utils_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/common/securitycontext/security_context.go
  pkg/render/node.go
  pkg/render/render_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
  test/utils.go
Labels: docs-pr-required, release-note-required

#2878 Remove duplicate code
  pkg/render/logstorage/linseed/linseed.go
Labels: docs-pr-required, release-note-required

#2879 Remove Windows images on EE
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/controller/installation/windows_controller_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: release-note-not-required, docs-not-required

#2880 Remove csr rbac creation from wrong controller; intrusiondetection_co…
  pkg/controller/logstorage/secrets/secret_controller.go
Labels: docs-pr-required, release-note-required

#2881 Remove csr rbac creation from wrong controller; intrusiondetection_co…
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required

#2884 Add RBAC for DPI when a management cluster is spin up
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#2890 [cherry-pick] [v1.30] Add RBAC for DPI when a management cluster is spin up (#2884)
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#2889 [cherry-pick] [v1.31] Add RBAC for DPI when a management cluster is spin up (#2884)
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#2887 Add IPAMConfig StrictAffinity validation to windows controller
  pkg/controller/installation/windows_controller.go
  pkg/controller/installation/windows_controller_test.go
Labels: release-note-not-required, docs-not-required

#2892 Updates for v1.29.7
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/main.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#2896 Update ManagedCluster CRD to sync with Calico Enterprise update
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2883 Add RBAC permissions so Linseed can operate on secrets and configmaps
  pkg/render/compliance.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/logstorage.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/logstorage_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, squash-commits

#2882 Add test to ensure LogStorage secrets controller takes no action on m…
  Makefile
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, squash-commits

#2895 update dns svc discovery for rke2
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#2898 update dns svc discovery for rke2 (#2895)
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#2897 update dns svc discovery for rke2 (#2895)
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#2899 Fix k8s service endpoint configmap validation in windows_controller
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/windows_controller.go
  pkg/controller/installation/windows_controller_test.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: release-note-not-required, docs-not-required

#2901 Update k8s.io/ to newer patch
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2903 Remove ResourceNames on tigera-linseed ClusterRole
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, squash-commits

#2905 Update versions for v1.30.6
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
Labels: release-note-not-required, docs-not-required

#2840 Use tenant ID as SAN for tunnel connection
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required
