Repository tigera/operator, pull requests merged in 2023-02, with the labels that each got.

#2438 Cherry-pick #2437 to v1.29
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: release-note-not-required, docs-not-required

#2442 Update CRDs to the latest
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2441 Enable communication between linseed and fluentd
  pkg/components/enterprise.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/render/fluentd.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/testutils/expected_policies/fluentd_unmanaged.json
  pkg/render/testutils/expected_policies/fluentd_unmanaged_ocp.json
  pkg/render/testutils/expected_policies/linseed.json
  pkg/render/testutils/expected_policies/linseed_ocp.json
Labels: docs-pr-required, release-note-required

#2433 Apply more restrictive SecurityContext to components
  Makefile
  build/Dockerfile
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/migration/convert/aws_cni_policy_only_test.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/aws-securitygroup-setup_test.go
  pkg/render/common/securitycontext/security_context.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
  pkg/tls/certificatemanagement/csr.go
Labels: docs-pr-required, release-note-required

#2414 Automated cherry pick of #2390: Add private flexvol image (#2363)
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2448 Automated cherry pick of #2446: Use the right registry for OSS cni-fips
  pkg/components/references.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2447 Automated cherry pick of #2446: Use the right registry for OSS cni-fips
  pkg/components/references.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2449 Update pins for tigera/api and k8s.io
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2451 Remove and replace deprecated ioutil
  hack/gen-versions/components.go
  pkg/common/operator_namespace.go
  pkg/common/operator_serviceaccount.go
  pkg/controller/installation/core_controller.go
  pkg/controller/utils/elasticsearch_test.go
  pkg/render/common/authentication/types.go
Labels: docs-pr-required, release-note-required

#2454 [release-v1.29] Update runAsUser for es-proxy and aws securitygroup
  pkg/render/aws-securitygroup-setup.go
  pkg/render/aws-securitygroup-setup_test.go
  pkg/render/intrusion_detection.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2455 [release-v1.29] Apply more restrictive SecurityContext to components
  Makefile
  build/Dockerfile
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/migration/convert/aws_cni_policy_only_test.go
  pkg/controller/migration/convert/calico_default_config_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/aws-securitygroup-setup_test.go
  pkg/render/common/securitycontext/security_context.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packetcapture_api_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
  pkg/tls/certificatemanagement/csr.go
Labels: docs-pr-required, release-note-required

#2457 [release-v1.29] Increase Elasticsearch readiness probe threshold and timeout
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#2459 Fix! Ensure es-proxy and linseed can communicate
  pkg/components/enterprise.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/testutils/expected_policies/elasticsearch.json
  pkg/render/testutils/expected_policies/elasticsearch_ocp.json
  pkg/render/testutils/expected_policies/manager.json
  pkg/render/testutils/expected_policies/manager_ocp.json
Labels: docs-pr-required, release-note-required

#2450 Omit updates for NetworkPolicy/Tier when Spec is identical
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2462 [1.28] Omit updates for NetworkPolicy/Tier when Spec is identical
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2463 [master] Omit updates for NetworkPolicy/Tier when Spec is identical
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#2456 Increase Elasticsearch readiness probe threshold and timeout
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#2458 [release-v1.28] Increase Elasticsearch readiness probe threshold and timeout
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#2467 Cherry-pick openshift scc changes to 1.29
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2472 [release-calient-v1.29] Don't render SecurityContext for Windows fluentd
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#2477 [release-v1.29] Add chown to the elastic init keystore container securitycontext
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2480 Prepare v3.16.0
  config/common_versions.yml
  config/enterprise_versions.yml
  go.mod
  go.sum
  hack/gen-versions/common.go.tpl
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
Labels: docs-pr-required, release-note-required

#2481 Make versions and files
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_externalnetworks.yaml
Labels: docs-pr-required, release-note-required

#2466 Fix SCC for Egw openshift
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#2476 Add chown to the elastic init keystore container securitycontext
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2471 Don't render SecurityContext for fluentd on Windows
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#2485 [RS-749] - Sets fluentd env vars for RS index replicas and shards.
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/fluentd.go
Labels: kind/bug, release-note-not-required, docs-not-required

#2493 Fix EGW icmp probes
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#2464 Upgrade Prometheus to v2.42.0
  Makefile
  config/enterprise_versions.yml
  deploy/crds/prometheus/01-crd-alertmanager.yaml
  deploy/crds/prometheus/01-crd-alertmanagerconfigs.yaml
  deploy/crds/prometheus/01-crd-alertmanagers.yaml
  deploy/crds/prometheus/01-crd-podmonitor.yaml
  deploy/crds/prometheus/01-crd-podmonitors.yaml
  deploy/crds/prometheus/01-crd-probe.yaml
  deploy/crds/prometheus/01-crd-probes.yaml
  deploy/crds/prometheus/01-crd-prometheus.yaml
  deploy/crds/prometheus/01-crd-prometheuses.yaml
  deploy/crds/prometheus/01-crd-prometheusrule.yaml
  deploy/crds/prometheus/01-crd-prometheusrules.yaml
  deploy/crds/prometheus/01-crd-servicemonitor.yaml
  deploy/crds/prometheus/01-crd-servicemonitors.yaml
  deploy/crds/prometheus/01-crd-thanosruler.yaml
  deploy/crds/prometheus/01-crd-thanosrulers.yaml
  go.mod
  go.sum
  pkg/components/enterprise.go
  pkg/controller/utils/component_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#2496 Fix EGW icmp probes (#2493)
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2498 mTLS between linseed and es-proxy
  pkg/components/enterprise.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/esgateway.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/linseed.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
Labels: docs-pr-required, release-note-required

#2506 Fix an unused variable passed to ES metrics
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/logstorage_controller.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2497 (PICK release v1.29) Application-Layer Policies via per-host/per-node envoy support
  api/v1/applicationlayer_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/applicationlayer/envoy-config.yaml.template
Labels: docs-pr-required, release-note-required

#2508 Update image for linseed component
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#2483 CSI driver should tolerate all like l7 and node
  pkg/render/csi.go
Labels: docs-pr-required, release-note-required

#2494 Automated cherry pick of #2479: Increase timeout to 20s
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#2495 Automated cherry pick of #2479: Increase timeout to 20s
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#2486 Mount SSL_CERT_FILE in system-wide trust store
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/logstorage/linseed.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2490 [release-v1.28] Mount legacy SSL_CERT_FILE in system-wide trust store
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2489 [release-v1.29] Mount legacy SSL_CERT_FILE in system-wide trust store
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required
