Repository tigera/operator, pull requests merged in 2023-08, with the labels that each got.

#2787 [release-v1.31] Add SecurityContext for Prometheus service container
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2788 [release-v1.30] Add SecurityContext for Prometheus service container
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2723 Multi-tenant changes for PolicyRecommendation
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/controller/tenancy/tenancy.go
  pkg/controller/tenancy/tenancy_test.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection_test.go
  pkg/render/manager_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required

#2790 Ensure logstorage controller is not blocked on certs that need to be updated by other controllers
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required

#2789 [release-v1.29] Add SecurityContext for Prometheus service container
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#2791 Automated cherry pick of #2790: Certs: Returning specific error type when key usage is
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2792 Merge master
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/common/secret/secrets.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/fluentd.go
  pkg/render/intrusion_detection.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/policyrecommendation.go
  pkg/tls/certkeyusage/certkeyusage.go
Labels: docs-pr-required, release-note-required

#2793 Automated cherry pick of #2790: Certs: Returning specific error type when key usage is
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2795 Remove duplicate Felix Health Port for Openshift
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2796 Automated cherry pick of #2795: Remove duplicate Felix Health Port for Openshift
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2799 Automated cherry pick of #2796: Remove duplicate Felix Health Port for Openshift
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2798 Automated cherry pick of #2796: Remove duplicate Felix Health Port for Openshift
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2800 Update versions for v3.17.1 release
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/common.go.tpl
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#2749 [cherry-pick] pull request #2741 from lwr20/lwr-op-bundle-upd
  hack/gen-bundle/get-manifests.sh
  hack/gen-bundle/update-bundle.sh
Labels: docs-pr-required, release-note-required

#2746 Increase probes timeout for calico components
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
Labels: docs-pr-required, release-note-required

#2801 [release-v1.31] Increase probes timeout for calico components
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2803 Merge master
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
Labels: docs-pr-required, release-note-required

#2806 Automated cherry pick of #2802: Create internal manager tls inside of manager_controller
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2808 Automated cherry pick of #2802: Create internal manager tls inside of manager_controller
  Makefile
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#2802 ev-4025 release-v1.30 Create internal manager tls inside of manager_controller and fix certificate management
  Makefile
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#2810 Internal-manager-tls should contain only K8S services
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/testutils/expected_policies/manager.json
  pkg/render/testutils/expected_policies/manager_ocp.json
Labels: docs-pr-required, release-note-required

#2811 Internal-manager-tls should contain only K8S services (#2810)
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/testutils/expected_policies/manager.json
  pkg/render/testutils/expected_policies/manager_ocp.json
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2809 Use default non-root SecurityContext for manager
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2812 [release-v1.31] Use default non-root SecurityContext for manager
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2813 [cherry-pick] Internal-manager-tls should contain only K8S services (#2810)
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/testutils/expected_policies/manager.json
  pkg/render/testutils/expected_policies/manager_ocp.json
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2814 [ci-1299][ev-4068] Fix watch that is monitoring the wrong namespace
  pkg/controller/installation/core_controller.go
Labels: docs-pr-required, release-note-required

#2815 Automated cherry pick of #2814: Fix watch that is monitoring the wrong namespace
  pkg/controller/installation/core_controller.go
Labels: docs-pr-required, release-note-required

#2818 fix policyrecommendationscopes failing dirty-check
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
Labels: docs-pr-required, release-note-required

#2816 go generate pkg/render/applicationlayer
  pkg/render/applicationlayer/modsecurityrules.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch, squash-commits

#2820 Merge master
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
  pkg/render/applicationlayer/modsecurityrules.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/render_test.go
  pkg/render/testutils/expected_policies/manager.json
  pkg/render/testutils/expected_policies/manager_ocp.json
Labels: docs-pr-required, release-note-required

#2821 update coreruleset to 3.3.5
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-901-INITIALIZATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9005-CPANEL-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-905-COMMON-EXCEPTIONS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-910-IP-REPUTATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-911-METHOD-ENFORCEMENT.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-912-DOS-PROTECTION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-913-SCANNER-DETECTION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-921-PROTOCOL-ATTACK.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-922-MULTIPART-ATTACK.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-949-BLOCKING-EVALUATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-950-DATA-LEAKAGES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-959-BLOCKING-EVALUATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-980-CORRELATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
  pkg/render/applicationlayer/modsec-core-ruleset/crs-setup.conf
  pkg/render/applicationlayer/modsec-core-ruleset/modsecdefault.conf
  pkg/render/applicationlayer/modsec-core-ruleset/unicode.mapping
  pkg/render/applicationlayer/modsecurityrules.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch, squash-commits

#2822 update coreruleset to 3.3.5 (#2821)
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-901-INITIALIZATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9005-CPANEL-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-905-COMMON-EXCEPTIONS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-910-IP-REPUTATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-911-METHOD-ENFORCEMENT.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-912-DOS-PROTECTION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-913-SCANNER-DETECTION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-921-PROTOCOL-ATTACK.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-922-MULTIPART-ATTACK.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-949-BLOCKING-EVALUATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-950-DATA-LEAKAGES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-959-BLOCKING-EVALUATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-980-CORRELATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
  pkg/render/applicationlayer/modsec-core-ruleset/crs-setup.conf
  pkg/render/applicationlayer/modsec-core-ruleset/modsecdefault.conf
  pkg/render/applicationlayer/modsec-core-ruleset/unicode.mapping
  pkg/render/applicationlayer/modsecurityrules.go
Labels: docs-pr-required, release-note-required

#2824 Fix for what looks like a copy-paste error
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2826 Automated cherry pick of #2824: Fix for what looks like a copy-paste error
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
Labels: docs-pr-required, release-note-required

#2825 Automated cherry pick of #2824: Fix for what looks like a copy-paste error
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2830 update CRD (felixConfiguration)
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2832 Update enterprise changes to CRDs
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2834 Merge master into feature-mt
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-901-INITIALIZATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9005-CPANEL-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-903.9006-XENFORO-EXCLUSION-RULES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-905-COMMON-EXCEPTIONS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-910-IP-REPUTATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-911-METHOD-ENFORCEMENT.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-912-DOS-PROTECTION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-913-SCANNER-DETECTION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-921-PROTOCOL-ATTACK.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-922-MULTIPART-ATTACK.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-934-APPLICATION-ATTACK-NODEJS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  pkg/render/applicationlayer/modsec-core-ruleset/REQUEST-949-BLOCKING-EVALUATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-950-DATA-LEAKAGES.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-959-BLOCKING-EVALUATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-980-CORRELATION.conf
  pkg/render/applicationlayer/modsec-core-ruleset/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example
  pkg/render/applicationlayer/modsec-core-ruleset/crs-setup.conf
  pkg/render/applicationlayer/modsec-core-ruleset/modsecdefault.conf
  pkg/render/applicationlayer/modsec-core-ruleset/unicode.mapping
  pkg/render/applicationlayer/modsecurityrules.go
Labels: docs-pr-required, release-note-required

#2836 Fix manager policy rule
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#2827 Increase timeout
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-not-required, docs-not-required

#2839 Add some common content-types expected in micro-service traffic
  pkg/render/applicationlayer/modsec-core-ruleset/crs-setup.conf
  pkg/render/applicationlayer/modsecurityrules.go
Labels: kind/enhancement, enterprise, docs-pr-required, release-note-required, merge-when-ready, delete-branch, squash-commits

#2842 Fix certificate management after multi-tenant changes
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/kubecontrollers/esgateway.go
  pkg/controller/logstorage/linseed/esmetrics.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/elasticsearch.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2845 Update versions for v3.18.0
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#2805 Internal-manager-tls should contain only K8S services
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/testutils/expected_policies/manager.json
  pkg/render/testutils/expected_policies/manager_ocp.json
Labels: docs-pr-required, release-note-required
