Repository tigera/operator, pull requests merged in 2023-11, with the labels that each got.

#2964 Update CRDs for OSS and enterprise
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2965 Update EE CRDs
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2967 Update versions for calient v3.15.5
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#2958 Automate updating operator version for release
  Makefile
  RELEASING.md
  hack/gen-versions/main.go
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch, squash-commits

#2894 Ability to configure per-tenant index names
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/controller/logstorage/linseed/linseed_controller_test.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2973 [release 1.30] Update x/net
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2972 [release 1.31] update x/net
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2971 [release 1.32] Update x/net
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2968 [release-v1.30][cherry-pick] Automate updating operator version for release
  Makefile
  RELEASING.md
  hack/gen-versions/main.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2969 [release-v1.31][cherry-pick] Automate updating operator version for release (#2958)
  Makefile
  RELEASING.md
  hack/gen-versions/main.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2975 Add tenant namespace check for multitenant
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#2978 Remove old controller ref for Voltron secret
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required

#2979 [release-v1.32] Auto pick #2978: Remove old controller ref for Voltron secret
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required

#2980 Cherry-pick #2975 Add tenant namespace check for multitenant
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#2974 [release 1.29] update x/net
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2982 [cherry-pick][1.32] Ability to configure per-tenant index names (#2894)
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/controller/logstorage/linseed/linseed_controller_test.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2983 Automatic version updates for v1.30.8 release
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
Labels: release-note-not-required, docs-not-required

#2984 Apiserver render, protect against uninitialized Installation resource
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2977 Fix csi daemonset validation
  pkg/common/validation/csi-node-driver/validation.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
Labels: docs-pr-required, release-note-required

#2985 Es-proxy reaches K8S api via Voltron
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2986 [cherry-pick][v1.32] Es-proxy reached K8S api via Voltron (#2985)
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2987 EV-4126 Add watch for tenant controller
  pkg/controller/secrets/tenant_controller.go
Labels: docs-pr-required, release-note-required

#2990 Use trusted bundle with root CAs for multi-tenant manager pods
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/secrets/secrets_suite_test.go
  pkg/controller/secrets/tenant_controller.go
  pkg/controller/secrets/tenant_controller_test.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2993 [release-v1.32] Auto pick #2990: Use trusted bundle with root CAs for multi-tenant manager
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/secrets/secrets_suite_test.go
  pkg/controller/secrets/tenant_controller.go
  pkg/controller/secrets/tenant_controller_test.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
Labels: docs-pr-required, release-note-required

#2976 [RS-1209] Webhooks processor deployment in the operator.
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2995 Split ES metrics out of Linseed controller into its own controller
  controllers/logstorage_controller.go
  pkg/controller/logstorage/esmetrics/esmetrics_controller.go
  pkg/controller/logstorage/esmetrics/esmetrics_controller_test.go
  pkg/controller/logstorage/esmetrics/esmetrics_suite_test.go
  pkg/controller/logstorage/linseed/esmetrics.go
  pkg/controller/logstorage/linseed/linseed_controller.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, squash-commits

#2992 [EV-4356] createPredicateForObject should react if the generation isn…
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required

#2998 Pick to v1.32 [EV-4356] createPredicateForObject should react if the generation isn't set
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required

#2999 [RS-1446] - WAF UI needs permission to delete applicationlayers resources
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3000 [RS-1446] - Cherry pick delete permission for WAF UI
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3001 Update base image and dependencies
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3002 [release-v1.30] Auto Release Update for v1.30.9
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2994 Allow operations on felixconfigurations in tigera clusterroles in ord…
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3004 Automated cherry pick of #2994: Allow operations on felixconfigurations in tigera
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3003 Automated cherry pick of #2994: Allow operations on felixconfigurations in tigera
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2981 Per-tenant elasticsearch configuration
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  main.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/elastic/external_elastic_controller.go
  pkg/controller/logstorage/elastic/external_elastic_controller_test.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/controller/logstorage/linseed/linseed_controller_test.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/users/user_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/options/options.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/utils.go
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/common/elasticsearch/service.go
  pkg/render/logstorage/external.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch_suite_test.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#3005 Cherry-pick ebpf ipv6
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
Labels: docs-pr-required, release-note-required

#2989 Enable OIDC for multi-tenant setup
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#3006 [cherry-pick][1.32] Enable OIDC for multi-tenant setup (#2989)
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#3009 [RS-1379] RBAC for securityevernwebhooks for the UI.
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3011 EV-4410
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3014 [RS-1431] Allow UI admin user to create and patch webhooks-secret
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3013 Bump calico/go-build to v0.90
  Makefile
Labels: docs-pr-required, release-note-required

#3015 Fix push-manifests Makefile target
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3016 Update versions for v1.29.8/v3.16.5
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3017 [RS-1431] Allow tigera-network-admin to create secrets
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3008 Additional external ES changes
  api/v1/tenant_types.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/controller/logstorage/kubecontrollers/esgateway.go
  pkg/controller/manager/manager_controller.go
  pkg/render/fluentd.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3020 Allow get managed clusters for a cluster id for tigera-linseed using …
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#3021 Fix upgrade scenario for changing rolebinding roleref name
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, squash-commits

#3022 Fix upgrade scenario for changing rolebinding roleref name
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: release-note-not-required, docs-not-required, squash-commits

#3019 A few minor cleanups
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/users/users_controller.go
  pkg/render/logstorage.go
  pkg/render/node.go
  pkg/render/policyrecommendation.go
Labels: docs-pr-required, release-note-required
