Repository tigera/operator, pull requests merged in 2023-12, with the labels that each got.

#3026 Change rollout settings for Fluentd to speed up rollout.
  pkg/render/fluentd.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3027 [cherry-pick][1.32] Allow linseed to read secrets in tigera-operator namespace (#3024)
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3028 Fix! Delete Rolebind from toDelete objects
  pkg/render/fluentd.go
Labels: docs-pr-required, release-note-required

#3034 Fix release by preventing overwriting IMAGE_REGISTRY
  Makefile
Labels: docs-pr-required, release-note-required

#3029 Fix! Delete Rolebind from toDelete objects (#3028)
  pkg/render/fluentd.go
Labels: docs-pr-required, release-note-required

#3037 Automated cherry pick of #3034: Fix release by preventing overwriting IMAGE_REGISTRY
  Makefile
Labels: docs-pr-required, release-note-required

#3018 Add Linseed RBAC,envvars for eks log forwarding
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#3036 Release steps: Clarify github milestone creation
  RELEASING.md
Labels: docs-pr-required, release-note-required

#3040 Cherry-pick #3018 Add Linseed RBAC,envvars for eks log forwarding
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#3039 Cherry-pick #3018 Add Linseed RBAC,envvars for eks log forwarding
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#3042 EV-4413 configure Linux OS affinity for policy-recommendation
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/render/policyrecommendation.go
Labels: docs-pr-required, release-note-required

#3048 Update kibanaURL name in tenant CR
  api/v1/tenant_types.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
Labels: docs-pr-required, release-note-required

#3047 cherry-pick #3042 EV-4413 configure Linux OS affinity for policy-recommendation #3046
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/render/policyrecommendation.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3045 add support for updating docs and release note labels on version update PR
  Makefile
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch, squash-commits

#2708 CNI tuning plugin configuration added to Installation CRD
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
  pkg/controller/utils/merge.go
  pkg/controller/utils/merge_test.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#3010 Ev 4104 csr controller
  controllers/controllers.go
  controllers/csr_controller.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/csr/csr_controller.go
  pkg/controller/csr/csr_controller_suite_test.go
  pkg/controller/csr/csr_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/elastic/external_elastic_controller_test.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/utils/utils.go
  pkg/render/common/meta/meta.go
  pkg/render/common/test/testing.go
  pkg/render/logstorage.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/tls/certificatemanagement/csr.go
  pkg/tls/certificatemanagement/keypair.go
  pkg/tls/tls.go
Labels: docs-pr-required, release-note-required

#3041 Remove some RBAC resources that are unused in multi-tenant envs
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/guardian.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3050 Configure manager to properly impersonate when communicating with managed clusters
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3053 [RS-1574] Linseed misconfiguration for Webhooks in MCM configuration
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#2954 Remove usage of ES ConfigMap and PublicCertSecret
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/elastic/external_elastic_controller_test.go
  pkg/controller/logstorage/managedcluster/managed_cluster_controller.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/render/common/elasticsearch/clusterconfig.go
  pkg/render/common/elasticsearch/decorator.go
  pkg/render/common/elasticsearch/decorator_test.go
  pkg/render/common/elasticsearch/tls.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/fluentd_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: enterprise, release-note-not-required, docs-not-required

#3055 [RS-1577] Linseed cluster id is no longer required.
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#3056 fix: missing logging arguments for dikastes
  pkg/render/applicationlayer/applicationlayer.go
Labels: docs-pr-required, release-note-required

#3051 EV-4381 Add linseedDeployment in Tenant CR
  api/v1/linseed_deployment_types.go
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#3052 PolicyRecommendation needs to access resource within a tenant namespace
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/fluentd.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/utils.go
Labels: docs-pr-required, release-note-required

#3058 [cherry-pick] fix: missing logging arguments for dikastes
  pkg/render/applicationlayer/applicationlayer.go
Labels: docs-pr-required, release-note-required

#3057 Add design / code guidelines document
  README.md
  docs/common_tasks.md
  docs/controller-dependency-graph.svg
  docs/dev_guidelines.md
Labels: docs-pr-required, release-note-required

#3062 [cherry-pick][v1.33]PolicyRecommendation needs to access resource within a tenant namespa…
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/fluentd.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/utils.go
Labels: docs-pr-required, release-note-required

#3066 fix felix crds
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3070 Make gen-files
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3067 Fix issue where controller is watching a secret that is never created
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/elastic/external_elastic_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required

#3068 Automated cherry pick of #3067: Fix issue where controller is watching a secret that is never
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows_controller_test.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/elastic/external_elastic_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required

#2888 Clean up network policies watches
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/esmetrics/esmetrics_controller.go
  pkg/controller/logstorage/esmetrics/esmetrics_controller_test.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/controller/logstorage/linseed/linseed_controller.go
Labels: docs-pr-required, release-note-required

#3071 Update versions for calico v3.27.0
  config/calico_versions.yml
  config/common_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
Labels: release-note-not-required, docs-not-required

#3072 CSR Image must be instantiated
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller_test.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/controller/logstorage/linseed/linseed_controller_test.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3073 Automated cherry pick of #3072: CSR Image must be instantiated
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller_test.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/controller/logstorage/linseed/linseed_controller_test.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3083 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3079 Use common calico base and unify Dockerfiles
  .semaphore/semaphore.yml
  Makefile
  build/Dockerfile
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: docs-pr-required, release-note-required

#3081 Only watch the monitor CR if the CRD exists.
  pkg/controller/csr/csr_controller.go
Labels: docs-pr-required, release-note-required

#3082 Automated cherry pick of #3081: Only watch the monitor CR if the CRD exists.
  pkg/controller/csr/csr_controller.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready
