Repository tigera/operator, pull requests merged in 2023-07, with the labels that each got.

#2715 Prototype ability for operator to install multiple copies of tigera-manager
  api/v1/installation_types.go
  api/v1/manager_types.go
  main.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/windows/calico_windows_upgrader.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/options/options.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/request.go
  pkg/controller/utils/auth.go
  pkg/controller/utils/component.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/utils.go
  pkg/render/certificatemanagement/certificatemanagement.go
  pkg/render/guardian.go
  pkg/render/manager.go
  pkg/render/packet_capture_api.go
  pkg/render/tiers/tiers.go
Labels: docs-pr-required, release-note-required

#2713 Postpone policy recommendation scope watches until apiserver is up an…
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#2717 Automated cherry pick of #2713 origin release v1.30
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/controller/utils/utils.go
Labels: docs-pr-required, release-note-required

#2718 Compliance: Add watch for ES PublicCertSecret
  pkg/controller/compliance/compliance_controller.go
Labels: docs-pr-required, release-note-required

#2719 [pick #2718] Compliance: Add watch for ES PubliceCertSecret [r1.30]
  pkg/controller/compliance/compliance_controller.go
Labels: docs-pr-required, release-note-required

#2716 fix: WAF rules should be intialized as DetectionOnly post-install
  pkg/render/applicationlayer/modsec-core-ruleset/modsecdefault.conf
Labels: docs-pr-required, release-note-required

#2714 [EV-3840] Add networkpolicies to policy rec clusterrole
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2722 [EV-3840] Add networkpolicies to policy rec clusterrole
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2725 fix typo in filename to pod_security_policy.go
  pkg/render/common/podsecuritypolicy/pod_security_policy.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2727 Revert k8s126 update
  Makefile
  go.mod
  go.sum
  pkg/common/k8svalidation/validation.go
  pkg/controller/utils/component_test.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
Labels: docs-pr-required, release-note-required

#2729 [pick #2727] Revert k8s 1.26 update [r1.30]
  Makefile
  go.mod
  go.sum
  pkg/common/k8svalidation/validation.go
  pkg/controller/utils/component_test.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
Labels: docs-pr-required, release-note-required

#2730 Update ES&KB to v7.17.11
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2733 Automated cherry pick of #2730: Update ES&KB to v7.17.11.
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2737 make gen-files
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2736 Update golang to 1.20.6
  Makefile
  build/Dockerfile.s390x
Labels: docs-pr-required, release-note-required, merge-when-ready

#2735 Update golang to 1.20.6
  Makefile
Labels: docs-pr-required, release-note-required, merge-when-ready

#2726 Fix "make fv" target from incorrectly running UTs. Also remove
  Makefile
Labels: release-note-not-required, docs-not-required, squash-commits

#2739 Use internal manager tls certificate for es-proxy and linseed
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2742 [cherry-pick] Use internal manager tls certificate for es-proxy and linseed (#2739)
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#2741 Update operator bundle generation code
  hack/gen-bundle/get-manifests.sh
  hack/gen-bundle/update-bundle.sh
Labels: docs-pr-required, release-note-required

#2743 Don't use subPath on windows: https://github.com/moby/moby/issues/30555
  pkg/tls/certificatemanagement/certificatebundle.go
Labels: docs-pr-required, release-note-required

#2744 Automated cherry pick of #2740: Don't use subPath on windows:
  pkg/tls/certificatemanagement/certificatebundle.go
Labels: docs-pr-required, release-note-required

#2745 Automated cherry pick of #2740: Don't use subPath on windows:
  pkg/tls/certificatemanagement/certificatebundle.go
Labels: docs-pr-required, release-note-required

#2740 [CI-1296] Don't use subPath on windows: https://github.com/moby/moby/issues/30555
  pkg/tls/certificatemanagement/certificatebundle.go
Labels: docs-pr-required, release-note-required

#2750 [release-v1.30] Adjust linseed probe timeout and period seconds
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2752 CI reporting improvements
  .semaphore/semaphore.yml
  Makefile
  pkg/active/active_suite_test.go
  pkg/common/common_suite_test.go
  pkg/common/validation/validation_suite_test.go
  pkg/components/components_suite_test.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_suite_test.go
  pkg/controller/apiserver/apiserver_suite_test.go
  pkg/controller/applicationlayer/applicationlayer_suit_test.go
  pkg/controller/authentication/authentication_suite_test.go
  pkg/controller/certificatemanager/certificatemanager_suite_test.go
  pkg/controller/clusterconnection/clusterconnection_suite_test.go
  pkg/controller/compliance/compliance_suite_test.go
  pkg/controller/egressgateway/egressgateway_suite_test.go
  pkg/controller/installation/installation_controller_suite_test.go
  pkg/controller/installation/windows/windows_suite_test.go
  pkg/controller/intrusiondetection/intrusiondetection_suite_test.go
  pkg/controller/logcollector/logcollector_suite_test.go
  pkg/controller/logstorage/logstorage_controller_suite_test.go
  pkg/controller/manager/manager_controller_suite_test.go
  pkg/controller/migration/convert/convert_suite_test.go
  pkg/controller/monitor/monitor_controller_suite_test.go
  pkg/controller/policyrecommendation/policyrecommendation_suite_test.go
  pkg/controller/status/status_suite_test.go
  pkg/controller/tiers/tiers_controller_suite_test.go
  pkg/controller/utils/imageset/imageset_suite_test.go
  pkg/controller/utils/utils_suite_test.go
  pkg/crds/crds_suite_test.go
  pkg/dns/dns_suite_test.go
  pkg/render/common/components/components_suite_test.go
  pkg/render/egressgateway/egressgateway_suite_test.go
  pkg/render/intrusiondetection/dpi/dpi_suite_test.go
  pkg/render/kubecontrollers/kube-controllers_suite_test.go
  pkg/render/logstorage/esgateway/esgateway_suite_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_suite_test.go
  pkg/render/logstorage/linseed/linseed_suite_test.go
  pkg/render/monitor/monitor_suite_test.go
  pkg/render/render_suite_test.go
  pkg/render/tiers/tiers_suite_test.go
  test/fv_suite_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, squash-commits

#2753 Add watch for managed cluster linseed cert in compliance
  pkg/controller/compliance/compliance_controller.go
Labels: docs-pr-required, release-note-required

#2754 [pick #2753] Add watch for managed cluster linseed cert in compliance [r1.30]
  pkg/controller/compliance/compliance_controller.go
Labels: docs-pr-required, release-note-required

#2756 [pick #2753] Add watch for managed cluster linseed cert in compliance [r1.31]
  pkg/controller/compliance/compliance_controller.go
Labels: docs-pr-required, release-note-required

#2758 Add .PHONY for ut target and ignore ut folder
  .gitignore
  Makefile
Labels: docs-pr-required, release-note-required

#2755 Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  main.go
  pkg/crds/crds.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2724 Openshift PodSecurity
  pkg/render/apiserver.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#2759 update CRD (felixConfiguration)
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2760 cherrypick #2759 update CRD (felixConfiguration)
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2762 [release-v1.30] Add PSPs for dex and policy recommendation
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#2764 Openshift PodSecurity
  pkg/render/apiserver.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#2757 Add PSPs for dex and policy recommendation
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2761 [release-v1.31] Add PSPs for dex and policy recommendation
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2763 Openshift PodSecurity
  pkg/render/apiserver.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/namespaces.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2766 cherrypick #2765 - update CRD (OSS felixConfiguration)
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2769 [release-v1.29] Add PSP for dex
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required

#2775 Cert fix
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/render/common/secret/secrets.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/fluentd.go
  pkg/render/intrusion_detection.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/policyrecommendation.go
  pkg/tls/certkeyusage/certkeyusage.go
Labels: docs-pr-required, release-note-required

#2774 Merge upstream master branch
  .semaphore/semaphore.yml
  Makefile
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver_test.go
  pkg/render/compliance_test.go
  pkg/render/dex_test.go
  pkg/render/fluentd_test.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor_test.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api_test.go
  pkg/render/policyrecommendation_test.go
  pkg/render/render_test.go
  pkg/render/typha_test.go
  test/active_test.go
  test/crd_management_test.go
  test/load_images_on_kind_cluster.sh
  test/mainline_test.go
  test/utils.go
Labels: release-note-not-required, docs-not-required

#2777 [pick #2775] Recreate certificates that are only specified to be used as server certs [r1.31]
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/render/common/secret/secrets.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/fluentd.go
  pkg/render/intrusion_detection.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/policyrecommendation.go
  pkg/tls/certkeyusage/certkeyusage.go
Labels: docs-pr-required, release-note-required

#2778 [Pick #2775] Recreate certificates that are only specified to be used as server certs [r1.30]
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/compliance/compliance_controller.go
  pkg/render/common/secret/secrets.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/fluentd.go
  pkg/render/intrusion_detection.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/policyrecommendation.go
  pkg/tls/certkeyusage/certkeyusage.go
Labels: docs-pr-required, release-note-required

#2779 Fix for EGW deployment in openshift 4.13
  pkg/controller/installation/core_controller.go
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required

#2780 Merge pull request #2779 from sridhartigera/openshift-egw
  pkg/controller/installation/core_controller.go
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required

#2781 Merge pull request #2779 from sridhartigera/openshift-egw
  pkg/controller/installation/core_controller.go
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required
