Repository tigera/operator, pull requests merged in 2023-06, with the labels that each got.

#2670 Add temporary role for calico-node during namespace migration
  pkg/controller/migration/namespace_migration.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-not-required, docs-not-required

#2681 Cherry-pick #2670 Add temporary role for calico-node during namespace migration
  pkg/controller/migration/namespace_migration.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2682 s390x: build s390x binary and image
  .semaphore/clean_up.yml
  .semaphore/push_images.yml
  .semaphore/semaphore.yml
  Makefile
  build/Dockerfile.s390x
Labels: release-note-required, docs-not-required

#2683 [release-v1.30] Auto pick #2617: Move BGPFilter permissions from EE-only to OSS+EE in
  pkg/render/apiserver.go
Labels: kind/bug, release-note-required, docs-not-required

#2661 Changes to pick fips image for all the components
  hack/gen-versions/calico.go.tpl
  pkg/components/calico.go
  pkg/components/references.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#2684 Remove tigera-prometheus-api deployment that may have been installed …
  pkg/controller/monitor/monitor_controller_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#2686 Cherry-pick fips changes to 1.30
  hack/gen-versions/calico.go.tpl
  pkg/components/calico.go
  pkg/components/references.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#2685 Cherry-pick fips changes to 1.29
  hack/gen-versions/calico.go.tpl
  pkg/components/calico.go
  pkg/components/references.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#2687 Openshift namespace label
  pkg/render/namespaces.go
Labels: docs-pr-required, release-note-required

#2657 rs-979: [applicationlayer] configurable envoy xff settings
  api/v1/applicationlayer_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/applicationlayer/envoy-config.yaml.template
Labels: docs-pr-required, release-note-required

#2692 Release v1.29
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2690 Cherry-pick #2687 Openshift namespace label
  pkg/render/namespaces.go
Labels: hold merge, docs-pr-required, release-note-required

#2678 Anomaly detection jobs should query Linseed
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/testutils/expected_policies/ad-detectors.json
  pkg/render/testutils/expected_policies/ad-detectors_ocp.json
Labels: docs-pr-required, release-note-required

#2694 Update versions for calient v3.17.0 redux
  config/common_versions.yml
  pkg/components/common.go
Labels: docs-pr-required, release-note-required

#2699 Remove CLUSTER_NAME for compliance; Will rely on Voltron to setup the…
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#2701 [cherry-pick] Remove CLUSTER_NAME for compliance; Will rely on Voltron to setup the…
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#2702 update crd
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
Labels: docs-pr-required, release-note-required

#2693 Update and clarify release instructions
  RELEASING.md
Labels: docs-pr-required, release-note-required

#2697 Fix missing certificate management configurations
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#2705 Automated cherry pick of #2697: "Fix missing certificate management configurations"
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#2706 Linseed must be able to verify Voltron's certificate
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required

#2707 [release-v1.30] Auto pick #2706: Linseed must be able to verify Voltron's certificate
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required

#2711 Anomaly detection jobs should query Linseed (#2678)
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/testutils/expected_policies/ad-detectors.json
  pkg/render/testutils/expected_policies/ad-detectors_ocp.json
Labels: docs-pr-required, release-note-required

#2703 Drop cluster name from intrusion detection controller
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2710 Drop cluster name from intrusion detection controller
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2700 Set DNS trusted servers using FelixConfig instead of FELIX_ env var
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/utils/felix_configuration.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: kind/bug, release-note-not-required, docs-not-required
