Repository tigera/operator, pull requests merged in 2023-03, with the labels that each got.

#2510 [pick #2483] CSI driver should tolerate all like l7 and node [r1.29]
  pkg/render/csi.go
Labels: docs-pr-required, release-note-required

#2509 [pick #2483] CSI driver should tolerate all like l7 and node [r1.28]
  pkg/render/csi.go
Labels: docs-pr-required, release-note-required

#2501 [Release 1.29] Update dependencies (cherry-pick 2500)
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready

#2502 [Release 1.28] Update dependencies (cherry-pick 2500)
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready

#2499 Copy pull secrets to the EGW namespace
  pkg/common/common.go
  pkg/common/components.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/controller/utils/component.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: release-note-not-required, docs-not-required

#2512 Cherry-pick PR 2499
  pkg/common/common.go
  pkg/common/components.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/controller/utils/component.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#2511 Remove Elastic SELinux init container
  pkg/controller/logstorage/logstorage_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2504 Add and update PodSecurityPolicy to match SecurityContext
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/esgateway.go
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/linseed.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/utils/discovery.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/common/podsecuritypolicy/pod_secruity_policy.go
  pkg/render/compliance.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2514 [release-v1.29] Add and update PodSecurityPolicy to match SecurityContext
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/esgateway.go
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/utils/discovery.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/common/podsecuritypolicy/pod_secruity_policy.go
  pkg/render/compliance.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#2513 Bump Kibana version to v7.17.9
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2524 Add NET_RAW capability to ocp scc.
  pkg/render/egressgateway/egressgateway.go
Labels: docs-pr-required, release-note-required

#2525 Add NET_RAW capability to ocp scc. (#2524)
  pkg/render/egressgateway/egressgateway.go
Labels: docs-pr-required, release-note-required

#2523 [release-v1.28] Bump Kibana version to v7.17.9
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2522 [release-v1.29] Bump Kibana version to v7.17.9
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2521 [release-v1.28] Bump Elasticsearch version to v7.17.9
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2519 Bump Elasticsearch version to v7.17.9
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2520 [release-v1.29] Bump Elasticsearch version to v7.17.9
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2516 Add waf resource to the lma.tigera.io resource group
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: release-note-required, docs-not-required

#2531 Merge pull request #2516 from gantony/add_viewer_waf_runtime
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2529 Automated cherry pick of #2528: Update ECK to 2.6.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2530 Automated cherry pick of #2528: Update ECK to 2.6.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2528 Update ECK to 2.6.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2533 [1.28] Add missing egress flow to Guardian access policy
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/testutils/expected_policies/guardian.json
  pkg/render/testutils/expected_policies/guardian_ocp.json
Labels: docs-pr-required, release-note-required

#2534 [1.29] Add missing egress flow to Guardian access policy
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/testutils/expected_policies/guardian.json
  pkg/render/testutils/expected_policies/guardian_ocp.json
Labels: docs-pr-required, release-note-required

#2535 [master] Add missing egress flow to Guardian access policy
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/testutils/expected_policies/guardian.json
  pkg/render/testutils/expected_policies/guardian_ocp.json
Labels: docs-pr-required, release-note-required

#2526 release-v1.29 cherry pick of #2377: Fix race condition where trusted bundle is rendered twice
  pkg/controller/logstorage/esgateway.go
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required

#2539 Trim extraneous lines in operator CRD yamls
  Makefile
  pkg/crds/operator/operator.tigera.io_amazoncloudintegrations.yaml
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
Labels: docs-pr-required, release-note-required

#2538 Bump alertmanager version to v0.25.0
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2544 Update the CRDs
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
Labels: docs-pr-required, release-note-required

#2517 stabilise intrusion detection failures due to elastic search not being ready
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/utils/utils.go
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#2548 Update CRDs
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2549 Automated cherry pick of #2541: Use golang 1.19.7 and controller-gen v0.11.3
  Makefile
  hack/gen-versions/components.go
  pkg/common/autoscale.go
  pkg/common/k8svalidation/v1helper/v1helper.go
  pkg/common/k8svalidation/v1validation.go
  pkg/common/operator_namespace.go
  pkg/common/operator_serviceaccount.go
  pkg/controller/installation/core_controller.go
  pkg/controller/migration/convert/ippools.go
  pkg/controller/status/mock.go
  pkg/controller/status/status.go
  pkg/controller/utils/elasticsearch_test.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_amazoncloudintegrations.yaml
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
  pkg/render/common/authentication/types.go
  pkg/render/common/secret/secrets.go
  pkg/render/tiers/tiers_suite_test.go
Labels: docs-pr-required, release-note-required

#2503 Expose logging config for calico cni
  api/v1/common_types.go
  api/v1/egressgateway_types.go
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/utils/merge.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2551 Add clusterrolebinding for OCP w/ federation
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#2552 Automated cherry pick of #2551: Add clusterrolebinding for OCP w/ federation
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#2553 Automated cherry pick of #2551: Add clusterrolebinding for OCP w/ federation
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#2559 check for cniLogging nil values before referencing
  pkg/render/node.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#2558 Prepare EE v3.16.1-1 pre-release
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#2556 [release-v1.29] Add PSP PolicyRule for anomaly detection detectors
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#2532 Intrusion detection migration to Linseed API
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_suite_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/endpoints.go
  pkg/render/fluentd.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/testutils/expected_policies/intrusion-detection-controller_unmanaged.json
  pkg/render/testutils/expected_policies/intrusion-detection-controller_unmanaged_ocp.json
Labels: docs-pr-required, release-note-required

#2560 Cherry pick (#2517) to rel-1.29
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/utils/utils.go
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2563 Cherry pick (#2517) to rel-1.28
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/logstorage.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/utils/utils.go
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2564 Prevent installation of PSPs in OCP in order to use SCCs instead
  main.go
Labels: release-note-not-required, docs-not-required

#2565 Prevent installation of PSPs in OCP in order to use SCCs instead
  main.go
Labels: release-note-not-required, docs-not-required

#2570 Prepare for release 3.15.2
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2561 Update Calico Enterprise Compliance to use Linseed
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/testutils/expected_policies/compliance-server.json
  pkg/render/testutils/expected_policies/compliance-server_ocp.json
  pkg/render/testutils/expected_policies/compliance_unmanaged.json
  pkg/render/testutils/expected_policies/compliance_unmanaged_ocp.json
Labels: docs-pr-required, release-note-required

#2393 Separate calico-node and calico-cni-plugin service accounts
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#2572 Add shards and replicas to Linseed
  pkg/controller/logstorage/linseed.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/common/elasticsearch/decorator.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2573 Add BGPFilter and ExternalNetwork RBAC to node
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#2567 Removes named resource clause on applicationlayers resource.
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: kind/bug, enterprise, release-note-not-required, docs-not-required

#2574 Remove unused K8s registry
  pkg/components/images.go
Labels: docs-pr-required, release-note-required

#2575 Allow connection between DPI and linseed
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/testutils/expected_policies/dpi_unmanaged.json
  pkg/render/testutils/expected_policies/dpi_unmanaged_ocp.json
Labels: docs-pr-required, release-note-required

#2577 Prepare for release 3.25.1
  .semaphore/semaphore.yml
  config/calico_versions.yml
  pkg/components/calico.go
Labels: docs-pr-required, release-note-required
