Repository tigera/operator, pull requests merged in 2023-05, with the labels that each got.

#2610 Fix! Linseed should have a rolling deployment strategy
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2598 migrate typha deployment affinities
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/core_test.go
Labels: docs-pr-required, release-note-required

#2614 Revert access to secrets for Linseed
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2616 [Cherry-pick] Rever secrets rbac & add rolling update strategy to linseed deployment
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#2617 Move BGPFilter permissions from EE-only to OSS+EE in apiserver
  pkg/render/apiserver.go
Labels: kind/bug, docs-pr-required, release-note-required

#2547 Update readme
  README.md
Labels: release-note-not-required, docs-not-required

#2612 Add policy to support nodelocal dnscache
  main.go
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/tiers/tiers_controller_test.go
  pkg/controller/utils/utils.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/common/test/testing.go
  pkg/render/testutils/expected_policies/dns.json
  pkg/render/testutils/expected_policies/dns_ocp.json
  pkg/render/testutils/expected_policies/node_local_dns_dual.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv4.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv6.json
  pkg/render/testutils/policy.go
  pkg/render/tiers/tiers.go
  pkg/render/tiers/tiers_test.go
Labels: docs-pr-required, release-note-required

#2615 Check more indicators for EKS discovery
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
Labels: kind/enhancement, docs-pr-required, release-note-required

#2623 Cherrypick Add policy to support nodelocal dnscache
  main.go
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/tiers/tiers_controller_test.go
  pkg/controller/utils/utils.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/common/test/testing.go
  pkg/render/testutils/expected_policies/dns.json
  pkg/render/testutils/expected_policies/dns_ocp.json
  pkg/render/testutils/expected_policies/node_local_dns_dual.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv4.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv6.json
  pkg/render/testutils/policy.go
  pkg/render/tiers/tiers.go
  pkg/render/tiers/tiers_test.go
Labels: docs-pr-required, release-note-required

#2624 Do not manage Kibana certs/secrets in Managed clusters
  pkg/controller/logstorage/logstorage.go
Labels: docs-pr-required, release-note-required

#2625 [1.30] Do not manage Kibana certs/secrets in Managed clusters
  pkg/controller/logstorage/logstorage.go
Labels: docs-pr-required, release-note-required

#2626 Prepare for release 3.15.3
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#2629 Update CRDs: felixconfigurations update [r1.30]
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2633 Update CRDs: felixconfigurations update
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2627 Check more indicators for EKS discovery [pick 2615, r1.30]
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
Labels: docs-pr-required, release-note-required

#2628 Check more indicators for EKS discovery [pick 2615, r1.29]
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
Labels: docs-pr-required, release-note-required

#2634 [release-v1.30] Bump Prometheus version to v2.43.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2631 Bump Prometheus version to v2.43.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2604 s390x: build s390x binary and image
  .semaphore/clean_up.yml
  .semaphore/push_images.yml
  .semaphore/semaphore.yml
  Makefile
  build/Dockerfile.s390x
Labels: docs-pr-required, release-note-required

#2590 A couple of development improvements
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/common.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/references.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/amazoncloudintegration.go
  pkg/render/apiserver.go
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/compliance.go
  pkg/render/csi.go
  pkg/render/dex.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/fluentd.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/node.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
  pkg/render/policyrecommendation.go
  pkg/render/render.go
  pkg/render/typha.go
  pkg/render/windows.go
Labels: docs-pr-required, release-note-required

#2632 Make es-gateway use rolling update instead of recreate strategy
  pkg/render/logstorage/esgateway/esgateway.go
Labels: docs-pr-required, release-note-required

#2637 [cherry-pick] Make es-gateway use rolling update instead of recreate strategy (#2632)
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/logstorage/esgateway/esgateway.go
Labels: docs-pr-required, release-note-required

#2636 Enforce default deny for calico-system
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/testutils/expected_policies/dns.json
  pkg/render/testutils/expected_policies/dns_ocp.json
  pkg/render/testutils/expected_policies/kubecontrollers.json
  pkg/render/testutils/expected_policies/kubecontrollers_managed.json
  pkg/render/testutils/expected_policies/kubecontrollers_managed_ocp.json
  pkg/render/testutils/expected_policies/kubecontrollers_ocp.json
  pkg/render/testutils/expected_policies/node_local_dns_dual.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv4.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv6.json
  pkg/render/tiers/tiers.go
Labels: docs-pr-required, release-note-required

#2638 [v1.30] Enforce default deny for calico-system
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/testutils/expected_policies/dns.json
  pkg/render/testutils/expected_policies/dns_ocp.json
  pkg/render/testutils/expected_policies/kubecontrollers.json
  pkg/render/testutils/expected_policies/kubecontrollers_managed.json
  pkg/render/testutils/expected_policies/kubecontrollers_managed_ocp.json
  pkg/render/testutils/expected_policies/kubecontrollers_ocp.json
  pkg/render/testutils/expected_policies/node_local_dns_dual.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv4.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv6.json
  pkg/render/tiers/tiers.go
Labels: docs-pr-required, release-note-required

#2646 Prepare for release 3.24.6
  config/calico_versions.yml
  hack/gen-versions/calico.go.tpl
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2645 Use correct calico-node UID when running in non-privileged mode.
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2651 Merge pull request #2645 from sridhartigera/host-path-init
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2652 Hostpath init cherry-pick -v1.29
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2641 [Release 1.30] Update base image to UBI 8.8
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required, merge-when-ready

#2642 [Release 1.29] Update base 1.29
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required, merge-when-ready

#2644 [Release 1.27] Update base image to UBI 8.8
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required, merge-when-ready

#2653 Remove GeoIP downloader from Elasticsearch as we have no use for it.
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2654 Remove /etc/calico host path volume
  pkg/render/csi.go
Labels: docs-pr-required, release-note-required

#2655 Automated cherry pick of #2653: Remove GeoIP downloader from Elasticsearch as we have no
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2656 Automated cherry pick of #2653: Remove GeoIP downloader from Elasticsearch as we have no
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#2660 update golang version to 1.20.4
  Makefile
Labels: docs-pr-required, release-note-required

#2659 [Release 1.30] Update golang to 1.20.4
  Makefile
Labels: docs-pr-required, release-note-required

#2639 Add dynamic layers to tigera infra layer in SG EV-3506
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/render/guardian.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#2620 Add policyrecommendationscopes to CRDs list
  hack/gen-bundle/get-manifests.sh
Labels: docs-pr-required, release-note-required

#2666 Update CRDs
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
Labels: docs-pr-required, release-note-required

#2665 Update CRDs
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
Labels: docs-pr-required, release-note-required

#2667 [EV-3431] Add linseed resources to policy recommendation (#2621)
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/testutils/expected_policies/linseed.json
  pkg/render/testutils/expected_policies/linseed_ocp.json
  pkg/render/testutils/expected_policies/policyrecommendation.json
  pkg/render/testutils/expected_policies/policyrecommendation_managed.json
  pkg/render/testutils/expected_policies/policyrecommendation_managed_ocp.json
  pkg/render/testutils/expected_policies/policyrecommendation_ocp.json
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2668 Fix! Windows needs c: prefix for the token path
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2669 Automated cherry pick of #2668: Fix! Windows needs c: prefix for the token path
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#2663 Revert "Add dynamic layers to tigera infra layer in SG EV-3506"
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/render/guardian.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2664 Revert "Cherry-pick #2639 Add dynamic layers to tigera infra layer in SG EV-3506"
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/render/guardian.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2611 Update versions for v3.26.0
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-bundle/get-manifests.sh
  hack/gen-versions/calico.go.tpl
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
Labels: docs-pr-required, release-note-required

#2673 cherry-pick #2671 Add missing namespaces to SG layer tigera infrastructure EV-3506
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#2671 Add missing namespaces to SG layer tigera infrastructure EV-3506
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#2674 Add RBAC for threat feeds
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#2676 [ev-3754] Prepare ee-v3.17.0
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
Labels: docs-pr-required, release-note-required

#2677 Fix the registry
  hack/gen-versions/main.go
  pkg/components/images.go
Labels: docs-pr-required, release-note-required
