Repository tigera/operator, pull requests merged in 2023-10, with the labels that each got.

#2900 Linseed single index support
  pkg/controller/logstorage/users/user_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#2914 Add Windows HPC EE support
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#2915 Update for v3.26.2
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2917 Update for Calico v3.26.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#2918 Guard AD PSP deletion
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#2662 RFC: Graceful termination of the operator
  main.go
  pkg/controller/installation/core_controller.go
  pkg/render/namespaces.go
Labels: docs-pr-required, release-note-required

#2922 Fix windows_controller/core_controller race condition
  pkg/controller/installation/windows_controller.go
  pkg/controller/installation/windows_controller_test.go
Labels: release-note-not-required, docs-not-required

#2907 [Release v1.30] Add egressgatewaypolicies to node RBAC
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#2908 [Release v1.31] Add egressgatewaypolicies to node RBAC
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#2925 Update CRDs: stagedkubernetesnetworkpolicies
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
Labels: release-note-not-required, docs-not-required

#2924 Update apiserver controller to handle old voltron cert format
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/tls/certificatemanagement/keypair.go
Labels: docs-pr-required, release-note-required

#2928 Update versions for v1.31.2/v3.18.0-1.1
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#2927 [pick #2924] Update apiserver controller to handle old voltron cert format [r1.30]
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/tls/certificatemanagement/keypair.go
Labels: release-note-required, docs-not-required

#2931 Add fluentd-windows prometheus metrics support
  pkg/controller/installation/windows_controller.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#2936 Various fixes for multi-tenancy
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/testutils/expected_policies/compliance-server.json
  pkg/render/testutils/expected_policies/compliance-server_ocp.json
  pkg/render/testutils/expected_policies/dex.json
  pkg/render/testutils/expected_policies/dex_ocp.json
  pkg/render/testutils/expected_policies/elasticsearch.json
  pkg/render/testutils/expected_policies/elasticsearch_ocp.json
  pkg/render/testutils/expected_policies/es-gateway.json
  pkg/render/testutils/expected_policies/es-gateway_ocp.json
  pkg/render/testutils/expected_policies/guardian.json
  pkg/render/testutils/expected_policies/guardian_ocp.json
  pkg/render/testutils/expected_policies/kibana.json
  pkg/render/testutils/expected_policies/kibana_ocp.json
  pkg/render/testutils/expected_policies/linseed.json
  pkg/render/testutils/expected_policies/linseed_dpi_enabled.json
  pkg/render/testutils/expected_policies/linseed_ocp.json
  pkg/render/testutils/expected_policies/linseed_ocp_dpi_enabled.json
  pkg/render/testutils/expected_policies/packetcapture.json
  pkg/render/testutils/expected_policies/packetcapture_managed.json
  pkg/render/testutils/expected_policies/packetcapture_managed_ocp.json
  pkg/render/testutils/expected_policies/packetcapture_ocp.json
Labels: docs-pr-required, release-note-required

#2930 Clean up Linseed elastic users for non-existent tenants
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/elastic/mock.go
  pkg/controller/logstorage/users/user_controller.go
  pkg/controller/logstorage/users/users_controller_suite_test.go
  pkg/controller/logstorage/users/users_controller_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/utils_test.go
Labels: release-note-not-required, docs-not-required, squash-commits

#2941 [cherry-pick][1.32] Various fixes for multi-tenancy (#2936)
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/testutils/expected_policies/compliance-server.json
  pkg/render/testutils/expected_policies/compliance-server_ocp.json
  pkg/render/testutils/expected_policies/dex.json
  pkg/render/testutils/expected_policies/dex_ocp.json
  pkg/render/testutils/expected_policies/elasticsearch.json
  pkg/render/testutils/expected_policies/elasticsearch_ocp.json
  pkg/render/testutils/expected_policies/es-gateway.json
  pkg/render/testutils/expected_policies/es-gateway_ocp.json
  pkg/render/testutils/expected_policies/guardian.json
  pkg/render/testutils/expected_policies/guardian_ocp.json
  pkg/render/testutils/expected_policies/kibana.json
  pkg/render/testutils/expected_policies/kibana_ocp.json
  pkg/render/testutils/expected_policies/linseed.json
  pkg/render/testutils/expected_policies/linseed_dpi_enabled.json
  pkg/render/testutils/expected_policies/linseed_ocp.json
  pkg/render/testutils/expected_policies/linseed_ocp_dpi_enabled.json
  pkg/render/testutils/expected_policies/packetcapture.json
  pkg/render/testutils/expected_policies/packetcapture_managed.json
  pkg/render/testutils/expected_policies/packetcapture_managed_ocp.json
  pkg/render/testutils/expected_policies/packetcapture_ocp.json
Labels: docs-pr-required, release-note-required

#2943 Update CRDs and commit
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2942 Cherry-pick elastic users cleanup controller
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/elastic/mock.go
  pkg/controller/logstorage/users/user_controller.go
  pkg/controller/logstorage/users/users_controller_suite_test.go
  pkg/controller/logstorage/users/users_controller_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/utils_test.go
Labels: docs-pr-required, release-note-required

#2944 Include tenant namespaces in DNS access policies
  pkg/controller/tiers/tiers_controller.go
  pkg/render/tiers/tiers.go
  pkg/render/tiers/tiers_test.go
Labels: docs-pr-required, release-note-required

#2946 [release-v1.32] Auto pick #2944: Include tenant namespaces in DNS access policies
  pkg/controller/tiers/tiers_controller.go
  pkg/render/tiers/tiers.go
  pkg/render/tiers/tiers_test.go
Labels: docs-pr-required, release-note-required

#2947 Management cluster installation fixes
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#2948 (master) Management cluster installation fixes
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#2939 Automated cherry pick of #2938: Add a label to the prometheus service, so it can be
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#2950 [release-v1.32] Auto pick #2949: Make windowsDataplane disabled by default in providerAKS (as
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
Labels: release-note-not-required, docs-not-required

#2945 Changes to support ebpf and ipv6
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2949 Make windowsDataplane disabled by default in providerAKS (as with all other cases too)
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
Labels: release-note-not-required, docs-not-required

#2952 [Release v1.32] Update BGPFitler CRDs
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
Labels: docs-pr-required, release-note-required

#2957 [EV-4308] update kb and elastic to 7.17.14
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2951 update kb and elastic to 7.17.14
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2956 [EV-4308] update kb and elastic to 7.17.14
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#2955 [EV-4308] update kb and elastic to 7.17.14
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required
