Repository tigera/operator, pull requests merged in 2023-01, with the labels that each got.

#2371 Update numorstring
  Makefile
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/migration/convert/felix_vars.go
  pkg/controller/migration/convert/felix_vars_test.go
  pkg/controller/migration/convert/numorstring/numorstring.go
Labels: docs-pr-required, release-note-required

#2370 Update numorstring
  Makefile
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/migration/convert/felix_vars.go
  pkg/controller/migration/convert/felix_vars_test.go
  pkg/controller/migration/convert/numorstring/numorstring.go
Labels: docs-pr-required, release-note-required

#2368 [v1.27] Work around upgrade bug from versions that don't support TPROXY.
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
Labels: release-note-required, docs-not-required

#2379 partial pick from pull #1832 to add missing cert
  pkg/controller/logstorage/esmetrics.go
Labels: docs-pr-required, release-note-required

#2374 [v1.26] Work around upgrade issue upgrading from versions that don't support TPROXY.
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
Labels: docs-pr-required, release-note-required

#2373 [v1.28] Work around upgrade issue upgrading from versions that don't support TPROXY.
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
Labels: docs-pr-required, release-note-required

#2380 Bump golang version to 1.18
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2381 Update CRDs - generate filles/versions
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
Labels: docs-pr-required, release-note-required

#2378 Automated cherry pick of #2377: Fix race condition where trusted bundle is rendered twice
  pkg/controller/logstorage/esgateway.go
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required

#2383 Prepare v1.27.7
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2384 update crds
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2382 Run job until it eventually completes
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2331 add support override for csi-node-driver
  api/v1/csi_node_driver.go
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/installation/validation.go
  pkg/controller/utils/merge.go
  pkg/controller/utils/merge_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required

#2395 Update to Calico v3.25.0
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_externalnetworks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
Labels: release-note-not-required, docs-not-required

#2391 Automated cherry pick of #2390: Add private flexvol image (#2363)
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2396 Egress Gateway - operator changes (#2336)
  api/v1/egressgateway_types.go
  api/v1/zz_generated.deepcopy.go
  config/enterprise_versions.yml
  config/samples/operator_v1_egressgateway.yaml
  controllers/controllers.go
  controllers/egressgateway_controller.go
  hack/gen-versions/enterprise.go.tpl
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/ippool.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/components/enterprise.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/controller/egressgateway/egressgateway_suite_test.go
  pkg/controller/utils/discovery.go
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_suite_test.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#2400 Prepare EE v3.15.0-1 pre release.
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#2385 Automated cherry pick of #2382: Run job until it eventually completes
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2398 Add externalNetwork to the EGW operator CRD
  api/v1/egressgateway_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/apis/crd.projectcalico.org/v1/externalnetwork.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#2401 Add externalNetwork to the EGW operator CRD (#2398)
  api/v1/egressgateway_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/apis/crd.projectcalico.org/v1/externalnetwork.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#2386 Automated cherry pick of #2382: Run job until it eventually completes
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2403 Fix: incompatible job spec caused controller to fail
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required

#2404 Automated cherry pick of #2403: Fix: incompatible job spec caused controller to fail
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2405 Automated cherry pick of #2403: Fix: incompatible job spec caused controller to fail
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2406 Fix EGW upgrade and crd comments for doc
  api/v1/egressgateway_types.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
Labels: docs-pr-required, release-note-required

#2407 Fix EGW upgrade and crd comments for doc (#2406)
  api/v1/egressgateway_types.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2408 Update ids controller healthz path
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2410 [release-v1.28] Update ids controller healthz path
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2409 [release-v1.29] Update ids controller healthz path
  pkg/render/intrusion_detection.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2377 Fix race condition where trusted bundle is rendered twice with differ…
  pkg/controller/logstorage/esgateway.go
  pkg/controller/logstorage/esmetrics.go
  pkg/controller/logstorage/logstorage_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2390 Add pod2daemon private mstr
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#2413 Add some missing certificates to the bundles of various namespaces
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2416 Automated cherry pick of #2413: Add some missing certificates to the bundles of various
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
Labels: release-note-required, docs-not-required

#2415 Automated cherry pick of #2413: Add some missing certificates to the bundles of various
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/logstorage/eskubecontrollers.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller.go
Labels: release-note-required, docs-not-required

#2421 Move guardian hash annotation to podTemplate
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#2422 [RS-707] - Allow tigera-ui-user to view WAF config
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2419 Automated cherry pick of #2417: Remove max-tls-flag. It is no longer necessary for FIPS mode
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2418 Automated cherry pick of #2417: Remove max-tls-flag. It is no longer necessary for FIPS mode
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2417 Remove max-tls-flag. It is no longer necessary for FIPS mode
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2424 [pick 2421 r1.28] Move guardian hash annotation to podTemplate
  pkg/render/guardian.go
Labels: release-note-not-required, docs-not-required

#2423 [pick 2421 r1.29] Move guardian hash annotation to podTemplate
  pkg/render/guardian.go
Labels: release-note-not-required, docs-not-required

#2425 [RS-707] - Allow tigera-ui-user to view WAF config (#2422)
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#2329 Allow query server talk to Prometheus
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2426 [release-v1.29] Allow query server talk to Prometheus
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2428 [release-v1.28] Allow query server talk to Prometheus
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#2427 Create, delete cluster scoped resources from EGW controller
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/utils/component.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/apiserver.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/guardian.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/monitor/monitor.go
  pkg/render/packet_capture_api.go
  pkg/render/passthru.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#2430 Cherry-pick https://github.com/tigera/operator/pull/2427 to 1.29
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/utils/component.go
  pkg/render/apiserver.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/guardian.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/monitor/monitor.go
  pkg/render/packet_capture_api.go
  pkg/render/passthru.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#2435 Prepare EE v3.15.1 with Operator version v1.28.10
  config/enterprise_versions.yml
  go.mod
  go.sum
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
Labels: docs-pr-required, release-note-required

#2434 Update CRDs to the latest
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
Labels: docs-pr-required, release-note-required

#2432 Use two constructors for deletion passthru
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/apiserver.go
  pkg/render/guardian.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/monitor/monitor.go
  pkg/render/packet_capture_api.go
  pkg/render/passthru.go
  pkg/render/render_test.go
Labels: release-note-not-required, docs-not-required

#2431 Pass user and password to connect to ES
  pkg/controller/logstorage/linseed.go
  pkg/controller/logstorage/logstorage_controller.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/logstorage.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/testutils/expected_policies/elasticsearch.json
  pkg/render/testutils/expected_policies/elasticsearch_ocp.json
  pkg/render/testutils/expected_policies/manager.json
  pkg/render/testutils/expected_policies/manager_ocp.json
Labels: docs-pr-required, release-note-required

#2436 Merge pull request #2432 from caseydavenport/casey-del-passthru
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/installation/core_controller.go
  pkg/controller/monitor/monitor_controller.go
  pkg/render/apiserver.go
  pkg/render/guardian.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/monitor/monitor.go
  pkg/render/packet_capture_api.go
  pkg/render/passthru.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#2437 Do not delete psp when cluster doesn't support psp
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: release-note-not-required, docs-not-required
