Repository tigera/operator, pull requests merged in 2024-06, with the labels that each got.

#3371 Attach OpenShift nonroot-v2 SCC to Prometheus components
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#3372 Handle PC RBAC creation in FluentD
  pkg/controller/logcollector/logcollector_controller.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#3368 Clean up unused variables from manager
  pkg/controller/manager/manager_controller.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3157 Wait for calico-node DaemonSet rollout to avoid mass restart during manifest-to-operator migration
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/migration/namespace_migration.go
Labels: release-note-required, docs-not-required, merge-when-ready

#3344 update script to generate release notes from milestone
  Makefile
  RELEASING.md
  build/Dockerfile.release-notes
  generate-release-notes.py
  hack/generate_release_notes.py
Labels: release-note-not-required, docs-not-required

#3376 Grant ES Proxy rights to create LocalSubjectAccessReviews
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/guardian.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3377 Handle compliance manager flags for optin experience
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3379 Skip creation of dex cert management when disabled
  pkg/controller/authentication/authentication_controller.go
Labels: docs-pr-required, release-note-required

#3380 [cherry-pick] [1.34] Shorten kibana session. (#3306)
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3381 Allow Terminating resources to be recreated when Installation is not finalizing.
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, squash-commits

#3385 [release-v1.34] Auto pick #3381: Fix deadlock where terminating resources were never
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, squash-commits

#3382 Bump es and kb to v7.17.21
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3383 Bump es and kb to v7.17.21
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3386 [release-v1.33] Auto pick #3381: Fix deadlock where terminating resources were never
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/render/node.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required

#2545 Remove LogCollector Splunk public certificate
  pkg/controller/logcollector/logcollector_controller.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#3388 [release-v1.32] Auto Release Update for v1.32.9
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3391 [release-v1.35] Bump Elastic and Kibana to v7.17.22
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3390 Bump Elastic and Kibana to v7.17.22
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3392 [release-v1.34] Auto Release Update for v1.34.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/usage.tigera.io_licenseusagereports.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3378 Switch to ClusterRole/RoleBindings to get ManagedClusters to pass authorizat…
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#3393 Rearrange multi-tenant UTs so they're not longer subset of single-ten…
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required

#3395 Port creating an MTLS client for ElasticSearch
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/elastic/mock.go
  pkg/controller/logstorage/users/users_controller.go
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#3394 Fix! Make intrusion detection multi-tenant aware
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage/linseed/linseed.go
Labels: docs-pr-required, release-note-required

#3398 Update crds in release-v1.35
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required
