Repository tigera/operator, pull requests merged in 2024-01, with the labels that each got.

#3075 Break infinite reconciliation loop
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required

#3084 Automated cherry pick of #3075: Avoid endless reconcile loop when image pull secrets are
  pkg/controller/utils/component.go
  pkg/controller/utils/component_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3085 Fix host port validation to properly respect 'disabled'
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
Labels: docs-pr-required, release-note-required

#3086 Fix CA secret name for no-tenant vs single-tenant vs multi-tenant
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3061 EV-4475 Resource config for Manager and PolicyRec
  api/v1/manager_types.go
  api/v1/policyrecommendation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#3054 Remove curator
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/controller/logstorage/linseed/linseed_controller_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/render/common/elasticsearch/decorator.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage_test.go
  pkg/render/testutils/expected_policies/elastic-curator.json
  pkg/render/testutils/expected_policies/elastic-curator_ocp.json
  pkg/render/testutils/expected_policies/es-gateway.json
  pkg/render/testutils/expected_policies/es-gateway_ocp.json
  pkg/render/testutils/expected_policies/linseed.json
  pkg/render/testutils/expected_policies/linseed_dpi_enabled.json
  pkg/render/testutils/expected_policies/linseed_ocp.json
  pkg/render/testutils/expected_policies/linseed_ocp_dpi_enabled.json
Labels: docs-pr-required, release-note-required

#3089 [Cherry-pick] Fix CA secret name for no-tenant vs single-tenant vs multi-tenant
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3094 Update CRDs: FelixConfigurations
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3101 Update golang/x/crypto
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready

#3099 [1.32] Update base image and crypto
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready

#3098 [1.31] Update base image and crypto
  build/Dockerfile.amd64
  build/Dockerfile.arm64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready

#3093 Set tenant claim to be the id of the tenant
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#3108 run make gen-versions
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3110 Automated cherry pick of #3107: Update coreos stack to reduce CVEs
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#3107 Update coreos stack to reduce CVEs
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#3100 [1.33] Update golang/x/crypto
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready

#3109 Automated cherry pick of #3107: Update coreos stack to reduce CVEs
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#3087 fix CNI plugin configuration issue
  pkg/controller/migration/convert/network.go
  pkg/controller/migration/convert/network_test.go
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#3096 Intrusion detection forwarder needs permission to snapshot its state
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3112 PolicyRecommendation should enqueue global resource watched object ch…
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3115 [RS-1691] Webhooks-controller should now be rendered on management clusters.
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3106 [cherrypick] [RS-1614] Webhooks should be able to watch config maps and secrets for changes.
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3119 Revert bad FLOW_LOG_FILE fluentd env var Windows fix
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: release-note-not-required, docs-not-required

#3116 Fix unset linseed url. When missing, clusters with clusterDomain set …
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3121 Automate updating operator version for release (#2958)
  Makefile
  RELEASING.md
  hack/gen-versions/main.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch, squash-commits

#3125 Automated cherry pick of #3124: Fix unset linseed url. When missing, clusters with
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3124 Automated cherry pick of #3123: Fix unset linseed url. When missing, clusters with
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3123 Fix unset linseed url. When missing, clusters with clusterDomain set …
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3122 Automated cherry pick of #3116: Fix unset linseed url. When missing, clusters with
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3120 Support zeroed kube-controllers metric port
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/testutils/expected_policies/prometheus.json
  pkg/render/testutils/expected_policies/prometheus_ocp.json
Labels: docs-pr-required, release-note-required

#3127 Add tigera operator scheme to the unit tests for authn.
  pkg/controller/utils/auth_test.go
Labels: docs-pr-required, release-note-required

#3128 Fix panic that can be caused when removing the logstorage resource.
  pkg/controller/logstorage/esmetrics/esmetrics_controller.go
Labels: docs-pr-required, release-note-required

#3126 Bump Elasticsearch and Kibana versions to v7.17.16
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3129 Automated cherry pick of #3128: Fix panic that can be caused when removing the logstorage
  pkg/controller/logstorage/esmetrics/esmetrics_controller.go
Labels: docs-pr-required, release-note-required

#3102 Update tigera-apiserver probes
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3130 Report TigeraStatus for tiers
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/logcollector/logcollector_controller.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/esmetrics/esmetrics_controller.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/migration/convert/network_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/tiers/tiers_controller_test.go
  pkg/controller/utils/test_utils.go
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
Labels: docs-pr-required, release-note-required

#3134 [release-v1.32] Auto Release Update for v1.32.4
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/common.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3117 [cherrypick] [RS-1691] Webhooks-controller should now be rendered on management clusters.
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3139 Ensure degraded status is cleared for tiers controller
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/tiers/tiers_controller_test.go
Labels: docs-pr-required, release-note-required

#3133 [v1.32] Support zeroed kube-controllers metric port
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/testutils/expected_policies/prometheus.json
  pkg/render/testutils/expected_policies/prometheus_ocp.json
Labels: docs-pr-required, release-note-required

#3132 [v1.31] Support zeroed kube-controllers metric port
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/testutils/expected_policies/prometheus.json
  pkg/render/testutils/expected_policies/prometheus_ocp.json
Labels: docs-pr-required, release-note-required

#3131 [v1.30] Support zeroed kube-controllers metric port
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/testutils/expected_policies/prometheus.json
  pkg/render/testutils/expected_policies/prometheus_ocp.json
Labels: docs-pr-required, release-note-required

#3138 Compliance multi-tenancy follow-up commits to normalize networkpolicy…
  pkg/controller/compliance/compliance_controller.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/guardian.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/manager.go
Labels: release-note-not-required, docs-not-required

#3135 Fix trusted-bundle conflict in ES secret controller
  api/v1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  hack/boilerplate.go.txt
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/common.go.tpl
  hack/gen-versions/components.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/common/components.go
  pkg/components/calico.go
  pkg/components/common.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/controller/secrets/tenant_controller.go
  pkg/controller/secrets/tenant_controller_test.go
  pkg/controller/utils/namespace_helper.go
  pkg/render/common/test/testing.go
Labels: docs-pr-required, release-note-required

#2747 [cherry-pick] pull request #2741 from lwr20/lwr-op-bundle-upd
  hack/gen-bundle/get-manifests.sh
  hack/gen-bundle/update-bundle.sh
Labels: release-note-required, docs-not-required

#2748 [cherry-pick] pull request #2741 from lwr20/lwr-op-bundle-upd
  hack/gen-bundle/get-manifests.sh
  hack/gen-bundle/update-bundle.sh
Labels: release-note-required, docs-not-required

#3118 Consolidate tigera status for all log storage controllers
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/elastic/external_elastic_controller.go
  pkg/controller/logstorage/esmetrics/esmetrics_controller.go
  pkg/controller/logstorage/initializer/conditions_controller.go
  pkg/controller/logstorage/initializer/conditions_controller_test.go
  pkg/controller/logstorage/initializer/initializing_controller.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/users/users_controller.go
Labels: docs-pr-required, release-note-required

#3137 Migrate job installer to run inside elasticsearch namespace
  api/v1/dashboards_job_types.go
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  controllers/logstorage_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/dashboards/dashboards_controller.go
  pkg/controller/logstorage/dashboards/dashboards_controller_test.go
  pkg/controller/logstorage/dashboards/dashboards_suite_test.go
  pkg/controller/logstorage/initializer/conditions_controller.go
  pkg/controller/logstorage/initializer/conditions_controller_test.go
  pkg/controller/logstorage/initializer/initializing_controller.go
  pkg/controller/logstorage/users/users_controller.go
  pkg/controller/logstorage/users/users_controller_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/common/components/components.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/dashboards/dashboards.go
  pkg/render/logstorage/dashboards/dashboards_suite_test.go
  pkg/render/logstorage/dashboards/dashboards_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/testutils/expected_policies/dashboards.json
  pkg/render/testutils/expected_policies/dashboards_ocp.json
  pkg/render/testutils/expected_policies/kibana.json
  pkg/render/testutils/expected_policies/kibana_ocp.json
  pkg/render/testutils/expected_policies/linseed.json
  pkg/render/testutils/expected_policies/linseed_dpi_enabled.json
  pkg/render/testutils/expected_policies/linseed_ocp.json
  pkg/render/testutils/expected_policies/linseed_ocp_dpi_enabled.json
Labels: docs-pr-required, release-note-required

#3143 Dex binary changed location inside of Dockerfile
  pkg/render/dex.go
Labels: docs-pr-required, release-note-required

#3145 Fix the Compliance namespace in Voltron's proxy targets
  pkg/controller/manager/manager_controller.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#3148 [release-v1.33] Auto Release Update for v1.33.0
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/common.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  hack/gen-versions/main.go
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3136 Update intrusion detection for multi-tenancy
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/migration/convert/network_test.go
  pkg/controller/utils/auth_test.go
  pkg/render/common/test/testing.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/testutils/expected_policies/intrusion-detection-controller_unmanaged.json
  pkg/render/testutils/expected_policies/intrusion-detection-controller_unmanaged_ocp.json
Labels: release-note-not-required, docs-not-required

#3144 Update envoy config template
  pkg/render/applicationlayer/envoy-config.yaml.template
Labels: docs-pr-required, release-note-required
