Repository tigera/operator, pull requests merged in 2024-10, with the labels that each got.

#3286 Update generate-release-notes.py to only include release-note-required label [v1.34]
  generate-release-notes.py
Labels: release-note-not-required, docs-not-required

#3520 Adding X-Frames-Options DENY header for Kibana (#3516)
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_test.go
Labels: docs-pr-required, release-note-required

#3464 Remove Job + SA when it is a managed cluster. Only render SA if Job i…
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3455 Remove FIPS mode for enterprise users. It is no longer supported.
  api/v1/installation_types.go
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/initializer/initializing_controller.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/crypto_utils.go
  pkg/render/dex.go
  pkg/render/guardian.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/dashboards/dashboards.go
  pkg/render/logstorage/dashboards/dashboards_test.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#3536 Regenerate CRDs.
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3537 [v1.36] Regenerate CRDs
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/policy.networking.k8s.io_adminnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/policy.networking.k8s.io_adminnetworkpolicies.yaml
Labels: release-note-not-required, docs-not-required

#3539 Fix Installation API comment
  api/v1/installation_types.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: docs-pr-required, release-note-not-required

#3541 [release-v1.35] Auto pick #3539: Fix Installation API comment
  api/v1/installation_types.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: docs-pr-required, release-note-not-required

#3540 [release-v1.36] Auto pick #3539: Fix Installation API comment
  api/v1/installation_types.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: docs-pr-required, release-note-not-required

#3543 Introdoces SidecarWebhook status
  api/v1/applicationlayer_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/common/common.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
  pkg/crds/enterprise/policy.networking.k8s.io_adminnetworkpolicies.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#3545 [RS-2143] Reducing DPI readiness initial delay 90s -> 10s.
  pkg/render/intrusiondetection/dpi/dpi.go
Labels: docs-pr-required, release-note-required

#3549 Automated cherry pick of #3548: Update ES&KB to v7.17.24.
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3551 [RS-2143] [cherry-pick v1.36] Reducing DPI readiness initial delay 90s -> 10s.
  pkg/render/intrusiondetection/dpi/dpi.go
Labels: docs-pr-required, release-note-required

#3547 Release v1.36 cherrypick applicationlayer status sidecarwebhook
  api/v1/applicationlayer_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/common/common.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#3552 Removes Host Numeric rule from coreruleset
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/applicationlayer/embed/coreruleset/tigera.conf
Labels: docs-pr-required, release-note-required, merge-when-ready

#3553 Removes Host Numeric rule from coreruleset
  pkg/render/applicationlayer/embed/coreruleset/tigera.conf
Labels: docs-pr-required, release-note-required

#3544 Add tolerations for arm64 workloads on GKE
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/meta/meta.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/dashboards/dashboards.go
  pkg/render/logstorage/dashboards/dashboards_test.go
  pkg/render/logstorage/eck/eck.go
  pkg/render/logstorage/eck/eck_test.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required

#3554 [release-v1.36] Add tolerations for arm64 workloads on GKE
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/meta/meta.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/dashboards/dashboards.go
  pkg/render/logstorage/dashboards/dashboards_test.go
  pkg/render/logstorage/eck/eck.go
  pkg/render/logstorage/eck/eck_test.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3548 Update ES&KB to v7.17.24.
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3555 Auto build updates v1.34.6
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3530 [Pick #3489] Use restricted namespace for opensource calico-apiserver (v1.36)
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required

#3556 Set "system-node-critical" priority on calico-node-windows pods
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#3557 [release-v1.36] Auto pick #3556: Set "system-node-critical" priority on
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: release-note-required, docs-not-required

#3558 [release-v1.35] Auto pick #3556: Set "system-node-critical" priority on
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: release-note-required, docs-not-required

#3559 [release-v1.34] Auto pick #3556: Set "system-node-critical" priority on
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: release-note-required, docs-not-required

#3560 [release-v1.32] Auto pick #3556: Set "system-node-critical" priority on
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: release-note-required, docs-not-required

#3562 Upgrade es,kb to 7.17.25 for 320 cve
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3561 cherry-pick #3562 Upgrade es,kb to 7.17.25 for 320 cve
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3535 Ensure external certs have a hash
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/render/apiserver_test.go
  pkg/tls/certificatemanagement/certificatebundle.go
Labels: docs-pr-required, release-note-required

#3565 Upgrade es,kb to 7.17.25 for 320 cve
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3570 [RS-2165] Webhooks updates for 3.20 EP1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3571 [EV-5299] Disable Policy Recommendation for Windows OS
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3572 [EV-5299] Disable Policy Recommendation for Windows OS
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3568 [EV-5299] Disable Policy Recommendation for Windows OS
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3563 [EV-5299] Disable Policy Recommendation for Windows OS
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3564 Add VadlidatingAdmissionPolicy RBAC and bump k8s to v1.30 release
  Makefile
  api/v1/monitor_types.go
  api/v1/zz_generated.deepcopy.go
  deploy/crds/elastic/agent-crd.yaml
  deploy/crds/elastic/apmserver-crd.yaml
  deploy/crds/elastic/beat-crd.yaml
  deploy/crds/elastic/elasticmapsservers.yaml
  deploy/crds/elastic/elasticsearch-crd.yaml
  deploy/crds/elastic/enterprisesearch-crd.yaml
  deploy/crds/elastic/kibana-crd.yaml
  go.mod
  go.sum
  main.go
  pkg/common/k8svalidation/helper/helper.go
  pkg/common/k8svalidation/validation.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/controller/monitor/monitor_controller_test.go
  pkg/controller/secrets/tenant_controller_test.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/crds/operator/operator.tigera.io_tlsterminatedroutes.yaml
  pkg/ctrlruntime/controller.go
  pkg/render/apiserver.go
  pkg/render/common/secret/secrets.go
  pkg/render/common/test/testing.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required

#3443 the calico-apiserver namespace frequently get stuck for a long time in terminating status when upgrading to enterprise - v1.34 pick of (#3439)
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
Labels: docs-pr-required, release-note-required

#3529 [Pick #3489] Use restricted namespace for opensource calico-apiserver (v1.35)
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3528 [Pick #3489] Use restricted namespace for opensource calico-apiserver (v1.34)
  pkg/render/apiserver.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3575 Revert "[EV-5299] Disable Policy Recommendation for Windows OS"
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3578 [release-v1.36] Auto Release Update for v1.36.0
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#3574 Revert "[EV-5299] Disable Policy Recommendation for Windows OS"
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3573 Revert "[EV-5299] Disable Policy Recommendation for Windows OS"
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3576 Remove custom cache option when creating controller manager
  Makefile
  main.go
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
Labels: docs-pr-required, release-note-required

#3581 Update EGW status only if it has changed
  pkg/controller/egressgateway/egressgateway_controller.go
Labels: docs-pr-required, release-note-required

#3579 Update EGW status only if it has changed - v1.36
  pkg/controller/egressgateway/egressgateway_controller.go
Labels: release-note-not-required, docs-not-required

#3580 Update EGW status only if it has changed - [v1.34]
  pkg/controller/egressgateway/egressgateway_controller.go
Labels: docs-pr-required, release-note-required
