Repository tigera/operator, pull requests merged in 2024-03, with the labels that each got.

#3215 Voltron and/or es-proxy should have kibana's certificate in the bundl…
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required

#3218 Automated cherry pick of #3217: Voltron and/or es-proxy should have kibana's certificate
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required

#3220 Automated cherry pick of #3175: Decrease the validity of JWTs issued by Dex to 15m
  pkg/render/dex.go
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3213 ev-4711 1.32 update elastic stack versions
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3212 ev-4711 1.30 update elastic stack versions
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3211 Update elastic stack versions
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3186 Adds PolicySetupTimeoutSeconds option to CalicoNetwork
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/controller/utils/merge.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3219 Automated cherry pick of #3175: Decrease the validity of JWTs issued by Dex to 15m
  pkg/render/dex.go
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3221 Make test variable private that didn't need to be public
  pkg/controller/installation/defaults_test.go
Labels: release-note-not-required, docs-not-required

#3225 EV-4693 Make resource requests/limits configurable for tigera-guardian
  api/v1/guardian_deployment_types.go
  api/v1/managementclusterconnection_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/render/guardian.go
  pkg/render/guardian_test.go
Labels: docs-pr-required, release-note-required

#3222 Fix features annotations
  hack/gen-bundle/update-bundle.sh
Labels: docs-pr-required, release-note-required, merge-when-ready

#3166 refactor: set kube network based on cni type instead of provider
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: release-note-required, docs-not-required

#3228 Prevent the operator from starting in namespaces it manages
  main.go
Labels: release-note-not-required, docs-not-required

#3227 refactor: set kube network based on cni type instead of provider (#3166)
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#3142 Deploy es-kube-controllers in a multi-tenant environment
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#3230 Allow to access managed service per tenant
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#3232 Update libs to patch CVEs
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3233 Update libs to patch CVEs
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3184 Remove auth that was not supported since ee v3.4
  api/v1/manager_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/manager/manager_controller.go
  pkg/crds/operator/operator.tigera.io_managers.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3231 [Addendum] Dashboards Controller needs to know when elastic is extern…
  pkg/controller/logstorage/dashboards/dashboards_controller.go
Labels: docs-pr-required, release-note-required

#3205 EV-4687 Make resource request/limits configurable for dex,IDC
  api/v1/authentication_types.go
  api/v1/dex_deployment_types.go
  api/v1/intrusiondetection_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/components/resources.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/tls/certificatemanagement/csr.go
Labels: docs-pr-required, release-note-required

#3236 Remove bpf dual stack validation
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3238 Disable keep alive for the elasticsearch client
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#3239 [release-v1.32] Auto pick #3238: Disable keep alive for the elasticsearch client
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#3237 remove orphaned file
  pkg/render/applicationlayer/embed/coreruleset/unicode.mapping
  pkg/render/applicationlayer/embed/embed_test.go
Labels: docs-pr-required, release-note-required

#3240 Revert "Voltron and/or es-proxy should have kibana's certificate in t…
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3241 [release-v1.30] Auto Release Update for v1.30.10
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/common.go.tpl
  hack/gen-versions/enterprise.go.tpl
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3207 EV-4691 make logstorage components configurable for resource requests…
  api/v1/elasticsearchmetric_types.go
  api/v1/logstorage_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/logstorage/esmetrics/esmetrics_controller.go
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#3209 EV-4687 Make compliance components configurable - resource requests/l…
  api/v1/benchmarker_types.go
  api/v1/compliance_controller_types.go
  api/v1/compliance_reporter_types.go
  api/v1/compliance_server_types.go
  api/v1/compliance_types.go
  api/v1/snapshotter_deployment_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/compliance/compliance_controller.go
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/render/common/components/components.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#3206 Logcollector - Make resource requests/limits configurable
  api/v1/eks_logforwarder_types.go
  api/v1/fluentd_daemonset_types.go
  api/v1/logcollector_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
Labels: docs-pr-required, release-note-required

#3199 Configure voltron routes with TLS Route CRs
  api/v1/tlsroute.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/manager/manager_controller.go
  pkg/crds/operator/operator.tigera.io_tlspassthroughroutes.yaml
  pkg/crds/operator/operator.tigera.io_tlsterminatedroutes.yaml
  pkg/render/manager.go
  pkg/render/manager/manager_route_config.go
  pkg/render/manager/manager_route_config_test.go
  pkg/render/manager/manager_suite_test.go
Labels: docs-pr-required, release-note-required

#3234 Update libs to patch CVEs
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3243 update version for v3.28
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required

#3244 Fix cherry-pick pr3198
  api/v1/dashboards_job_types.go
  api/v1/linseed_deployment_types.go
  api/v1/zz_generated.deepcopy.go
Labels: docs-pr-required, release-note-required

#3246 Fix cherry-pick pr3197
  api/v1/dashboards_job_types.go
  api/v1/linseed_deployment_types.go
  api/v1/zz_generated.deepcopy.go
Labels: docs-pr-required, release-note-required

#3247 Fix cherry-pick pr3195
  api/v1/calico_node_windows_types.go
  api/v1/dashboards_job_types.go
  api/v1/linseed_deployment_types.go
  api/v1/zz_generated.deepcopy.go
Labels: docs-pr-required, release-note-required

#3248 Fix cherry-pick pr3194
  api/v1/calico_node_windows_types.go
  api/v1/dashboards_job_types.go
  api/v1/linseed_deployment_types.go
  api/v1/zz_generated.deepcopy.go
Labels: docs-pr-required, release-note-required

#3242 Add container name in comments for Deployments,daemonset and other re…
  api/v1/apiserver_types.go
  api/v1/benchmarker_types.go
  api/v1/calico_kubecontrollers_types.go
  api/v1/calico_node_types.go
  api/v1/calico_node_windows_types.go
  api/v1/compliance_controller_types.go
  api/v1/compliance_reporter_types.go
  api/v1/compliance_server_types.go
  api/v1/csi_node_driver.go
  api/v1/dashboards_job_types.go
  api/v1/dex_deployment_types.go
  api/v1/eckoperator_types.go
  api/v1/egressgateway_types.go
  api/v1/eks_logforwarder_types.go
  api/v1/elasticsearchmetric_types.go
  api/v1/fluentd_daemonset_types.go
  api/v1/guardian_deployment_types.go
  api/v1/intrusiondetection_types.go
  api/v1/kibana_types.go
  api/v1/l7_logcollector_types.go
  api/v1/linseed_deployment_types.go
  api/v1/manager_types.go
  api/v1/monitor_types.go
  api/v1/policyrecommendation_types.go
  api/v1/snapshotter_deployment_types.go
  api/v1/typha_deployment_types.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
Labels: docs-pr-required, release-note-required

#3250 Cherry-pick #3242 Add container name in comments for Deployments,daemonset and other re
  api/v1/apiserver_types.go
  api/v1/benchmarker_types.go
  api/v1/calico_kubecontrollers_types.go
  api/v1/calico_node_types.go
  api/v1/calico_node_windows_types.go
  api/v1/compliance_controller_types.go
  api/v1/compliance_reporter_types.go
  api/v1/compliance_server_types.go
  api/v1/csi_node_driver.go
  api/v1/dashboards_job_types.go
  api/v1/dex_deployment_types.go
  api/v1/eckoperator_types.go
  api/v1/egressgateway_types.go
  api/v1/eks_logforwarder_types.go
  api/v1/elasticsearchmetric_types.go
  api/v1/fluentd_daemonset_types.go
  api/v1/guardian_deployment_types.go
  api/v1/intrusiondetection_types.go
  api/v1/kibana_types.go
  api/v1/l7_logcollector_types.go
  api/v1/linseed_deployment_types.go
  api/v1/manager_types.go
  api/v1/monitor_types.go
  api/v1/policyrecommendation_types.go
  api/v1/snapshotter_deployment_types.go
  api/v1/typha_deployment_types.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
Labels: docs-pr-required, release-note-required

#3254 Fix CSI node driver resource config
  api/v1/csi_node_driver.go
  pkg/common/validation/csi-node-driver/validation.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required

#3255 [release-v1.34] Auto pick #3254: Fix setting of resources for the CSI node driver
  api/v1/csi_node_driver.go
  pkg/common/validation/csi-node-driver/validation.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required

#3256 [release-v1.33] Auto pick #3254: Fix setting of resources for the CSI node driver
  api/v1/csi_node_driver.go
  pkg/common/validation/csi-node-driver/validation.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required

#3252 [RS-1725] Allow intrusion-detection-controller to read alert exceptions
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3257 [RS-1725] Allow intrusion-detection-controller to read alert exceptions (#3252)
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3258 Relax IPAM check in core controller
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#3260 [release-v1.34] Auto pick #3258: Relax IPAM check in core controller
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3245 Fix secret not available messages
  pkg/controller/logstorage/secrets/secret_controller.go
Labels: docs-pr-required, release-note-required

#3263 Automated cherry pick of #3245: Fix secret not available messages
  pkg/controller/logstorage/secrets/secret_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3264 Build updates Enterprise v3.18.2
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3267 Update the projectcalico resources
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3266 Move Encapsulation validation into IP pool controller
  pkg/controller/installation/validation.go
  pkg/controller/ippool/pool_controller_test.go
  pkg/controller/ippool/validation.go
Labels: docs-pr-required, release-note-required

#3268 [release-v1.34] Auto pick #3266: Move Encapsulation validation into IP pool controller
  pkg/controller/installation/validation.go
  pkg/controller/ippool/pool_controller_test.go
  pkg/controller/ippool/validation.go
Labels: docs-pr-required, release-note-required

#3269 Make monitor controller aware that there are multi tenant options
  pkg/controller/monitor/monitor_controller.go
Labels: docs-pr-required, release-note-required

#3272 Remove unnecessary code block
  pkg/controller/monitor/monitor_controller.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3270 Switch the prometheus backoff to use Ticker
  pkg/controller/monitor/prometheus.go
Labels: docs-pr-required, release-note-required

#3273 Switch the backoff to use Ticker [pick #3270 release-1.34]
  pkg/controller/monitor/prometheus.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3208 Move test utilities to test package fromt utils folder to move ginkgo v1 import
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logcollector/logcollector_controller_test.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/monitor/monitor_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/controller/utils/test_utils.go
  test/utils.go
Labels: docs-pr-required, release-note-required

#3274 [cherry-pick] [1.34] Make monitor controller aware that there are multi tenant options (#3…
  pkg/controller/monitor/monitor_controller.go
Labels: docs-pr-required, release-note-required
