Repository tigera/operator, pull requests merged in 2024-08, with the labels that each got.

#3451 [release-v1.35] Auto Release Update for v1.35.0
  config/calico_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/main.go
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3452 Improve OpenShift platform detection accuracy
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
Labels: release-note-required, docs-not-required

#3453 Print image options and ImageSet utility
  Makefile
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/enterprise.go.tpl
  main.go
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/images_test.go
  pkg/components/references.go
Labels: release-note-required, docs-not-required

#3454 Tenant fail to clean up because of missing connection to Elasticsearch
  pkg/controller/logstorage/users/users_controller.go
Labels: release-note-not-required, docs-not-required

#3456 [cherry-pick][v1.35]Tenant fail to clean up because of missing connection to Elasticsearc…
  pkg/controller/logstorage/users/users_controller.go
Labels: docs-pr-required, release-note-required

#3457 Bump es/kb to fix CVEs
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3458 [EV-5126] Rename and update tigera-crds clusterrole
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3462 Switch to new machine type in semaphore CI
  .semaphore/clean_up.yml
  .semaphore/clear_cache.yml
  .semaphore/push_images.yml
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#3463 Switch to new machine type in semaphore CI [pick 3462 r1.35]
  .semaphore/clean_up.yml
  .semaphore/clear_cache.yml
  .semaphore/push_images.yml
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#3466 Make capitalization of Dockerfile keywords consistent
  build/Dockerfile
Labels: docs-pr-required, release-note-required

#3467 Switch to f1 machine type in Sem
  .semaphore/clean_up.yml
  .semaphore/clear_cache.yml
  .semaphore/push_images.yml
  .semaphore/semaphore.yml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3468 Automatic version updates for v1.32.11 release
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3465 [RS-2023] Change services permissions to deployments permissions
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3471 Switch to new machine type in semaphore CI [v1.34]
  .semaphore/clean_up.yml
  .semaphore/clear_cache.yml
  .semaphore/push_images.yml
  .semaphore/semaphore.yml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3476 Render DPI RBAC to access Linseed
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#3474 Update RBACs for tier support in Calico OSS
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_tiers.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/node.go
  pkg/render/typha.go
Labels: docs-pr-required, release-note-required

#3478 Render DPI RBAC to access Linseed for multi-tenat management clusters
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
Labels: docs-pr-required, release-note-required

#3473 [RS-2023] Add back services RBAC permissions
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3472 Add IP pool config to disable new allocations
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/ippool/defaults.go
  pkg/controller/ippool/pool_controller.go
  pkg/controller/ippool/pool_controller_test.go
  pkg/controller/ippool/pool_conversion_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: docs-pr-required, release-note-required

#3479 [v1.34] Update ES and KB versions
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3482 [release-v1.30] Auto Release Update for v1.30.11
  .semaphore/clean_up.yml
  .semaphore/clear_cache.yml
  .semaphore/push_images.yml
  .semaphore/semaphore.yml
  config/calico_versions.yml
  config/common_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/main.go
  pkg/components/calico.go
  pkg/components/common.go
Labels: release-note-not-required, docs-not-required

#3484 Add hostendpoints get and list to tigera ui and admin users
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required
