Repository tigera/operator, pull requests merged in 2024-05, with the labels that each got.

#3337 Update prometheus operator permissions to v0.73.2
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required

#3309 [release-v1.33][cherry-pick] Fix security-context for apiserver - audit logs are supported only in Enterprise version
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3308 [release-v1.32][cherry-pick] Fix security-context for apiserver - audit logs are supported only in Enterprise version
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3341 Restore Labels and Annotations before parsing v1 pools
  pkg/controller/ippool/pool_controller.go
Labels: release-note-not-required, docs-not-required

#3343 [release-v1.34] Auto pick #3341: Restore original v3 Labels and Annotations in IP pool
  pkg/controller/ippool/pool_controller.go
Labels: release-note-not-required, docs-not-required

#3332 [REFACTOR] Kibana and ECK will have their own renderer
  main.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/logstorage/dashboards/dashboards_controller.go
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/controller/logstorage/elastic/external_elastic_controller_test.go
  pkg/controller/logstorage/initializer/initializing_controller.go
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/crds/enterprise/usage.tigera.io_licenseusagereports.yaml
  pkg/render/logstorage.go
  pkg/render/logstorage/dashboards/dashboards.go
  pkg/render/logstorage/dashboards/dashboards_test.go
  pkg/render/logstorage/eck/eck.go
  pkg/render/logstorage/eck/eck_suite_test.go
  pkg/render/logstorage/eck/eck_test.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_suite_test.go
  pkg/render/logstorage/kibana/kibana_test.go
  pkg/render/logstorage_test.go
  pkg/render/tiers/tiers_test.go
Labels: docs-pr-required, release-note-required

#3342 EV-4824 update useraccess for compliance, intrusiondetection and pack…
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3333 Clean up es proxy for ELASTIC environment variables
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: docs-pr-required, release-note-required

#3346 Update kube-controllers for license usage collection
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#3349 set mount type to DirectoryOrCreate for hostPath needed by Calico
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#3350 [release-v1.34] Auto Release Update for v1.34.0
  Makefile
  config/calico_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/main.go
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/components/images.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3352 Force a Linseed restart when the credentials to connect to Elastic change
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#3354 Handle packetcapture dependency with guardian
  pkg/controller/clusterconnection/clusterconnection_controller.go
Labels: docs-pr-required, release-note-required

#3355 [cherry-pick] [v1.34] Force a Linseed restart when the credentials to connect to Elastic ch…
  pkg/controller/logstorage/linseed/linseed_controller.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
Labels: docs-pr-required, release-note-required

#3358 [Release v1.34] set mount type to DirectoryOrCreate for hostPath needed by Calico
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#3359 [Release v1.33] set mount type to DirectoryOrCreate for hostPath needed by Calico
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#3360 [Release v1.32] set mount type to DirectoryOrCreate for hostPath needed by Calico
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/windows.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#3363 remove default creation of tigera-dex namespace
  pkg/controller/authentication/authentication_controller.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#3362 [v1.34] License Usage Collection
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#3369 v1.34 pick: Limit TLSRoute lists to the tenant namespace in multi-tenant clusters (#3367)
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: docs-pr-required, release-note-required

#3361 Add RBAC for linseed managedcluster informer
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required
