Repository tigera/operator, pull requests merged in 2024-07, with the labels that each got.

#3399 CSI DaemonSet no longer uses the "default" ServiceAccount
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: release-note-required, docs-not-required

#3397 [cherry-pick][v1.35] Port creating an MTLS client for ElasticSearch (#3395)
  pkg/controller/logstorage/elastic/elastic_controller.go
  pkg/controller/logstorage/elastic/mock.go
  pkg/controller/logstorage/users/users_controller.go
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#3396 [cherry-pick][v1.35] Switch to ClusterRole/RoleBindings to get ManagedClusters to pass aut…
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#3402 Ci 1558 3.18
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/monitor/monitor_controller_test.go
Labels: docs-pr-required, release-note-required

#3401 [TSLA-7094] (Cherry-pick) Rearrange multi-tenant UTs so they're not longer subset of single-ten…
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3406 CI-1558 Automated cherry pick of #3404: Fix deadlock situation where two controller rely on the
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/monitor/monitor_controller_test.go
Labels: docs-pr-required, release-note-required

#3405 CI-1558 Automated cherry pick of #3404: Fix deadlock situation where two controller rely on the
  pkg/controller/logstorage/secrets/secret_controller.go
  pkg/controller/logstorage/secrets/secret_controller_test.go
  pkg/controller/monitor/monitor_controller.go
  pkg/controller/monitor/monitor_controller_test.go
Labels: docs-pr-required, release-note-required

#3407 Fix! External Elastic client should use external certificate
  pkg/controller/utils/elasticsearch.go
Labels: docs-pr-required, release-note-required

#3403 Create namespace before certificates
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3408 [cherry-pick][v1.35] Cherry-pick intrusion detection multi-tenant aware and elastic client creation fixes
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/utils/elasticsearch.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/logstorage/linseed/linseed.go
Labels: docs-pr-required, release-note-required

#3409 Do not default to elastic username for external elastic and read it f…
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/elasticsearch_test.go
Labels: docs-pr-required, release-note-required

#3410 [cherry-pick][1.35]Do not default to elastic username for external elastic and read it f…
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/elasticsearch_test.go
Labels: docs-pr-required, release-note-required

#3411 Bind all tenants service account for compliance server cluster role
  pkg/controller/compliance/compliance_controller.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#3416 [ev-5047] Change dashboard name for redirecting users after login.
  pkg/render/logstorage/kibana/kibana.go
Labels: docs-pr-required, release-note-required

#3417 Fix missing error message in tigerastatus object.
  pkg/controller/logstorage/elastic/elastic_controller.go
Labels: docs-pr-required, release-note-required

#3421 Automated cherry pick of #3417: Fix missing error message in tigerastatus object.
  pkg/controller/logstorage/elastic/elastic_controller.go
Labels: docs-pr-required, release-note-required

#3422 Automated cherry pick of #3416: Change dashboard name for redirecting users after login.
  pkg/render/logstorage/kibana/kibana.go
Labels: docs-pr-required, release-note-required

#3414 [cherry-pick][v1.35]Bind all tenants service account for compliance server cluster role
  pkg/controller/compliance/compliance_controller.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#3415 Automatic version updates for v1.32.10 release
  config/calico_versions.yml
  config/common_versions.yml
  pkg/components/calico.go
  pkg/components/common.go
Labels: release-note-not-required, docs-not-required

#3423 Configure resources for es-kube-controllers via the tenant CR
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#3425 [cherry-pick][v1.35] Configure resources for es-kube-controllers via the tenant CR (#3423)
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#3424 Relax ImageSet validation
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/secrets/cluster_ca_controller.go
  pkg/controller/secrets/cluster_ca_controller_test.go
  pkg/controller/utils/imageset/imageset.go
  pkg/controller/utils/imageset/imageset_test.go
Labels: docs-pr-required, release-note-required

#3426 [Pick #3424] Relax ImageSet validation (r1.35)
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/secrets/cluster_ca_controller.go
  pkg/controller/secrets/cluster_ca_controller_test.go
  pkg/controller/utils/imageset/imageset.go
  pkg/controller/utils/imageset/imageset_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#3427 [Pick #3424] Relax ImageSet validation (r1.34)
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/secrets/cluster_ca_controller.go
  pkg/controller/secrets/cluster_ca_controller_test.go
  pkg/controller/utils/imageset/imageset.go
  pkg/controller/utils/imageset/imageset_test.go
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#3430 Add es kube controllers as containers
  api/v1/calico_kubecontrollers_types.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
Labels: docs-pr-required, release-note-required

#3433 [cherry-pick][v1.35] Add es kube controllers as containers (#3430)
  api/v1/calico_kubecontrollers_types.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
Labels: docs-pr-required, release-note-required

#3434 Bind all tenants to linseed RBAC
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#3437 [cherry-pick][v1.35]Bind all tenants to linseed RBAC (#3434)
  pkg/render/compliance.go
  pkg/render/compliance_test.go
Labels: docs-pr-required, release-note-required

#3435 Set default values for vxlanVNI and BPFHostConntrackBypass for DockerEE
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/bpf.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-pr-required, release-note-required

#3441 Set default values for vxlanVNI and BPFHostConntrackBypass for Docker…
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/bpf.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-pr-required, release-note-required

#3442 Set default values for vxlanVNI and BPFHostConntrackBypass for Docker…
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/installation/bpf.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: docs-pr-required, release-note-required

#3438 [EV-5062] set calico version
  config/calico_versions.yml
  pkg/components/calico.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#3439 the calico-apiserver namespace frequently get stuck for a long time in terminating status when upgrading to enterprise
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
Labels: docs-pr-required, release-note-required

#3444 the calico-apiserver namespace frequently get stuck for a long time in terminating status when upgrading to enterprise - v1.35 pick of (#3439)
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
Labels: docs-pr-required, release-note-required

#3447 [v1.30] Update go-build to v0.89
  Makefile
Labels: release-note-required, docs-not-required

#3448 [1.30] Update x/net to v0.27.0
  go.mod
  go.sum
Labels: release-note-required, docs-not-required, merge-when-ready, delete-branch

#3449 [release-v1.34] Auto Release Update for v1.34.3
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch
