Repository tigera/operator, pull requests merged in 2024-04, with the labels that each got.

#2906 Fix security-context for apiserver - audit logs are supported only in Enterprise version
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3251 Remove special key-cert-provisioner image code, now that it is in the…
  Makefile
  RELEASING.md
  config/calico_versions.yml
  config/common_versions.yml
  config/enterprise_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/common.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  main.go
  pkg/components/calico.go
  pkg/components/common.go
  pkg/components/enterprise.go
  pkg/components/images.go
  pkg/components/images_test.go
  pkg/components/references.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager.go
  pkg/controller/certificatemanager/certificatemanager_suite_test.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows_controller_test.go
  pkg/controller/utils/imageset/imageset.go
  pkg/render/csi.go
  pkg/render/csi_test.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/tls/certificatemanagement/csr.go
Labels: docs-pr-required, release-note-required

#3265 EV-4646 deprecate AWS SG integeration
  api/v1/amazoncloudintegration_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1beta1/amazoncloudintegration_types.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/zz_generated.deepcopy.go
  config/samples/operator_v1_amazoncloudintegration.yaml
  controllers/amazoncloudintegration_controller.go
  controllers/controllers.go
  docs/controller-dependency-graph.svg
  docs/generate-controller-dependency-graph.py
  git-hooks/files-to-skip
  go.mod
  go.sum
  main.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_controller_test.go
  pkg/controller/amazoncloudintegration/amazoncloudintegration_suite_test.go
  pkg/controller/amazoncloudintegration/validation.go
  pkg/controller/amazoncloudintegration/validation_test.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows_controller.go
  pkg/controller/installation/windows_controller_test.go
  pkg/controller/options/options.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_amazoncloudintegrations.yaml
  pkg/render/amazoncloudintegration.go
  pkg/render/amazoncloudintegration_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/manager.go
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render_test.go
  pkg/render/typha.go
  pkg/render/typha_test.go
  pkg/render/windows.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required

#2940 [Feature Request] Add podDisruptionBudget in API server
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3281 [release-v1.32] Auto Release Update for v1.32.7
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3283 Update generate-release-notes.py to only include release-note-required label [v1.31]
  generate-release-notes.py
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3284 Update generate-release-notes.py to only include release-note-required label [v1.32]
  generate-release-notes.py
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3280 Fix IP pool name defaulting
  pkg/controller/ippool/defaults.go
  pkg/controller/ippool/pool_controller_test.go
Labels: release-note-not-required, docs-not-required

#3288 [release-v1.34] Auto pick #3280: Fix IP pool name defaulting
  pkg/controller/ippool/defaults.go
  pkg/controller/ippool/pool_controller_test.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#3275 Remove elastic secrets dependency for compliance and only deploy serv…
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/testutils/expected_policies/compliance-server.json
  pkg/render/testutils/expected_policies/compliance-server_ocp.json
  pkg/render/testutils/expected_policies/compliance_unmanaged.json
  pkg/render/testutils/expected_policies/compliance_unmanaged_ocp.json
Labels: docs-pr-required, release-note-required

#3289 [cherry-pick][v1.34] Remove elastic secrets dependency for compliance and only deploy serv…
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/testutils/expected_policies/compliance-server.json
  pkg/render/testutils/expected_policies/compliance-server_ocp.json
  pkg/render/testutils/expected_policies/compliance_unmanaged.json
  pkg/render/testutils/expected_policies/compliance_unmanaged_ocp.json
Labels: docs-pr-required, release-note-required

#3290 Fix handling of UID in IP pool controller
  pkg/controller/ippool/pool_controller.go
Labels: docs-pr-required, release-note-required

#3277 Add CSI anti-affinity defaults
  pkg/render/csi.go
  pkg/render/csi_test.go
Labels: docs-pr-required, release-note-required

#3291 [release-v1.34] Auto pick #3290: Fix handling of UID in IP pool controller
  pkg/controller/ippool/pool_controller.go
Labels: release-note-not-required, docs-not-required

#3294 Add egress rule to allow dashboards to connect to external Kibana
  pkg/controller/logstorage/dashboards/dashboards_controller.go
  pkg/render/logstorage/dashboards/dashboards.go
  pkg/render/logstorage/dashboards/dashboards_test.go
Labels: docs-pr-required, release-note-required

#3295 [cherry-pick][v1.34] Add egress rule to allow dashboards to connect to external Kibana (#3…
  pkg/controller/logstorage/dashboards/dashboards_controller.go
  pkg/render/logstorage/dashboards/dashboards.go
  pkg/render/logstorage/dashboards/dashboards_test.go
Labels: docs-pr-required, release-note-required

#3271 Send the list of all ips to egress gateway to support dual stack
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#3292 EV-4646 - Deprecate AWS - Remove cloud-controller references
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3301 [Release v1.34] Send the list of all ips to egress gateway to support dual stack
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#3299 [Release v1.33] Send the list of all ips to egress gateway to support dual stack
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#3188 Namespace migration - Fix potential namespace migration problem with one node cluster
  pkg/controller/migration/namespace_migration.go
Labels: docs-pr-required, release-note-required

#3297 Automated cherry pick of #3296: The dashboard name has changed in the installer repo, change
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#3296 The dashboard name has changed in the installer repo, change it accor…
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#3305 Cherry-pick #3304 EV-4792 Added Add HSTS header to dex and upgrade to 2.39
  pkg/render/dex.go
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required

#3304 EV-4792 Added Add HSTS header to dex and upgrade to 2.39
  pkg/render/dex.go
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required

#3303 cherry-pick #3302 Fix broken policy rec req limit reconcilation
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3302 Fix broken policy rec req limit reconcilation
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
Labels: docs-pr-required, release-note-required

#3312 [EV-4646] Remove cloud-controller references
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3306 Shorten kibana session
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3313 Fix annotations for voltron tls route configuration (too long and invalid characters)
  pkg/render/manager/manager_route_config.go
  pkg/render/manager/manager_route_config_test.go
Labels: docs-pr-required, release-note-required

#3315 [release-v1.34] Auto pick #3313: Fix annotations for voltron tls route configuration (too long
  pkg/render/manager/manager_route_config.go
  pkg/render/manager/manager_route_config_test.go
Labels: docs-pr-required, release-note-required

#3314 Rev Go to v1.22, Kubernetes to v1.28.9.
  Makefile
  api/v1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
  pkg/crds/operator/operator.tigera.io_tlspassthroughroutes.yaml
  pkg/crds/operator/operator.tigera.io_tlsterminatedroutes.yaml
Labels: docs-pr-required, release-note-required

#3317 [v1.34] Rev Go to v1.22, Kubernetes to v1.28.9
  Makefile
  api/v1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
  pkg/crds/operator/operator.tigera.io_tlspassthroughroutes.yaml
  pkg/crds/operator/operator.tigera.io_tlsterminatedroutes.yaml
Labels: release-note-required, docs-not-required

#3316 EV-4848 Add resource requirement config for packet capture
  api/v1/packetcapture_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_packetcaptures.yaml
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
Labels: docs-pr-required, release-note-required

#3321 [release 1.32] Update depndencies
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#3320 [release 1.33] Update dependencies
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#3319 Update branch cutting instructions.
  RELEASING.md
Labels: release-note-not-required, docs-not-required

#3318 cherry-pick #3316 EV-4848 Add resource requirement config for packet capture
  api/v1/packetcapture_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_packetcaptures.yaml
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
Labels: docs-pr-required, release-note-required

#3324 cherry-pick #3323 move packet capture watch inside enterpriseCRD exist check
  pkg/controller/apiserver/apiserver_controller.go
Labels: docs-pr-required, release-note-required

#3323 move packet capture watch inside enterpriseCRD exist check
  pkg/controller/apiserver/apiserver_controller.go
Labels: docs-pr-required, release-note-required

#3327 Fix annotation data ordering issues from k8s listing in different order and maps not being ordered
  pkg/render/manager/manager_route_config.go
  pkg/render/manager/manager_route_config_test.go
Labels: docs-pr-required, release-note-required

#3325 [RS-1818] Update ILM policy to keep warm tigera_secure_ee_events indices writable
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/elasticsearch_test.go
  pkg/controller/utils/test_files/02_put_policy.json
Labels: docs-pr-required, release-note-required

#3330 [RS-1818] Update ILM policy to keep warm tigera_secure_ee_events indices writable
  pkg/controller/utils/elasticsearch.go
  pkg/controller/utils/elasticsearch_test.go
  pkg/controller/utils/test_files/02_put_policy.json
Labels: docs-pr-required, release-note-required

#3310 [release-v1.34][cherry-pick] Fix security-context for apiserver - audit logs are supported only in Enterprise version
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3331 Automatic version updates for v1.32.8 release
  config/common_versions.yml
  config/enterprise_versions.yml
  pkg/components/common.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3334 Name Packet capture operator v1 CRD as PacketCaptureAPI
  api/v1/packetcapture_types.go
  api/v1/packetcaptureapi_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_packetcaptureapis.yaml
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
Labels: docs-pr-required, release-note-required

#3335 Cherry-pick #3334 Name Packet capture operator v1 CRD as PacketCaptureAPI
  api/v1/packetcapture_types.go
  api/v1/packetcaptureapi_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_packetcaptureapis.yaml
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
Labels: docs-pr-required, release-note-required

#3338 Automated cherry pick of #3337: Update prometheus operator permissions to v0.73.2
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: docs-pr-required, release-note-required
