Repository tigera/operator, pull requests merged in 2024-12, with the labels that each got.

#3612 add resource req/limits for es-gateway
  api/v1/esgateway_deployment_types.go
  api/v1/logstorage_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/kubecontrollers/esgateway.go
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
Labels: docs-pr-required, release-note-required

#3613 Clarify processing of pod resource overrides
  api/v1/apiserver_types.go
  api/v1/benchmarker_types.go
  api/v1/calico_kubecontrollers_types.go
  api/v1/calico_node_types.go
  api/v1/calico_node_windows_types.go
  api/v1/compliance_controller_types.go
  api/v1/compliance_reporter_types.go
  api/v1/compliance_server_types.go
  api/v1/csi_node_driver.go
  api/v1/dashboards_job_types.go
  api/v1/dex_deployment_types.go
  api/v1/eckoperator_types.go
  api/v1/egressgateway_types.go
  api/v1/eks_logforwarder_types.go
  api/v1/elasticsearchmetric_types.go
  api/v1/fluentd_daemonset_types.go
  api/v1/guardian_deployment_types.go
  api/v1/intrusiondetection_types.go
  api/v1/kibana_types.go
  api/v1/l7_logcollector_types.go
  api/v1/linseed_deployment_types.go
  api/v1/manager_types.go
  api/v1/packetcaptureapi_types.go
  api/v1/policyrecommendation_types.go
  api/v1/snapshotter_deployment_types.go
  api/v1/typha_deployment_types.go
  api/v1/windows_upgrade_types.go
  go.mod
  pkg/common/validation/overrides.go
  pkg/common/validation/overrides_test.go
  pkg/components/overrides.go
  pkg/render/common/components/components.go
Labels: release-note-not-required, docs-not-required

#3628 Fix 'intrustion' typo
  pkg/controller/intrusiondetection/intrusiondetection_suite_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3632 Fix for PriorityClassName override handling
  pkg/render/common/components/components.go
Labels: release-note-not-required, docs-not-required

#3627 Remove override methods for ESGatewayDeployment
  api/v1/esgateway_deployment_types.go
Labels: release-note-not-required, docs-not-required

#3631 Disable the ValidatingAdmissionPolicy API on k8s v1.28 and older
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3625 cherry-pick #3612 add resource req/limits for es-gateway
  api/v1/esgateway_deployment_types.go
  api/v1/logstorage_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/kubecontrollers/esgateway.go
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esgateway/esgateway_test.go
Labels: docs-pr-required, release-note-required

#3634 Add support for BaselineAdminNetworkPolicy
  pkg/crds/calico/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/apiserver.go
  pkg/render/node.go
  pkg/render/nonclusterhost/nonclusterhost.go
  pkg/render/typha.go
Labels: release-note-not-required, docs-not-required

#3626 UT to check for unhandled override fields
  pkg/render/common/components/components.go
  pkg/render/common/components/components_test.go
Labels: release-note-not-required, docs-not-required

#3639 Update CRDs
  pkg/crds/calico/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3636 Expand proxy detection support to Dex and support proxy configuration
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/authentication_controller_test.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/utils/merge.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/dex.go
  pkg/render/guardian.go
  test/utils.go
Labels: docs-pr-required, release-note-required

#3640 [release-v1.36] Auto pick #3633: Update AWS SG setup job for OpenShift
  pkg/awssgsetup/aws_security_group_setup.go
Labels: release-note-not-required, docs-not-required

#3641 [release-v1.35] Auto pick #3389: Add support for OpenShift HCP #3640: Update AWS SG setup job for OpenShift
  go.mod
  go.sum
  main.go
  pkg/awssgsetup/aws_security_group_setup.go
  pkg/controller/installation/core_controller.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/aws-securitygroup-setup_test.go
Labels: kind/enhancement, docs-pr-required, release-note-required

#3642 [release-v1.34] Auto pick #3389: Add support for OpenShift HCP #3640: Update AWS SG setup job for OpenShift
  go.mod
  go.sum
  main.go
  pkg/awssgsetup/aws_security_group_setup.go
  pkg/controller/installation/core_controller.go
  pkg/render/aws-securitygroup-setup.go
  pkg/render/aws-securitygroup-setup_test.go
Labels: kind/enhancement, docs-pr-required, release-note-required

#3647 Upgrade to es/kb 8.16.1 - es user id to 10001
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3650 Regenerate manifests using the latest controller-gen
  Makefile
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/calico/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/calico/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/calico/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networksets.yaml
  pkg/crds/calico/crd.projectcalico.org_tiers.yaml
  pkg/crds/crds_test.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_nonclusterhosts.yaml
  pkg/crds/operator/operator.tigera.io_packetcaptureapis.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
  pkg/crds/operator/operator.tigera.io_tlspassthroughroutes.yaml
  pkg/crds/operator/operator.tigera.io_tlsterminatedroutes.yaml
Labels: docs-pr-required, release-note-required

#3630 Restrict tigera-operator secret access to namespace only
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/logstorage/initializer/initializing_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/eck/eck.go
  pkg/render/logstorage/eck/eck_test.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch_test.go
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/render_test.go
  pkg/render/utils.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3654 Update dex binary path
  pkg/render/dex.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3638 Add Gateway API and Envoy Gateway install to Calico Enterprise
  Makefile
  PROJECT
  api/v1/gatewayapi_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/kustomization.yaml
  config/enterprise_versions.yml
  config/samples/kustomization.yaml
  config/samples/operator_v1_gatewayapi.yaml
  go.mod
  go.sum
  hack/gen-versions/enterprise.go.tpl
  internal/controller/controllers.go
  internal/controller/gatewayapi_controller.go
  pkg/apis/apis.go
  pkg/components/enterprise.go
  pkg/controller/gatewayapi/gatewayapi_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/utils/component.go
  pkg/crds/operator/operator.tigera.io_gatewayapis.yaml
  pkg/render/common/components/components.go
  pkg/render/common/components/components_test.go
  pkg/render/gateway_api.go
  pkg/render/gateway_api_resources.yaml
  pkg/render/gateway_api_test.go
  pkg/render/passthru.go
Labels: docs-pr-required, release-note-required

#3656 ev-5453
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#3658 Bump guardian to 3.20.0-2.3
  config/enterprise_versions.yml
  hack/maybe-build-release.sh
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3635 Update ImageSet docstring
  api/v1/imageset_types.go
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
Labels: docs-pr-required, release-note-required

#3659 Update CRDs: SecurityEventWebhooks
  pkg/crds/enterprise/crd.projectcalico.org_securityeventwebhooks.yaml
Labels: docs-pr-required, release-note-required

#3657 Move loadbalancer kubecontroller to enterprise default
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#3655 Cherry pick Gateway API work to branch for 3.21ep1
  Makefile
  PROJECT
  api/v1/gatewayapi_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/kustomization.yaml
  config/enterprise_versions.yml
  config/samples/kustomization.yaml
  config/samples/operator_v1_gatewayapi.yaml
  go.mod
  go.sum
  hack/gen-versions/enterprise.go.tpl
  internal/controller/controllers.go
  internal/controller/gatewayapi_controller.go
  pkg/apis/apis.go
  pkg/components/enterprise.go
  pkg/controller/gatewayapi/gatewayapi_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/utils/component.go
  pkg/crds/operator/operator.tigera.io_gatewayapis.yaml
  pkg/render/common/components/components.go
  pkg/render/common/components/components_test.go
  pkg/render/gateway_api.go
  pkg/render/gateway_api_resources.yaml
  pkg/render/gateway_api_test.go
  pkg/render/passthru.go
Labels: docs-pr-required, release-note-required

#3653 cherry-pick #3630 Restrict tigera-operator secret access to namespace only
  pkg/controller/compliance/compliance_controller.go
  pkg/controller/logstorage/initializer/initializing_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/dex.go
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/render/fluentd_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/intrusiondetection/dpi/dpi_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/eck/eck.go
  pkg/render/logstorage/eck/eck_test.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch_test.go
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_test.go
  pkg/render/logstorage_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  pkg/render/packet_capture_api.go
  pkg/render/packet_capture_api_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/render_test.go
  pkg/render/utils.go
Labels: docs-pr-required, release-note-required

#3651 cherry-pick #3645 Upgrade to es/kb 8.16.1 - es user id to 10001
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3660 Retain the get/list/watch for calico-kube-controller SA
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#3666 Cherry-pick #3660 Retain the get/list/watch for calico-kube-controller SA
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#3597 Add egress rule to kubernetes service when configured from configmap
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: docs-pr-required, release-note-required

#3668 Allow operator to create secrets in tigera-gateway namespace
  pkg/controller/gatewayapi/gatewayapi_controller.go
  pkg/render/gateway_api.go
  pkg/render/gateway_api_test.go
Labels: release-note-not-required, docs-not-required

#3667 expose logLevel for apiserver containers (#3652)
  api/v1/apiserver_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required

#3669 Allow operator to create secrets in tigera-gateway namespace
  pkg/controller/gatewayapi/gatewayapi_controller.go
  pkg/render/gateway_api.go
  pkg/render/gateway_api_test.go
Labels: release-note-not-required, docs-not-required

#3637 Stop benchmarking CRD loading since they are cached
  pkg/crds/crds_test.go
Labels: release-note-not-required, docs-not-required

#3664 [RS-2246] Updates for view WAF ruleset epic
  go.mod
  go.sum
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
  pkg/render/applicationlayer/embed/embed.go
  pkg/render/applicationlayer/ruleset/coreruleset/tigera.conf
  pkg/render/applicationlayer/ruleset/embed.go
  pkg/render/applicationlayer/ruleset/embed_test.go
Labels: docs-pr-required, release-note-required

#3670 Include dex secrets only when oidc is non tigera or nil
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/dex.go
Labels: docs-pr-required, release-note-required

#3672 cherry-pick #3670 Include dex secrets when oidc is non tigera or nil
  pkg/render/dex.go
Labels: docs-pr-required, release-note-required

#3673 Fix Dex policy test flake
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3601 Adjust connection controller and how it handles the license and network policy
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
Labels: docs-pr-required, release-note-required

#3674 [release-v1.37] Update dex binary path
  pkg/render/dex.go
Labels: docs-pr-required, release-note-required, merge-when-ready
