Repository tigera/operator, pull requests merged in 2025-04, with the labels that each got.

#3847 [release-v1.36] Auto Release Update for v1.36.8
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3848 Add notifications flag to disable notifications in the UI
  api/v1/whisker_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/whisker/controller.go
  pkg/crds/operator/operator.tigera.io_whiskers.yaml
  pkg/render/whisker/component.go
  pkg/render/whisker/component_test.go
Labels: docs-pr-required, release-note-required

#3842 Automated cherry pick of #3814: Fix certificate management with ECK 2.16.1. The prepare-fs.sh
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3845 Rename tigera-guardian components to guardian
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/logstorage/managedcluster/managed_cluster_controller_test.go
  pkg/render/goldmane/component_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/testutils/expected_policies/compliance_managed.json
  pkg/render/testutils/expected_policies/compliance_managed_ocp.json
  pkg/render/testutils/expected_policies/dpi_managed.json
  pkg/render/testutils/expected_policies/dpi_managed_ocp.json
  pkg/render/testutils/expected_policies/fluentd_managed.json
  pkg/render/testutils/expected_policies/guardian.json
  pkg/render/testutils/expected_policies/guardian_ocp.json
  pkg/render/testutils/expected_policies/intrusion-detection-controller_managed.json
  pkg/render/testutils/expected_policies/intrusion-detection-controller_managed_ocp.json
  pkg/render/testutils/expected_policies/kubecontrollers_managed.json
  pkg/render/testutils/expected_policies/kubecontrollers_managed_ocp.json
  pkg/render/testutils/expected_policies/packetcapture_managed.json
  pkg/render/testutils/expected_policies/packetcapture_managed_ocp.json
Labels: docs-pr-required, release-note-required

#3855 [PICK release-v1.38] Picks for OSS UI and Free tier
  api/v1/whisker_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/apis/crd.projectcalico.org/v1/clusterinfo.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/logstorage/managedcluster/managed_cluster_controller_test.go
  pkg/controller/whisker/controller.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/operator/operator.tigera.io_whiskers.yaml
  pkg/render/goldmane/component_test.go
  pkg/render/guardian.go
  pkg/render/guardian_test.go
  pkg/render/testutils/expected_policies/compliance_managed.json
  pkg/render/testutils/expected_policies/compliance_managed_ocp.json
  pkg/render/testutils/expected_policies/dpi_managed.json
  pkg/render/testutils/expected_policies/dpi_managed_ocp.json
  pkg/render/testutils/expected_policies/fluentd_managed.json
  pkg/render/testutils/expected_policies/guardian.json
  pkg/render/testutils/expected_policies/guardian_ocp.json
  pkg/render/testutils/expected_policies/intrusion-detection-controller_managed.json
  pkg/render/testutils/expected_policies/intrusion-detection-controller_managed_ocp.json
  pkg/render/testutils/expected_policies/kubecontrollers_managed.json
  pkg/render/testutils/expected_policies/kubecontrollers_managed_ocp.json
  pkg/render/testutils/expected_policies/packetcapture_managed.json
  pkg/render/testutils/expected_policies/packetcapture_managed_ocp.json
  pkg/render/whisker/component.go
  pkg/render/whisker/component_test.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required

#3858 generate manifests
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
Labels: release-note-not-required, docs-not-required

#3859 Don't include cluster.local in Goldmane URL
  pkg/render/node.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3860 Use same yaml 'prettier' as calico does to fix hash release generation
  Makefile
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_gatewayapis.yaml
  pkg/crds/operator/operator.tigera.io_goldmanes.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_nonclusterhosts.yaml
  pkg/crds/operator/operator.tigera.io_packetcaptureapis.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
  pkg/crds/operator/operator.tigera.io_tlspassthroughroutes.yaml
  pkg/crds/operator/operator.tigera.io_tlsterminatedroutes.yaml
  pkg/crds/operator/operator.tigera.io_whiskers.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3862 Skip Typha scaling checks when we're terminating
  pkg/controller/installation/core_controller.go
Labels: release-note-not-required, docs-not-required

#3861 [release-v1.38] Auto pick #3859: Don't include cluster.local in Goldmane URL
  pkg/render/node.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3866 Set explicit DNS nameservers for calico/node when needed
  cmd/main.go
  pkg/controller/installation/core_controller.go
  pkg/controller/options/options.go
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/calico/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/calico/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/calico/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networksets.yaml
  pkg/crds/calico/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_tiers.yaml
  pkg/dns/dns.go
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#3865 cherry-pick #3863 fix tigera-operator permission error for egressgateway
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#3868 [release-v1.38] Auto pick #3866: Set explicit DNS nameservers for calico/node when needed
  cmd/main.go
  pkg/controller/installation/core_controller.go
  pkg/controller/options/options.go
  pkg/dns/dns.go
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#3871 Add more permissions for guardian
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#3872 [PICK release-v1.38] Add more permissions for guardian (#3871)
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#3873 [Cherry-pick][v1.37] Add rbac to delete secrets (#3870)
  pkg/controller/logstorage/elastic/external_elastic_controller.go
  pkg/render/logstorage.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch_test.go
Labels: docs-pr-required, release-note-required

#3874 [cherry-pick][v1.38] Add rbac to delete secrets (#3870)
  pkg/controller/logstorage/elastic/external_elastic_controller.go
  pkg/render/logstorage.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch.go
  pkg/render/logstorage/externalelasticsearch/externalelasticsearch_test.go
Labels: docs-pr-required, release-note-required

#3840 [EV-5771] Introduce MANAGED_CLUSTER_IS_CALICO flag into the policy recommendation controller
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#3875 [Cherry-pick] Introduce necessary env vars to policy recommendation
  pkg/controller/policyrecommendation/policyrecommendation_controller.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#3876 [Cherry-Pick] Introduce MANAGED_CLUSTER_TYPE env var into the policy recommendation controller
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
Labels: docs-pr-required, release-note-required

#3867 Update es&kb to 7.17.28
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3854 Don't block the controller is authentication is not ready. Otherwise,…
  pkg/controller/monitor/monitor_controller.go
Labels: docs-pr-required, release-note-required

#3877 Automated cherry pick of #3867: Update es&kb to 7.17.28
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3879 Automated cherry pick of #3854: Remove dependency on authentication_controller while
  pkg/controller/monitor/monitor_controller.go
Labels: docs-pr-required, release-note-required

#3878 Automated cherry pick of #3854: Remove dependency on authentication_controller while
  pkg/controller/monitor/monitor_controller.go
Labels: docs-pr-required, release-note-required

#3881 Pull in latest CRDs from Calico
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/calico/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/calico/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/calico/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networksets.yaml
  pkg/crds/calico/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_tiers.yaml
Labels: release-note-not-required, docs-not-required

#3786 [RS-23978] Make operator api a go module
  api/go.mod
  api/go.sum
  api/v1/installation_types.go
  cmd/main.go
  go.mod
  go.sum
  pkg/apis/crd.projectcalico.org/v1/ippool.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/ippool/defaults.go
  pkg/controller/ippool/pool_controller.go
  pkg/controller/ippool/pool_conversion_test.go
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
  pkg/render/namespaces.go
  pkg/render/namespaces_test.go
  test/pool_test.go
Labels: release-note-not-required, docs-not-required

#3885 [release-v1.34] Auto Release Update for v1.34.10
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3888 [release-v1.38] Auto pick #3887: Use explicit verbs in tiered policy passthrough
  pkg/render/apiserver.go
Labels: release-note-required, docs-not-required

#3889 Auto version updates for v1.37.2
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3895 Mount BPF FS for iptables mode in EE
  pkg/controller/installation/core_controller_test.go
  pkg/crds/enterprise/crd.projectcalico.org_alertexceptions.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bfdconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/enterprise/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/enterprise/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_deeppacketinspections.yaml
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_externalnetworks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreports.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreporttypes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalthreatfeeds.yaml
  pkg/crds/enterprise/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_licensekeys.yaml
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_packetcaptures.yaml
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_securityeventwebhooks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_tiers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettingsgroups.yaml
  pkg/crds/enterprise/usage.tigera.io_licenseusagereports.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#3896 [master] Auto pick #3895: Mount BPF FS for iptables mode in EE as we use BPF maps,
  pkg/controller/installation/core_controller_test.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_alertexceptions.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bfdconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/enterprise/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/enterprise/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_deeppacketinspections.yaml
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_externalnetworks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreports.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreporttypes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalthreatfeeds.yaml
  pkg/crds/enterprise/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_licensekeys.yaml
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_packetcaptures.yaml
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_securityeventwebhooks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_tiers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettingsgroups.yaml
  pkg/crds/enterprise/usage.tigera.io_licenseusagereports.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#3897 Automated cherry pick of #3654: Update dex binary path
  pkg/render/dex.go
Labels: docs-pr-required, release-note-required

#3898 Automated cherry pick of #3654: Update dex binary path
  pkg/render/dex.go
Labels: docs-pr-required, release-note-required

#3900 [release-v1.34] Auto Release Update for v1.34.11
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3899 [CORE-11328] v1.38: Bumping k8s and x/net version
  Makefile
  go.mod
  go.sum
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_gatewayapis.yaml
  pkg/crds/operator/operator.tigera.io_goldmanes.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_nonclusterhosts.yaml
  pkg/crds/operator/operator.tigera.io_packetcaptureapis.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
  pkg/crds/operator/operator.tigera.io_tlspassthroughroutes.yaml
  pkg/crds/operator/operator.tigera.io_tlsterminatedroutes.yaml
  pkg/crds/operator/operator.tigera.io_whiskers.yaml
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required

#3903 Fix CRD creation; calico-private now has documents with more than 1 CRD
  pkg/crds/crds.go
  pkg/crds/enterprise/01-crd-eck-agent.yaml
  pkg/crds/enterprise/01-crd-eck-apmserver.yaml
  pkg/crds/enterprise/01-crd-eck-autoscaling.yaml
  pkg/crds/enterprise/01-crd-eck-beat.yaml
  pkg/crds/enterprise/01-crd-eck-bundle.yaml
  pkg/crds/enterprise/01-crd-eck-elasticmapsserver.yaml
  pkg/crds/enterprise/01-crd-eck-elasticsearch.yaml
  pkg/crds/enterprise/01-crd-eck-enterprisesearch.yaml
  pkg/crds/enterprise/01-crd-eck-kibana.yaml
  pkg/crds/enterprise/01-crd-eck-logstash.yaml
  pkg/crds/enterprise/01-crd-eck-stackconfigpolicy.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch

#3905 Disable license controller for Calico managed clusters
  pkg/render/kubecontrollers/kube-controllers.go
Labels: release-note-not-required, docs-not-required

#3907 [release-v1.38] Auto pick #3905: Disable license controller for Calico managed clusters
  pkg/render/kubecontrollers/kube-controllers.go
Labels: release-note-not-required, docs-not-required

#3909 Add doc about updating the envoy versions for Gateway API
  docs/common_tasks.md
Labels: release-note-not-required, docs-not-required

#3891 Update Envoy Gateway from v1.2.6 to v1.3.2
  Makefile
  go.mod
  go.sum
  pkg/render/gateway_api.go
  pkg/render/gateway_api_resources.yaml
Labels: kind/enhancement, hold merge, docs-pr-required, release-note-required

#3911 [release-v1.38] Auto pick #3891: Bump github.com/envoyproxy/gateway from v1.2.6 to v1.3.2
  Makefile
  go.mod
  go.sum
  pkg/render/gateway_api.go
  pkg/render/gateway_api_resources.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready

#3912 [master] Auto pick #3899: Upgrading k8s (0.32.4) and x/net (0.29.0) packages
  Makefile
  go.mod
  go.sum
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_applicationlayers.yaml
  pkg/crds/operator/operator.tigera.io_authentications.yaml
  pkg/crds/operator/operator.tigera.io_compliances.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_gatewayapis.yaml
  pkg/crds/operator/operator.tigera.io_goldmanes.yaml
  pkg/crds/operator/operator.tigera.io_imagesets.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/crds/operator/operator.tigera.io_intrusiondetections.yaml
  pkg/crds/operator/operator.tigera.io_logcollectors.yaml
  pkg/crds/operator/operator.tigera.io_logstorages.yaml
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/crds/operator/operator.tigera.io_managementclusters.yaml
  pkg/crds/operator/operator.tigera.io_managers.yaml
  pkg/crds/operator/operator.tigera.io_monitors.yaml
  pkg/crds/operator/operator.tigera.io_nonclusterhosts.yaml
  pkg/crds/operator/operator.tigera.io_packetcaptureapis.yaml
  pkg/crds/operator/operator.tigera.io_policyrecommendations.yaml
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/crds/operator/operator.tigera.io_tigerastatuses.yaml
  pkg/crds/operator/operator.tigera.io_tlspassthroughroutes.yaml
  pkg/crds/operator/operator.tigera.io_tlsterminatedroutes.yaml
  pkg/crds/operator/operator.tigera.io_whiskers.yaml
  pkg/render/logstorage.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3882 extends the Installation resource to allow specifying directories for installing CNI binaries and configuration files
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/utils/merge.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
  pkg/render/render_test.go
Labels: docs-pr-required, release-note-required

#3910 Fix manager RBAC for mixed mode management clusters
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/utils/namespace_helper.go
  pkg/controller/utils/utils.go
  pkg/render/guardian.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: release-note-not-required, docs-not-required

#3913 [release-v1.38] Auto pick #3910: Fix manager RBAC for mixed mode management clusters
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/utils/namespace_helper.go
  pkg/controller/utils/utils.go
  pkg/render/guardian.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: release-note-not-required, docs-not-required

#3914 [release-v1.37] Auto pick #3910: Fix manager RBAC for mixed mode management clusters
  pkg/controller/manager/manager_controller.go
  pkg/controller/manager/manager_controller_test.go
  pkg/controller/tiers/tiers_controller.go
  pkg/controller/utils/namespace_helper.go
  pkg/controller/utils/utils.go
  pkg/render/guardian.go
  pkg/render/manager.go
  pkg/render/manager_test.go
Labels: release-note-not-required, docs-not-required

#3915 [release-v1.37] Auto pick #3907: Disable license controller for Calico managed clusters
  pkg/render/kubecontrollers/kube-controllers.go
Labels: release-note-not-required, docs-not-required

#3917 Don't run kube-controllers if there are no enabled controllers
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#3919 [release-v1.38] Auto pick #3917: Don't run kube-controllers if there are no enabled
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#3918 [release-v1.37] Auto pick #3917: Don't run kube-controllers if there are no enabled
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required
