Repository tigera/operator, pull requests merged in 2025-01, with the labels that each got.

#3676 [release-v1.36] Auto pick #3631: Disable the ValidatingAdmissionPolicy API on k8s v1.28 and
  pkg/controller/apiserver/apiserver_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3675 Update the upstream versions of alertmanager and prometheus
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3629 Update eck to v2.16.0
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/eck/eck.go
  pkg/render/logstorage/eck/eck_test.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3680 Update CRDs: FelixConfigurations
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3481 Calico apiserver improvements
  api/v1/apiserver_types.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3677 v1.37 Automated cherry pick of #3629: Make ES work with ECK 2.16.0 by setting the appropriate
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/eck/eck.go
  pkg/render/logstorage/eck/eck_test.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3678 v1.36 Automated cherry pick of #3629: Make ES work with ECK 2.16.0 by setting the appropriate
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/controller/installation/validation.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage/eck/eck.go
  pkg/render/logstorage/eck/eck_test.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3681 Include ECK CRDs in those managed by the operator
  Makefile
  pkg/crds/enterprise/01-crd-eck-agent.yaml
  pkg/crds/enterprise/01-crd-eck-apmserver.yaml
  pkg/crds/enterprise/01-crd-eck-autoscaling.yaml
  pkg/crds/enterprise/01-crd-eck-beat.yaml
  pkg/crds/enterprise/01-crd-eck-elasticmapsserver.yaml
  pkg/crds/enterprise/01-crd-eck-elasticsearch.yaml
  pkg/crds/enterprise/01-crd-eck-enterprisesearch.yaml
  pkg/crds/enterprise/01-crd-eck-kibana.yaml
  pkg/crds/enterprise/01-crd-eck-logstash.yaml
  pkg/crds/enterprise/01-crd-eck-stackconfigpolicy.yaml
Labels: docs-pr-required, release-note-required

#3683 [Pick #3452] Improve OpenShift platform detection accuracy (1.34)
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
Labels: release-note-required, docs-not-required

#3684 [Pick #3681] Include ECK CRDs in those managed by the operator (r1.37)
  Makefile
  pkg/crds/enterprise/01-crd-eck-agent.yaml
  pkg/crds/enterprise/01-crd-eck-apmserver.yaml
  pkg/crds/enterprise/01-crd-eck-autoscaling.yaml
  pkg/crds/enterprise/01-crd-eck-beat.yaml
  pkg/crds/enterprise/01-crd-eck-elasticmapsserver.yaml
  pkg/crds/enterprise/01-crd-eck-elasticsearch.yaml
  pkg/crds/enterprise/01-crd-eck-enterprisesearch.yaml
  pkg/crds/enterprise/01-crd-eck-kibana.yaml
  pkg/crds/enterprise/01-crd-eck-logstash.yaml
  pkg/crds/enterprise/01-crd-eck-stackconfigpolicy.yaml
Labels: docs-pr-required, release-note-required

#3693 Update pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3694 Automated cherry pick of #3673: Fix dex policy test flake
  pkg/render/dex_test.go
Labels: docs-pr-required, release-note-required

#3691 Automated cherry pick of #3690: Override ECK mount path such that our plugin continues to
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_test.go
Labels: docs-pr-required, release-note-required

#3685 [cherry-pick][v1.34]Create namespace before certificates (#3403)
  pkg/controller/intrusiondetection/intrusiondetection_controller.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
Labels: docs-pr-required, release-note-required

#3690 Override ECK mount path such that our plugin continues to work
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_test.go
Labels: docs-pr-required, release-note-required

#3695 [release-v1.36] Auto pick #3681: Include ECK CRDs in those managed by the operator
  Makefile
  pkg/crds/enterprise/01-crd-eck-agent.yaml
  pkg/crds/enterprise/01-crd-eck-apmserver.yaml
  pkg/crds/enterprise/01-crd-eck-autoscaling.yaml
  pkg/crds/enterprise/01-crd-eck-beat.yaml
  pkg/crds/enterprise/01-crd-eck-elasticmapsserver.yaml
  pkg/crds/enterprise/01-crd-eck-elasticsearch.yaml
  pkg/crds/enterprise/01-crd-eck-enterprisesearch.yaml
  pkg/crds/enterprise/01-crd-eck-kibana.yaml
  pkg/crds/enterprise/01-crd-eck-stackconfigpolicy.yaml
Labels: docs-pr-required, release-note-required

#3698 v1.34 ev-5445 ECK
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/controller/installation/validation.go
  pkg/controller/logstorage/elastic/elastic_controller_test.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3700 Add serviceaccount list to network-admin and user-ui (#3687)
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3696 [release-v1.35] Auto pick #3681: Include ECK CRDs in those managed by the operator
  Makefile
  pkg/crds/enterprise/01-crd-eck-agent.yaml
  pkg/crds/enterprise/01-crd-eck-apmserver.yaml
  pkg/crds/enterprise/01-crd-eck-autoscaling.yaml
  pkg/crds/enterprise/01-crd-eck-beat.yaml
  pkg/crds/enterprise/01-crd-eck-elasticmapsserver.yaml
  pkg/crds/enterprise/01-crd-eck-elasticsearch.yaml
  pkg/crds/enterprise/01-crd-eck-enterprisesearch.yaml
  pkg/crds/enterprise/01-crd-eck-kibana.yaml
  pkg/crds/enterprise/01-crd-eck-stackconfigpolicy.yaml
Labels: docs-pr-required, release-note-required

#3697 [release-v1.34] Auto pick #3681: Include ECK CRDs in those managed by the operator
  Makefile
  pkg/crds/enterprise/01-crd-eck-agent.yaml
  pkg/crds/enterprise/01-crd-eck-apmserver.yaml
  pkg/crds/enterprise/01-crd-eck-autoscaling.yaml
  pkg/crds/enterprise/01-crd-eck-beat.yaml
  pkg/crds/enterprise/01-crd-eck-elasticmapsserver.yaml
  pkg/crds/enterprise/01-crd-eck-elasticsearch.yaml
  pkg/crds/enterprise/01-crd-eck-enterprisesearch.yaml
  pkg/crds/enterprise/01-crd-eck-kibana.yaml
  pkg/crds/enterprise/01-crd-eck-stackconfigpolicy.yaml
Labels: docs-pr-required, release-note-required

#3703 Allow kube-controllers to read its own configuration
  pkg/render/kubecontrollers/kube-controllers.go
Labels: release-note-not-required, docs-not-required

#3702 Update Enterprise CRDs
  pkg/crds/enterprise/crd.projectcalico.org_alertexceptions.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bfdconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/enterprise/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/enterprise/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_deeppacketinspections.yaml
  pkg/crds/enterprise/crd.projectcalico.org_egressgatewaypolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_externalnetworks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerts.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalalerttemplates.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreports.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalreporttypes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalthreatfeeds.yaml
  pkg/crds/enterprise/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ippools.yaml
  pkg/crds/enterprise/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_licensekeys.yaml
  pkg/crds/enterprise/crd.projectcalico.org_managedclusters.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_networksets.yaml
  pkg/crds/enterprise/crd.projectcalico.org_packetcaptures.yaml
  pkg/crds/enterprise/crd.projectcalico.org_policyrecommendationscopes.yaml
  pkg/crds/enterprise/crd.projectcalico.org_remoteclusterconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_securityeventwebhooks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/enterprise/crd.projectcalico.org_tiers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettings.yaml
  pkg/crds/enterprise/crd.projectcalico.org_uisettingsgroups.yaml
  pkg/crds/enterprise/usage.tigera.io_licenseusagereports.yaml
Labels: release-note-not-required, docs-not-required

#3701 hardcode /var/run/calico as the location of the endpoint-status dir
  pkg/render/node.go
Labels: docs-pr-required, release-note-required

#3707 Update CRDs. Add BANP.
  pkg/crds/enterprise/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml
Labels: docs-pr-required, release-note-required, merge-when-ready, squash-commits

#3706 Update libcalico-go version to the branch, rather than the last relea…
  config/enterprise_versions.yml
  pkg/crds/enterprise/01-crd-eck-agent.yaml
  pkg/crds/enterprise/01-crd-eck-apmserver.yaml
  pkg/crds/enterprise/01-crd-eck-autoscaling.yaml
  pkg/crds/enterprise/01-crd-eck-beat.yaml
  pkg/crds/enterprise/01-crd-eck-elasticmapsserver.yaml
  pkg/crds/enterprise/01-crd-eck-elasticsearch.yaml
  pkg/crds/enterprise/01-crd-eck-enterprisesearch.yaml
  pkg/crds/enterprise/01-crd-eck-kibana.yaml
  pkg/crds/enterprise/01-crd-eck-logstash.yaml
  pkg/crds/enterprise/01-crd-eck-stackconfigpolicy.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_globalthreatfeeds.yaml
  pkg/crds/enterprise/crd.projectcalico.org_securityeventwebhooks.yaml
  pkg/crds/enterprise/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
Labels: docs-pr-required, release-note-required

#3689 [EV-5553] Pick #3688 apiserver: move loglevel under spec
  api/v1/apiserver_types.go
  api/v1/common_types.go
  api/v1/egressgateway_types.go
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  go.mod
  pkg/controller/egressgateway/egressgateway_controller.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#3688 [EV-5553] apiserver: move loglevel under spec
  api/v1/apiserver_types.go
  api/v1/common_types.go
  api/v1/egressgateway_types.go
  api/v1/installation_types.go
  api/v1/zz_generated.deepcopy.go
  go.mod
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/crds/operator/operator.tigera.io_egressgateways.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/egressgateway/egressgateway_test.go
Labels: docs-pr-required, release-note-required

#3712 Patch Go CVEs
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#3709 Move skip tenant crds to generic GetCRDS function
  pkg/crds/crds.go
Labels: docs-pr-required, release-note-required

#3711 Cherry-pick #3704 Move skip tenant crds to generic GetCRDS function
  pkg/crds/crds.go
Labels: docs-pr-required, release-note-required

#3710 Cherry-pick #3709 Move skip tenant crds to generic GetCRDS function
  pkg/crds/crds.go
Labels: docs-pr-required, release-note-required

#3713 Fix TLSTerminatedRoute mtlsCert secret mount path
  pkg/render/manager/manager_route_config.go
  pkg/render/manager/manager_route_config_test.go
Labels: docs-pr-required, release-note-required

#3714 EV-5564 Remove unnecessary volume override
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/kibana/kibana_test.go
Labels: docs-pr-required, release-note-required

#3715 Add Goldmane to versions generation
  config/calico_versions.yml
  hack/gen-versions/calico.go.tpl
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  pkg/components/calico.go
  pkg/components/enterprise.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#3716 [release-v1.37] Auto pick #3713: Fix TLSTerminatedRoute ForwardingMTLS secret mount path
  pkg/render/manager/manager_route_config.go
  pkg/render/manager/manager_route_config_test.go
Labels: docs-pr-required, release-note-required

#3717 Revert addition of plugins volume. This is only applicable to kbv8+
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3718 Use our own builds of Envoy gateway and ratelimit images
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/gateway_api.go
  pkg/render/gateway_api_test.go
Labels: kind/bug, enterprise, release-note-not-required, docs-not-required

#3722 remove -waf-log-file flag
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/applicationlayer/applicationlayer.go
  pkg/render/applicationlayer/applicationlayer_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, delete-branch, squash-commits

#3726 Use our own build of the Envoy proxy image
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/render/gateway_api_test.go
Labels: release-note-not-required, docs-not-required

#3741 [v1.36] update webhooks-processor component
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
Labels: release-note-not-required, docs-not-required

#3740 [v1.37] update webhooks-processor component
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
Labels: release-note-not-required, docs-not-required

#3734 cherry-pick #3733 upgrade es/kb to 8.17.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3733 upgrade es/kb to 8.17.1
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3742 Change felixconfig WAFEventLogsFileEnabled when necessary
  pkg/apis/crd.projectcalico.org/v1/felixconfig.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/applicationlayer/applicationlayer_controller.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3744 [release-v1.36] Auto Release Update for v1.36.4
  config/enterprise_versions.yml
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3738 update alertmanager version in enterprise_versions.yml
  config/enterprise_versions.yml
Labels: docs-pr-required, release-note-required

#3745 update alertmanager version in enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3747 picked #3724 Bump go dependencies to add 321 CVE
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required, merge-when-ready
