Repository tigera/operator, pull requests merged in 2025-07, with the labels that each got.

#4028 Commit contents of make gen-versions gen-files
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#4029 [release-v1.39] Auto pick #4025: Fix security context for csr init container
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/node.go
  pkg/render/packet_capture_api.go
  pkg/render/policyrecommendation.go
  pkg/render/typha.go
  pkg/tls/certificatemanagement/csr.go
  pkg/tls/certificatemanagement/interface.go
  pkg/tls/certificatemanagement/keypair.go
Labels: docs-pr-required, release-note-required

#4030 [release-v1.38] Auto pick #4025: Fix security context for csr init container
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/certificatemanager/certificatemanager_test.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/compliance.go
  pkg/render/dex.go
  pkg/render/fluentd.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusiondetection/dpi/dpi.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/logstorage.go
  pkg/render/logstorage/esgateway/esgateway.go
  pkg/render/logstorage/esmetrics/elasticsearch_metrics.go
  pkg/render/logstorage/kibana/kibana.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/manager.go
  pkg/render/monitor/monitor.go
  pkg/render/node.go
  pkg/render/packet_capture_api.go
  pkg/render/policyrecommendation.go
  pkg/render/typha.go
  pkg/tls/certificatemanagement/csr.go
  pkg/tls/certificatemanagement/interface.go
  pkg/tls/certificatemanagement/keypair.go
Labels: docs-pr-required, release-note-required

#4034 Bump go-build to 1.24.5-llvm18.1.8-k8s1.32.6
  Makefile
Labels: docs-pr-required, release-note-required

#4035 [release-v1.38] Auto pick #4034: Bump go-build to 1.24.5-llvm18.1.8-k8s1.32.6
  Makefile
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#4037 Fix crds
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#4036 Ev 5879 master
  Makefile
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#4031 Fix incorrect Guardian container name references
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#4040 [v1.38] Fix incorrect Guardian container name references
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#4041 [v1.39] Fix incorrect Guardian container name references
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#4032 [RS-2546] Update operator to deploy waf-http-filter in Enterprise
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/render/gateway_api.go
  pkg/render/gateway_api_test.go
Labels: docs-pr-required, release-note-required

#4042 Set prometheus reload strategy to ProcessSignal instead of default to http
  pkg/render/monitor/monitor.go
  pkg/render/monitor/monitor_test.go
Labels: release-note-not-required, docs-not-required

#4044 cherry-picked #4043 Update Linseed URL for compliance components in managed cluster
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#4043 Update Linseed URL for compliance components in managed cluster
  pkg/render/compliance.go
  pkg/render/compliance_test.go
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#4047 GatewayAPI controller: reconcile periodically
  pkg/controller/gatewayapi/gatewayapi_controller.go
Labels: release-note-not-required, docs-not-required

#4049 GatewayAPI controller: reconcile periodically
  pkg/controller/gatewayapi/gatewayapi_controller.go
Labels: release-note-not-required, docs-not-required

#4050 [release-v1.36] Auto Release Update for v1.36.12
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#4055 CRD update (gen-versions)
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
Labels: release-note-not-required, docs-not-required

#4053 Create ManagedClusterWatch ClusterRole in all management clusters
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: release-note-not-required, docs-not-required

#4052 Update operator api version
  go.mod
Labels: release-note-not-required, docs-not-required

#4064 [CORE-11605] Rename init container `mount-bpffs` to `ebpf-bootstrap`
  api/v1/calico_node_types.go
  api/v1/calico_node_windows_types.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#3894 Remove cnx prefix from Calico Enterprise component names
  config/enterprise_versions.yml
  hack/gen-versions/components.go
  hack/gen-versions/enterprise.go.tpl
  pkg/components/enterprise.go
  pkg/components/images_test.go
  pkg/components/references.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/windows_controller_test.go
  pkg/controller/manager/manager_controller_test.go
  pkg/render/manager_test.go
  pkg/render/node_test.go
  pkg/render/windows_test.go
Labels: docs-pr-required, release-note-required

#4066 Fix static checks for calicoEnterprise version
  pkg/crds/enterprise/crd.projectcalico.org_clusterinformations.yaml
Labels: release-note-not-required, docs-not-required

#4067 Bump ES&KB to 8.18.4
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required
