Repository tigera/operator, pull requests merged in 2025-09, with the labels that each got.

#4124 [release-v1.36] Auto Release Update for v1.36.13
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#4126 [release-v1.38] Auto pick #4123: Extract service account name from serviceaccount token
  pkg/common/operator_serviceaccount.go
Labels: release-note-required, docs-not-required

#4115 [CORE-11751] Enable BPF dataplane auto-install by default for kube-proxy clusters
  api/v1/installation_types.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/installation/defaults_test.go
  pkg/controller/kubeproxy/controller.go
  pkg/controller/kubeproxy/kubeproxy_controller_test.go
  pkg/controller/utils/bpf.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
  pkg/controller/utils/kubeproxy.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_installations.yaml
  test/gatewayapi_test.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required

#4132 make gen-versions
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
Labels: docs-pr-required, release-note-not-required

#4129 Auto-detect default BPF dataplane only for Calico variant.
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
Labels: release-note-not-required, docs-not-required

#4149 Update the crds
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#4085 Allow the user to configure impersonation permissions
  api/v1/managementclusterconnection_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/render/guardian.go
  pkg/render/guardian_test.go
Labels: docs-pr-required, release-note-required

#4154 [release-v1.39] Auto pick #4085: feat: Make guardian impersonation permissions
  api/v1/managementclusterconnection_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/utils/utils.go
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/render/guardian.go
  pkg/render/guardian_test.go
Labels: docs-pr-required, release-note-required

#4143 add namespace policy rule in controller common rules
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: release-note-not-required, docs-not-required

#4157 [v1.40] add namespace policy rule in controller common rules
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: release-note-not-required, docs-not-required

#4125 [cherry-pick][v1.39] Disbable es-kubecontrollers for multi-tenant environments (#4122)
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers.go
  pkg/controller/logstorage/kubecontrollers/es_kube_controllers_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
Labels: release-note-not-required, docs-not-required

#4146 [CORE-11824] BPF auto-config - Warning message for auto-detected providers
  api/v1/installation_types.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/core_controller_test.go
  pkg/controller/kubeproxy/controller.go
  pkg/controller/kubeproxy/kubeproxy_controller_test.go
  pkg/controller/utils/bpf.go
  pkg/controller/utils/discovery.go
  pkg/controller/utils/discovery_test.go
  pkg/controller/utils/sync.go
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/operator/operator.tigera.io_installations.yaml
Labels: release-note-not-required, docs-not-required

#4164 [release-v1.39] Auto pick #4161: Don't use * for impersonation resourceNames
  api/v1/managementclusterconnection_types.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/crds/operator/operator.tigera.io_managementclusterconnections.yaml
  pkg/render/guardian.go
  pkg/render/guardian_test.go
Labels: release-note-not-required, docs-not-required

#4170 Update kube-aggregator to v0.33.3
  go.mod
  go.sum
Labels: release-note-not-required, docs-not-required

#4176 Update the CRDs
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgpfilters.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/calico/crd.projectcalico.org_blockaffinities.yaml
  pkg/crds/calico/crd.projectcalico.org_caliconodestatuses.yaml
  pkg/crds/calico/crd.projectcalico.org_clusterinformations.yaml
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_globalnetworksets.yaml
  pkg/crds/calico/crd.projectcalico.org_hostendpoints.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamblocks.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamconfigs.yaml
  pkg/crds/calico/crd.projectcalico.org_ipamhandles.yaml
  pkg/crds/calico/crd.projectcalico.org_ippools.yaml
  pkg/crds/calico/crd.projectcalico.org_ipreservations.yaml
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_networkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_networksets.yaml
  pkg/crds/calico/crd.projectcalico.org_stagedglobalnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_stagedkubernetesnetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_stagednetworkpolicies.yaml
  pkg/crds/calico/crd.projectcalico.org_tiers.yaml
Labels: release-note-not-required, docs-not-required

#4175 [release-v1.36] Auto pick #4174: fix: fix email unverified issue when obtaining dex token
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-pr-required, release-note-required

#4174 [release-v1.38] Auto pick #4159: fix: fix email unverified issue when obtaining dex token
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-pr-required, release-note-required

#4173 [master] Auto pick #4159: fix: fix email unverified issue when obtaining dex token
  pkg/render/dex_config.go
  pkg/render/dex_config_test.go
Labels: docs-pr-required, release-note-required
