Repository tigera/operator, pull requests merged in 2025-03, with the labels that each got.

#3798 [release-v1.34] Auto Release Update for v1.34.9
  config/enterprise_versions.yml
  pkg/components/enterprise.go
  pkg/crds/enterprise/01-crd-eck-agent.yaml
  pkg/crds/enterprise/01-crd-eck-apmserver.yaml
  pkg/crds/enterprise/01-crd-eck-autoscaling.yaml
  pkg/crds/enterprise/01-crd-eck-beat.yaml
  pkg/crds/enterprise/01-crd-eck-elasticmapsserver.yaml
  pkg/crds/enterprise/01-crd-eck-elasticsearch.yaml
  pkg/crds/enterprise/01-crd-eck-enterprisesearch.yaml
  pkg/crds/enterprise/01-crd-eck-kibana.yaml
  pkg/crds/enterprise/01-crd-eck-logstash.yaml
  pkg/crds/enterprise/01-crd-eck-stackconfigpolicy.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3799 Fixes for Gateway API support in OSS
  pkg/components/references.go
  pkg/controller/gatewayapi/gatewayapi_controller.go
Labels: release-note-not-required, docs-not-required

#3804 Allow OSS operator to self-install GatewayAPI CRD
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/crds.go
  pkg/crds/crds_test.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required

#3807 Allow TLS to Goldmane
  pkg/controller/whisker/controller.go
  pkg/render/whisker/component.go
  pkg/render/whisker/component_test.go
Labels: release-note-not-required, docs-not-required

#3810 Clean up startup logs
  cmd/main.go
Labels: docs-pr-required, release-note-required

#3811 [CORE-11149] Upgrading k8s - v1.28.15, x/crypto - v0.36
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#3802 Changes for management clusters to host Calico managed clusters
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/manager.go
Labels: release-note-not-required, docs-not-required

#3813 Kube-controllers crd and rbac update for autoHEPs
  pkg/crds/calico/crd.projectcalico.org_kubecontrollersconfigurations.yaml
  pkg/render/kubecontrollers/kube-controllers.go
Labels: docs-pr-required, release-note-required

#3803 [RS-2395] update coreruleset version
  go.mod
  go.sum
  pkg/render/applicationlayer/ruleset/embed.go
Labels: docs-pr-required, release-note-required

#3815 [CORE-11149] Upgrading x/net to v0.37.0
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#3819 [release-v1.37] Auto pick #3802: Add API for managed cluster variant
  api/v1/tenant_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/crds/operator/operator.tigera.io_tenants.yaml
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/manager.go
Labels: release-note-not-required, docs-not-required

#3820 Add goldmane configmap volume + mount
  pkg/render/goldmane/component.go
  pkg/render/goldmane/component_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready, squash-commits

#3818 Add overrides to goldmane and whisker
  api/v1/goldmane_deployment_types.go
  api/v1/goldmane_types.go
  api/v1/whisker_deployment_types.go
  api/v1/whisker_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/goldmane/controller.go
  pkg/controller/whisker/controller.go
  pkg/crds/operator/operator.tigera.io_goldmanes.yaml
  pkg/crds/operator/operator.tigera.io_whiskers.yaml
  pkg/render/goldmane/component.go
  pkg/render/goldmane/component_test.go
  pkg/render/whisker/component.go
  pkg/render/whisker/component_test.go
Labels: release-note-not-required, docs-not-required

#3821 Configure liveness / readiness probes on Goldmane
  pkg/render/goldmane/component.go
  pkg/render/goldmane/component_test.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3806 [CORE-10623] Make apiserver ports configurable to avoid conflicts on EKS
  api/v1/apiserver_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/common/validation/apiserver/validation.go
  pkg/common/validation/overrides_test.go
  pkg/crds/operator/operator.tigera.io_apiservers.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/components/components.go
Labels: docs-pr-required, release-note-required

#3824 [EV-5676] update k[b]anp rbacs
  pkg/crds/calico/crd.projectcalico.org_bgpconfigurations.yaml
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#3826 update kubecontrollersconfig crd
  pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml
  pkg/crds/enterprise/crd.projectcalico.org_kubecontrollersconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3828 [release-v1.37] Auto pick #3827: Fix Voltron env var prefixes
  pkg/render/manager.go
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3829 Update versions for v1.38 branch
  config/calico_versions.yml
  config/enterprise_versions.yml
  pkg/components/calico.go
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3736 update alertmanager version in enterprise_versions.yml
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3830 [release-v1.36] Auto Release Update for v1.36.6
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3831 Add read only cluster permissions needed for free tier
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#3835 [release-v1.36] Auto Release Update for v1.36.7
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3834 Render CSR roles when NonClusterHost feature is enabled
  pkg/controller/csr/csr_controller.go
Labels: docs-pr-required, release-note-required

#3837 Check Goldmane CR instead of Whisker
  pkg/controller/installation/core_controller.go
Labels: release-note-not-required, docs-not-required

#3839 Update VERSION_TAG from `master` to `release-v3.30`
  Makefile
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3838 [release-v1.38] Auto pick #3837: Check Goldmane CR instead of Whisker
  pkg/controller/installation/core_controller.go
Labels: release-note-not-required, docs-not-required

#3814 Fix certificate management with ECK 2.16.1. The prepare-fs.sh script …
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3844 [PICKS release-v1.38] Picks for OSS UI
  pkg/render/guardian.go
  pkg/render/manager.go
Labels: docs-pr-required, release-note-required

#3805 Add env vars to the whisker deployment
  pkg/apis/crd.projectcalico.org/v1/clusterinfo.go
  pkg/apis/crd.projectcalico.org/v1/register.go
  pkg/apis/crd.projectcalico.org/v1/zz_generated.deepcopy.go
  pkg/controller/whisker/controller.go
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/whisker/component.go
  pkg/render/whisker/component_test.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required
