Repository tigera/operator, pull requests merged in 2025-06, with the labels that each got.

#3965 Fix! Update CRDs
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3967 Mount cert bundle to old location for fluentd (since mount items are specified specifically)
  pkg/render/dex_test.go
  pkg/render/fluentd.go
  pkg/tls/certificatemanagement/certificatebundle.go
  pkg/tls/certificatemanagement/interface.go
Labels: release-note-not-required, docs-not-required

#3970 Remove bogus mockStatus.On calls for SetDegraded
  pkg/controller/applicationlayer/applicationlayer_controller_test.go
  pkg/controller/compliance/compliance_controller_test.go
  pkg/controller/egressgateway/egressgateway_controller_test.go
  pkg/controller/gatewayapi/gatewayapi_controller_test.go
  pkg/controller/intrusiondetection/intrusiondetection_controller_test.go
  pkg/controller/packetcapture/packetcapture_controller_test.go
  pkg/controller/policyrecommendation/policyrecommendation_controller_test.go
Labels: release-note-not-required, docs-not-required

#3971 Add release note check from Calico OSS [master]
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check_release_notes.yml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3972 [release-v1.34] Auto Release Update for v1.34.12
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3976 Don't modify user-provided registry string
  pkg/components/references.go
  pkg/controller/installation/core_controller.go
  pkg/controller/installation/defaults_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#3983 [release-v1.34] Auto Release Update for v1.34.13
  config/calico_versions.yml
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3977 Use rolebingins to access managed clusters instead of cluster role bi…
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/components/components.go
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/render_test.go
Labels: release-note-not-required, docs-not-required

#3986 Move EE API server namespace out of global Enterprise object
  pkg/controller/installation/core_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: release-note-not-required, docs-not-required

#3987 Use clusterrolebindigs for zero and single tenant
  pkg/render/intrusion_detection.go
  pkg/render/intrusion_detection_test.go
  pkg/render/kubecontrollers/kube-controllers.go
  pkg/render/kubecontrollers/kube-controllers_test.go
  pkg/render/logstorage/linseed/linseed.go
  pkg/render/logstorage/linseed/linseed_test.go
  pkg/render/manager.go
  pkg/render/manager_test.go
  pkg/render/policyrecommendation.go
  pkg/render/policyrecommendation_test.go
  pkg/render/render_test.go
Labels: release-note-not-required, docs-not-required

#3991 Bump golang version
  Makefile
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#3852 Enhance GatewayAPI for LB type and additional configurability
  api/v1/common_types.go
  api/v1/gatewayapi_types.go
  api/v1/zz_generated.deepcopy.go
  pkg/controller/gatewayapi/gatewayapi_controller.go
  pkg/controller/gatewayapi/gatewayapi_controller_suite_test.go
  pkg/controller/gatewayapi/gatewayapi_controller_test.go
  pkg/crds/operator/operator.tigera.io_gatewayapis.yaml
  pkg/render/common/components/components.go
  pkg/render/egressgateway/egressgateway.go
  pkg/render/egressgateway/egressgateway_test.go
  pkg/render/gateway_api.go
  pkg/render/gateway_api_test.go
  test/gatewayapi_test.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required

#3999 [release-v1.34] Auto pick #3998: Increase the lifecycle.poll_interval for Elasticsearch
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#4001 deps: Bump prometheus to v3
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#3998 Ci 1787 1.36
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3997 [release-v1.38] Auto pick #3996: Increase the lifecycle.poll_interval for Elasticsearch
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3989 Move Calico API server from calico-apiserver namespace to calico-system for OSS
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/apiserver/apiserver_controller_test.go
  pkg/controller/tiers/tiers_controller.go
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
  pkg/render/common/meta/meta.go
  pkg/render/common/networkpolicy/networkpolicy.go
  pkg/render/testutils/expected_policies/dns.json
  pkg/render/testutils/expected_policies/dns_ocp.json
  pkg/render/testutils/expected_policies/node_local_dns_dual.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv4.json
  pkg/render/testutils/expected_policies/node_local_dns_ipv6.json
  pkg/render/tiers/tiers_test.go
  test/mainline_test.go
Labels: docs-pr-required, release-note-required

#4007 fix registry reference for calico/node-fips
  pkg/components/references.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
Labels: docs-pr-required, release-note-required

#3994 Manifest -> operator migration for nftables mode
  pkg/controller/migration/convert/bpf.go
  pkg/controller/migration/convert/handler.go
  pkg/controller/migration/convert/nftables.go
  pkg/controller/migration/convert/nftables_test.go
Labels: docs-pr-required, release-note-required

#4011 Use ComponentGatewayAPIEnvoyGateway instead of ComponentCalicoEnvoyGateway in Enterprise UT
  pkg/render/gateway_api_test.go
Labels: release-note-not-required, docs-not-required

#4014 Render bpffs init container in iptables mode with -skip-cgroup.
  pkg/render/node.go
  pkg/render/node_test.go
Labels: docs-pr-required, release-note-required

#4017 merge tiered policy resource for ee and oss
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/apiserver.go
  pkg/render/apiserver_test.go
Labels: docs-pr-required, release-note-required

#4015 Annotate guardian with cluster version info
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/clusterconnection/shim_test.go
  pkg/controller/utils/utils.go
  pkg/render/guardian.go
Labels: docs-pr-required, release-note-required

#4026 [release-v1.39] Auto pick #4013: Render bpffs init container in iptables mode with
  pkg/crds/enterprise/crd.projectcalico.org_felixconfigurations.yaml
  pkg/render/node.go
  pkg/render/node_test.go
Labels: release-note-not-required, docs-not-required
