Repository tigera/operator, pull requests merged in 2025-05, with the labels that each got.

#3916 Fix typo in test code
  pkg/render/manager_test.go
Labels: release-note-not-required, docs-not-required

#3924 [release-v1.38] Auto pick #3923: Fix that Whisker controller was not watching
  pkg/controller/goldmane/controller.go
  pkg/controller/whisker/controller.go
Labels: release-note-not-required, docs-not-required

#3926 Fix switching to nftables from iptables/BPF dataplane.
  pkg/controller/installation/validation.go
  pkg/controller/installation/validation_test.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready

#3927 [release-v1.38] Auto Release Update for v1.38.0
  config/calico_versions.yml
  hack/gen-versions/main.go
  pkg/components/calico.go
  pkg/components/images.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3925 [Cherry Pick] Add whisker and goldmane finalizers (#3886)
  cmd/main.go
  pkg/controller/apiserver/apiserver_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller.go
  pkg/controller/clusterconnection/clusterconnection_controller_test.go
  pkg/controller/goldmane/controller.go
  pkg/controller/utils/utils.go
  pkg/controller/whisker/controller.go
  pkg/render/finalizers.go
  test/whisker_test.go
Labels: docs-pr-required, release-note-required

#3928 [v1.38] Bump ES and KB
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: docs-pr-required, release-note-required

#3933 migrate to operator with loadbalancer controller enabled
  pkg/controller/migration/convert/core.go
  pkg/controller/migration/convert/core_test.go
Labels: docs-pr-required, release-note-required

#3932 Fix migrating a ebpf cluster from manual to operator.
  pkg/controller/installation/core_controller.go
Labels: docs-pr-required, release-note-required

#3934 [release-v1.38] Auto pick #3932: Fix migrating a ebpf cluster from manual to operator.
  pkg/controller/installation/core_controller.go
Labels: docs-pr-required, release-note-required

#3937 [CORE-11318] : upgrade golang.org libs for calico 3.29.4 CVE
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#3940 [v1.38] Bump go, /x/, ES, KB
  Makefile
  config/enterprise_versions.yml
  go.mod
  go.sum
  pkg/components/enterprise.go
  pkg/render/logstorage.go
  pkg/render/logstorage_test.go
Labels: docs-pr-required, release-note-required

#3941 Use correct cluster domain for Goldmane
  pkg/controller/whisker/controller.go
  pkg/render/whisker/component.go
  pkg/render/whisker/component_test.go
Labels: docs-pr-required, release-note-required

#3945 [release-v1.38] Auto pick #3941: Use correct cluster domain for Goldmane
  pkg/controller/whisker/controller.go
  pkg/render/whisker/component.go
  pkg/render/whisker/component_test.go
Labels: docs-pr-required, release-note-required

#3930 Fix Semaphore environment var name for release tagging [v1.38]
  .semaphore/release.yml
Labels: release-note-not-required, docs-not-required, delete-branch

#3929 Fix Semaphore environment var name for release tagging [master]
  .semaphore/release.yml
Labels: release-note-not-required, docs-not-required, delete-branch

#3947 [release-v1.34] Auto pick #3709: Move skip tenant crds to generic GetCRDS function
  pkg/crds/crds.go
Labels: docs-pr-required, release-note-required

#3946 [release-v1.35] Auto pick #3709: Move skip tenant crds to generic GetCRDS function
  pkg/crds/crds.go
Labels: docs-pr-required, release-note-required

#3942 Allow non-cluster host process to list and update HEPs
  pkg/render/nonclusterhost/nonclusterhost.go
  pkg/render/nonclusterhost/nonclusterhost_test.go
Labels: docs-pr-required, release-note-required

#3944 Update ocp manifest building master
  Makefile
  RELEASING.md
  config/manifests/bases/operator.clusterserviceversion.yaml
  config/manifests/bases/tigera-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  hack/gen-bundle/get-manifests.sh
  hack/gen-bundle/update-bundle.sh
Labels: release-note-not-required, docs-not-required

#3950 [release-v1.36] Auto Release Update for v1.36.9
  config/calico_versions.yml
  hack/gen-bundle/get-manifests.sh
  pkg/components/calico.go
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch

#3957 [release-v1.36] Auto Release Update for v1.36.10
  config/enterprise_versions.yml
  pkg/components/enterprise.go
Labels: release-note-not-required, docs-not-required

#3961 [release-v1.38] Auto Release Update for v1.38.1
  config/calico_versions.yml
  pkg/components/calico.go
  pkg/crds/calico/crd.projectcalico.org_felixconfigurations.yaml
Labels: release-note-not-required, docs-not-required, merge-when-ready, delete-branch
